### PR TITLE
Make SwiftLint ignore autogenerated file API.swift

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by eviltofu** [comment]
@hboon Should `API.swift` be placed in `.gitignore` like the `*.generated.swift` files?

**Comment by hboon** [comment]
@eviltofu might work too. But will have to remove it from the index and make sure it’s always autogenerated for each build. Not sure if it’s done already. A separate change though.

**Comment by eviltofu** [comment]
> @eviltofu will have to remove it from the index and make sure it’s always autogenerated for each build. Not sure if it’s done already. A separate change though.

I checked the build phases. There is a new Apollo phase which explicitly generates the API.swift file.

**Review by eviltofu — APPROVED** [review]
Submit a new issue to ignore or remove API.swift from the repository.

**Pull request merged**
