### PR TITLE
Fix: TokenScript files with invalid signatures are wrongly matched, always to mainnet

### PR DESCRIPTION
**Pull request by hboon**
For #1314

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon test fails for attribute extraction

**Comment by hboon** [comment]
@James-Sangalli Test should be fixed now. Also rebased master.

**Comment by James-Sangalli** [comment]
Thanks

**Comment by hboon** [comment]
> Thanks

Thanks for pointing it out! I keep looking at the wrong place.

**Pull request merged**
