### PR TITLE
Renamed “Run Script” build phase to “Upload debug symbols to Crashlytics"

### PR DESCRIPTION
**Pull request by eviltofu**
Made the intention of the "Run script" clearer.

### CODE REVIEW

**Comment by eviltofu** [comment]
I am thinking that this build phase should be removed. It uploads the debug symbols each time we compile. How will Crashlytics know which is the released debug symbols and which are from the branches developers are working on? No doubt the last upload will be used. We should fold this into the release script of fast lane. @hboon @oa-s

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
> I am thinking that this build phase should be removed. It uploads the debug symbols each time we compile. How will Crashlytics know which is the released debug symbols and which are from the branches developers are working on? No doubt the last upload will be used. We should fold this into the release script of fast lane. @hboon @oa-s

Definitely can't move it into fastlane until it works, but even then, I don't think we need to do that. We can just do a check like this:

```
if [ "${CONFIGURATION}" = "Release" ]; then
```

and the developer who wants to upload it while debugging can comment this out.

Also this build phrase (pre-PR) doesn't work. I have to manually upload the dSYMs for release builds.

**Comment by eviltofu** [comment]
> Also this build phrase (pre-PR) doesn't work. I have to manually upload the dSYMs for release builds.

So this should be filed as an issue? @hboon

**Comment by hboon** [comment]
Sure. Would you help assign it to me?

**Pull request merged**
