### PR TITLE
Add test case to check AmountTextField displays correctly formatted string #2612

### LINKED ISSUE #2612: Add test case to check AmountTextField displays correctly formatted string
This is a follow up for #2590.

Similar to #2452, let's try to stamp out regressions in the send screen.

Maybe something like:

input = 2000 (ethCost?)
asset output = "2000" (and not "2,000")

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2612

### CODE REVIEW

**Comment by hboon** [comment]
Ok. Would you buzz me after #2607 is merged? In case you want to add any related test(s) for it.

**Review by hboon — CHANGES_REQUESTED** [review]
Tests are failing

**Comment by vladyslav-iosdev** [comment]
> Tests are failing

@hboon check it now, should be ok

**Comment by hboon** [comment]
@vladyslav-iosdev I tried to rebase this, but appears to be some conflicts. Would you help to resolve them?

**Comment by hboon** [comment]
Force pushed after rebase master

**Review by hboon — APPROVED** [review]

**Pull request merged**
