### PR TITLE
Added NavigationBarTopSeparatorLine code in Erc1155TokenInstanceViewController to remove the gray line #3813

### LINKED ISSUE #3813: Erc1155TokenInstanceViewController needs to have gray line removed from navigation bar
How to get to this screen:

1. Watch this wallet: `0xE115De7efe6129538C7F6F846801Cd45dF60b36d`
2. Tap Wallet > Assets 
3. Scroll, find, and tap Creepz Invasion Pass
4. Tap Assets, tap Creepz Invasion Pass 

Screen Shot 2022-01-26 at 9 40 40 AM copy

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #3813 

See this [comment](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3813#issuecomment-1022790761).

### CODE REVIEW

**Comment by eviltofu** [comment]
Before
Before
After
After

**Comment by eviltofu** [comment]
@oa-s @hboon Ready for review

**Comment by hboon** [comment]
@eviltofu I took the liberty to edit your before/after comment layout. It's easier to compare this way.

**Review by hboon — APPROVED** [review]

**Comment by eviltofu** [comment]
> @eviltofu I took the liberty to edit your before/after comment layout. It's easier to compare this way.

Except that you can't see the lines when the images are shrunk. That's why I left them at the original resolution.

**Comment by hboon** [comment]
Does it not show up like this on your screen?

Screenshot 2022-01-27 at 3 10 04 PM

**Pull request merged**
