### PR TITLE
Fix: do not add 1gwei to PHI's gas price estimate (because it is already very low: 2000wei as of writing) #4931

### PR DESCRIPTION
**Pull request by hboon**
Fixes: #4931

### CODE REVIEW

**Comment by Phinetwork** [comment]
> Fixes: #4931

Are we able to merge this PR?

**Review by oa-s — APPROVED** [review]

**Comment by Phinetwork** [comment]
Can we merge this PR?

**Comment by Phinetwork** [comment]
Is this merge in the newest update because when go to send still defaults at 1 gwei. Just curious if this merge is already live or will be live in next update

**Comment by hboon** [comment]
@Phinetwork hi! it's been merged into master, but it's not live yet. The release from last week was a release to try something out so it has minimal changes. The next one would include this.

**Comment by Phinetwork** [comment]
> @Phinetwork hi! it's been merged into master, but it's not live yet. The release from last week was a release to try something out so it has minimal changes. The next one would include this.

Awesome thank you for the update appreciate it and your help. 🙏 are we also in the process of getting phi price api added.

**Pull request merged**
