### PR TITLE
Support local-ref

### LINKED ISSUE #1790: Implement ts:local-ref

### PR DESCRIPTION
**Pull request by hboon**
Closes  #1790

@James-Sangalli Left a couple of comments that might cause this PR to not work as expected:

- [x] https://github.com/AlphaWallet/TokenScript-Examples/pull/15#discussion_r422803989
- [x] https://github.com/AlphaWallet/TokenScript-Examples/pull/15#discussion_r422805104
- [x] https://github.com/AlphaWallet/TokenScript-Examples/pull/15#discussion_r422805285
- [x] https://github.com/AlphaWallet/TokenScript-Examples/pull/15#discussion_r422805890

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli can you paste me the wallet address somewhere?

**Comment by James-Sangalli** [comment]
> @James-Sangalli can you paste me the wallet address somewhere?

0x42ea529282DDE0AA87B42d9E83316eb23FE62c3f

**Comment by hboon** [comment]
> Email doesn't resolve (might be because of the comment, I will try that again later) 

@James-Sangalli forced pushed with fix

> but regardless of this it hits an exception of line 122 in AssetAttribute (which shouldn't happen).

How do I reproduce this?

**Comment by James-Sangalli** [comment]
> > Email doesn't resolve (might be because of the comment, I will try that again later)
> 
> @James-Sangalli forced pushed with fix
> 
> > but regardless of this it hits an exception of line 122 in AssetAttribute (which shouldn't happen).
> 
> How do I reproduce this?

Happened by simply clicking through the ENS token card. I am testing your new update now, will get back to you.

**Comment by James-Sangalli** [comment]
@hboon was able to successfully set a new email record: https://etherscan.io/tx/0xe76d1c55776ada393875765a1f41a60f70b9294812c579b6b2c3ae13a1abde39

However, the price for renewal does not load. To reproduce simply click on the renewal action and you will notice the price is set to zero. The console shows that it comes back as a "0" string with no errors.

**Comment by hboon** [comment]
@James-Sangalli fixed. Action attributes that depend on event-based attributes weren't resolved.

This is still true: both token-level and action-level attributes that are dependent on function-based attributes are still not supported. It's complicated. At least for iOS, we might need to rewrite some parts of the resolution code.

**Comment by hboon** [comment]
> The crash has disappeared.

Let me know if you figure it out. There's probably a bug somewhere.

**Comment by James-Sangalli** [comment]
photo_2020-05-14_10-34-51

The price resolves but the value is not registered in the function call data, seems it is missing the ability to take value params as references. Possible to fix in this PR?

**Comment by hboon** [comment]
> The price resolves but the value is not registered in the function call data, seems it is missing the ability to take value params as references. Possible to fix in this PR?

@James-Sangalli Done

**Pull request merged**
