### PR TITLE
Add dark mode to main wallet tab

### PR DESCRIPTION
**Pull request by eviltofu**
Will delete f03d26ec Set appearance to automatic before merging.
Will squash all commits before merging.
Will pull/rebase from master branch before merging.

Simulator Screen Recording - iPhone 11 - 2022-08-15 at 04 58 40

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Screenshot 2022-08-15 at 11 42 49 AM

- [x] The WalletConnect row needs to be updated too. You can connect to WalletConnect here: https://example.walletconnect.org
- [x] Looks like there's a spurious light line/separator at the top of the UITabBar

---

- [x] "Testnet" header:

Screenshot 2022-08-15 at 11 48 12 AM

- [x] The top and bottom separators around the Testnet header:

Screenshot 2022-08-15 at 11 48 37 AM

---

Are the other tabs covered by this PR too? If so, the Collectibles tab need some work around the tokens:

- [ ] Best to remove the borders around the collectibles entirely for darkmode (but verify the images still have rounded corners):

Screenshot 2022-08-15 at 11 47 15 AM

**Comment by eviltofu** [comment]
> Screenshot 2022-08-15 at 11 42 49 AM
> 
> * [ ]  The WalletConnect row needs to be updated too. You can connect to WalletConnect here: https://example.walletconnect.org
> * [ ]  Looks like there's a spurious light line/separator at the top of the UITabBar
> 
> * [ ]  "Testnet" header:
> 
> Screenshot 2022-08-15 at 11 48 12 AM
> 
> * [ ]  The top and bottom separators around the Testnet header:
> 
> Screenshot 2022-08-15 at 11 48 37 AM
> 
> Are the other tabs covered by this PR too? If so, the Collectibles tab need some work around the tokens:
> 
> * [ ]  Best to remove the borders around the collectibles entirely for darkmode (but verify the images still have rounded corners):
> 
> Screenshot 2022-08-15 at 11 47 15 AM

Should this be a header or normal tableview cell? The current background colour is Solitude#e6f3ff. There are no notes on what the dark mode colour should be. I will temporarily choose Mine#2f2f2f until told otherwise.

**Comment by hboon** [comment]
> I will temporarily choose Mine#2f2f2f until told otherwise.

Choose the simplest one (unless there is no simple option). We can fix it.

**Comment by eviltofu** [comment]
Simulator Screen Recording - iPhone 11 - 2022-08-16 at 10 34 15

**Comment by eviltofu** [comment]
image

**Comment by eviltofu** [comment]
image

**Comment by eviltofu** [comment]
image

**Comment by hboon** [comment]
> Is the line above the WalletConnect row supposed to be there? @hboon If it is then this is ready for testing/merge.

Try without it for Dark mode (only).

**Comment by hboon** [comment]
The corner for the collectibles tokens aren't clipped to the rounded corners.

Screenshot 2022-08-16 at 11 10 49 AM

**Review by hboon — APPROVED** [review]
Otherwise shoud be good enough to merge

**Comment by eviltofu** [comment]
> The corners for the collectibles tokens aren't clipped to the rounded corners.
> 
> Screenshot 2022-08-16 at 11 10 49 AM

The background colours don’t match. It’s white for light so I used black for dark but the background is cod. Guess I’ll switch it to cod

**Comment by eviltofu** [comment]
Ok so ... nothing seems to be working ... are we rate limited somewhere? I've watched the hweeboon.eth wallet but it just doesn't show up any collectibles anymore... I've got to use etherscan to get the wallet address manually instead of having the app fetch the address. Without the wallet I can't check the collectibles screen to see if the colours match ...

**Comment by eviltofu** [comment]
image

**Pull request merged**
