### PR TITLE
Create default, fallback icon for ERC1155 tokenIds ("tokens") that don't have token icons #3223

### LINKED ISSUE #3223: Create default, fallback icon for ERC1155 tokenIds ("tokens") that don't have token icons
The small icons and bigger version in these 2 screens respectively:

Small|Big
-|-
Screenshot 2021-09-27 at 1 26 40 PM|Screenshot 2021-09-27 at 1 26 50 PM

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3223

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
I added a commit (look for //hhh) to force the default icon to be used for illustration.

These 2 screens should display the default icon too when their icons aren't available:

&nbsp;|&nbsp;
-|-
Screenshot 2021-12-14 at 11 44 02 AM|Screenshot 2021-12-14 at 11 44 12 AM

And these 2 screens don't seem to display the default icon properly:

&nbsp;|&nbsp;
-|-
Screenshot 2021-12-14 at 11 44 14 AM|Screenshot 2021-12-14 at 11 44 16 AM

**Comment by hboon** [comment]
@vladyslav-iosdev this one's good for review?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev this one's good for review?

yep

**Review by hboon — COMMENTED** [review]
Thanks, the fallback icons appear correctly.

But I noticed that if an icon for an ERC721 token (maybe 1155 too?) is available, it seems to load and cycle through icons from other tokens. eg. Look at the More Loot icon (1st in the screen). It definitely shouldn't show the one with the standing human/zombie:

https://user-images.githubusercontent.com/56189/146506113-2f95d1a4-9008-4708-b061-550bd0df9bde.mp4

And this is the More Loot token: https://opensea.io/collection/more-loot (not sure if they have a collection icon).

It doesn't seem like a problem on the current `master` d93c5474c4d3e8bb059ba1028753498227cff2e0

**Comment by vladyslav-iosdev** [comment]
> https://opensea.io/collection/more-loot

ok, i will check it

**Pull request closed without merging**
