### PR TITLE
With upgraded web3 provider and hooks

### LINKED ISSUE #1323: Build 2.07 288 Dapp browser issue
Compound doesn't work
3E6F2913-EDC5-471F-A73F-E3496125DD7E

### PR DESCRIPTION
**Pull request by James-Sangalli**
Possibly fixes #1323 & #987

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli I'm getting this when I try to "Sign In" at cryptokitties.co:

```
[Error] ReferenceError: Can't find variable: sendResponse
	Global Code (www.cryptokitties.co:1)
```

**Comment by James-Sangalli** [comment]
@hboon if you try with latest commit, does it still fail for you?

**Comment by hboon** [comment]
I see this:

> Failed to load resource: the server responded with a status of 401 ()

pointing to:

> https://api.cryptokitties.co/sign

**Comment by hboon** [comment]
Just in case it was as issue with the cryptokitties site, I tried `master` and it doesn't exhibit the problem. (But it's running on a different simulator, in case that matters).

**Comment by James-Sangalli** [comment]
Shelving for now

**Pull request closed without merging**
