### PR TITLE
Support email doesn't include i os device model #992

### PR DESCRIPTION
**Pull request by Mac3n**
Fix: https://github.com/AlphaWallet/alpha-wallet-ios/issues/992

### CODE REVIEW

**Review by hboon — APPROVED** [review]
That looks great. Thanks for contributing @Mac3n.

Would you help squash the two commits into one and have the commit message summarise the change/reason. Maybe something like:

> Fix: Support email doesn't include iOS device model

?

**Comment by hboon** [comment]
and to rebase master (since it has changed since).

**Comment by Mac3n** [comment]
Thank you @hboon for your comments. I committed the changes as you said.

**Comment by hboon** [comment]
Thanks @Mac3n, just some cleaning up. Code is otherwise great. Could you do this [1]?

1. `git checkout support-email-doesn't-include-iOS-device-model`
2. `git fetch origin master:master` #Assuming `origin` points to the upstream version, i.e. https://github.com/AlphaWallet/alpha-wallet-ios or the git equivalent. This will make sure `master` is updated on your end.
3. `git rebase master` #After this, you should see your 2 commits on top of the `master` branch
4.  Can you now squash the 2 commits together? This is more dependent on your own local setup/tools, so I'll leave it to you. And it's optional. But usually we try to keep changes atomic, in 1 commit where possible [2]
5. Force push

Step 3 is what we generally mean when we say "rebase master".

[1] You probably know all these, but just making it intentionally verbose to not waste your time
[2] But you making it 2 commits when you submit the PR is great. It makes it much easier to review, we just squash it after review.

**Comment by Mac3n** [comment]
Thanks @hboon for your guidance.I hope done it correctly as you want. Excuse me because of any miss understood issues due to being new in the project process

**Comment by hboon** [comment]
@Mac3n :) did you do a `git pull origin master` or something like that? That’s what created the “Merge branch ‘master’” commit. We don’t want that commit. Can you try the steps I outlined above again?

**Comment by hboon** [comment]
BTW if you are stuck and just feeling like ending this, let me know and I can help with the steps and push it for you. Otherwise, I’m happy for you to try.

**Review by hboon — APPROVED** [review]
That's all good now. Thanks @Mac3n!

**Comment by Mac3n** [comment]
Thanks for your help @hboon  :)

**Comment by hboon** [comment]
Well, thanks for *your* help.

**Pull request merged**
