### PR TITLE
ENS avatar shown differently on simulator and device (and both are wrong) #4405

### LINKED ISSUE #4405: ENS avatar shown wrongly (refer to screenshot for device, not simulator)
Title was "ENS avatar shown differently on simulator and device (and both are wrong)".

This might be 2 separate issues:

simulator|device
-|-
Screenshot 2022-04-25 at 11 34 41 AM|

The actual ENS avatar should look like this:

Screenshot 2022-04-25 at 11 38 57 AM

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #4405

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
@oa-s I clarified in https://github.com/AlphaWallet/alpha-wallet-ios/issues/4405#issuecomment-1109369460. But with the PR, it's still showing all green be it simulator or device. (might be hard to verify we seem to be getting rate limited too easily. You might have to host the image yourself just for development)

**Comment by oa-s** [comment]
hmm, actually, yes, let me double check it

**Comment by hboon** [comment]
Works already?

**Comment by oa-s** [comment]
> Works already?

yes, now it works

**Review by hboon — APPROVED** [review]
Great!

**Pull request merged**
