### PR TITLE
[Refactor] Remove code that is no longer needed

### PR DESCRIPTION
**Pull request by eviltofu**
Remove code that is no longer needed

### CODE REVIEW

**Comment by hboon** [comment]
>  5956

@eviltofu that's a PR, do you mean to refer to closing an issue instead?

**Review by hboon — CHANGES_REQUESTED** [review]
Better to explain the "why" where possible:

> Remove code that is no longer needed

**Comment by hboon** [comment]
@eviltofu see earlier feedback: https://github.com/AlphaWallet/alpha-wallet-ios/pull/6339#pullrequestreview-1299119974

**Comment by eviltofu** [comment]
> @eviltofu see earlier feedback: [#6339 (review)](https://github.com/AlphaWallet/alpha-wallet-ios/pull/6339#pullrequestreview-1299119974)

I don't know how to explain it simpler than `Removes empty stub struct Colors { }` or do you mean the title?

**Comment by hboon** [comment]
Use this for the commit message and PR:

> Remove code that is no longer needed

The "why" is explained by "no longer needed".

**Comment by eviltofu** [comment]
@hboon Do I need to make more changes?

**Review by hboon — APPROVED** [review]
All good!

**Pull request merged**
