### PR TITLE
Update replace Double values with NSDecimalNumber value fix precision loss

### LINKED ISSUE #2270: Amount entered into Send fungible (native/ERC 20) screen is not taken as it is
Amount entered into Send fungible (native/ERC 20) screen is not taken as it is

Maybe it's a bug introduced in #2249 ?

This also cause the problem where the user sees and knows there is a balance of "0.1" but is not allowed to enter "0.1"

(screenshot is taken with actionsheet PR, but issue is reproducible on master)

Screenshot 2020-11-12 at 2 26 38 PM

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2270

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
seems like issue not fised in this PR, working on it

**Comment by hboon** [comment]
>seems like issue not fised in this PR, working on it

@vladyslav-iosdev ok. Would you let me know later before you go if it’s good for review and merge? I’ll try to check it these two days

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev ok. Would you let me know later before you go if it’s good for review and merge? I’ll try to check it these two days

@hboon now its available to check

**Comment by vladyslav-iosdev** [comment]
@hboon let me know if it works for u

**Comment by hboon** [comment]
Seem to work great, and fixing the underlying issue. Thanks!

**Comment by hboon** [comment]
Forced push after squashing

**Review by hboon — APPROVED** [review]

**Pull request merged**
