### PR TITLE
When we sign a short message that is still long enough to be truncated, the "Show" button doesn't appear #6221

### LINKED ISSUE #6221: When we sign a short message that is still long enough to be truncated, the "Show" button doesn't appear
Message "Hello there, Boon" on iPhone 14 Pro. It does if the message is much longer

Short, but longer enough|Much longer
-|-
|

Tested with https://sigtool.ambire.com + WalletConnect

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6221

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Same problem now with "Hello there, Bo1" :)

**Comment by oa-s** [comment]
now it should be ok

**Comment by hboon** [comment]
Oh!

**Review by hboon — COMMENTED** [review]
It looks like the `Show` button always show up even when the message is short:

Screenshot 2023-02-06 at 11 14 46 AM

The condition seems wrong. How about we simplify this and just always return true/false so the Show button is always shown?

```
private var availableToShowFullMessage: Bool {
    return false/true //I can't figure out which
}
```

**Comment by oa-s** [comment]
> Show button is always shown?

that would be easier way, let's do that

**Comment by oa-s** [comment]
updated pr with always displaying show more button

**Pull request merged**
