### PR TITLE
Fix stucking on loading screen when call approve(), fix displaying small amounts when confirmation swap action. #6055

### LINKED ISSUE #6055: After initiating a swap on Polygon from WETH to MATIC and confirming the approve(), stuck at "Loading…"
Verified that transaction was confirmed on Polyscan and waited for a bit. Maybe the code to watch for the transaction completion and follow up with the actual swap transaction is not working?

After killing the app and initiating swap again (this time the approve() call wasn't necessary), the actionsheet to confirm the swap transaction appears and works correctly

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6055

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
That seems like quite a lot of changes. Do we know why it didn't work before the PR?

**Comment by oa-s** [comment]
> That seems like quite a lot of changes. Are all the changes needed? Do we know why it didn't work before the PR?

spliting beetwen separate prs

**Comment by oa-s** [comment]
> Do we know why it didn't work before the PR?

yes, loading indicator wasn't  hidden on failure

**Comment by oa-s** [comment]
After #6076

**Pull request merged**
