### PR TITLE
Add bundled token icons #1958

### LINKED ISSUE #1958: Add bundled token icons
Add more bundled token icons into `AlphaWalletAddress+UI.swift`, in `tokenImage`. Watch out that the hardcoded addresses in the switch-case has to be in eip55String (i.e. the correct combination of upper/lowercase) to work correctly.

---

From Tomek at https://github.com/AlphaWallet/alpha-wallet-ios/issues/1665#issuecomment-648022585:

I added 

**a) ptokens:** 

pdai - https://zpl.io/2ENB0GY
psai - https://zpl.io/ag4M3q0
peth - https://zpl.io/2j6QJQr
pbtc - https://zpl.io/2p64JXN
peos - https://zpl.io/VKRPzgP
pusdt - https://zpl.io/VYvKE4L
pltc - https://zpl.io/a7AO00v

b) synthetix tokens

saud - https://zpl.io/VkqG6Lv
sgbp - https://zpl.io/boqDXWo
seur - https://zpl.io/aXxPvD8
sjpy - https://zpl.io/aR51pBr
schf - https://zpl.io/2yAOZXp
susd - https://zpl.io/V049Ej9
sbtc - https://zpl.io/V04qB6l
sxtz - https://zpl.io/2GKy0Nd
sxmr - https://zpl.io/VYvKEmJ
sdefi - https://zpl.io/bJm7Rj3
sada- https://zpl.io/2p64JYN
sltc - https://zpl.io/bJm7Rl9
seth - https://zpl.io/boqDXOW
snikkei - https://zpl.io/bzgNZJ4
sxau - https://zpl.io/aR51JMg
slink - https://zpl.io/beqDEwP

**c) others**
teo - https://zpl.io/a7AO9ZR
eos - https://zpl.io/bzgNEWX
nest - https://zpl.io/VQXLZ74 
link - https://zpl.io/agpvKqO
alphawallet discovery token - https://zpl.io/25D5OwW

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1958

### CODE REVIEW

**Comment by hboon** [comment]
We have a convention, either add the WIP, don’t merge label to the PR and/or make the PR a draft. Not a very big deal though.

**Comment by vladyslav-iosdev** [comment]
> We have a convention, either add the WIP, don’t merge label to the PR and/or make the PR a draft. Not a very big deal though.

ok, got it.

**Comment by vladyslav-iosdev** [comment]
> func foo() {
> 
>         let l = [
>         "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643",
>         "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359",
>         "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
>         "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
>         "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
>         "0x493C57C4763932315A328269E1ADaD09653B9081",
>         "0x47421d4d41196475cd9f84cc3fcda056ba6bde64",
>         "0x5228a22e72ccc52d415ecfd199f99d0665e7733b",
>         "0xf53ad2c6851052a81b42133467480961b2321c09",
>         "0x429D83Bb0DCB8cdd5311e34680ADC8B12070a07f",
>         "0xea5c61205fB4A255Af041E8350AAA9343C516E55",
>         "0xbd31496feb604f9ec6a1c78c3371f8cfd220f5f2",
>         "0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0",
>         "0x04abeda201850ac0124161f037efd70c74ddc74c",
>         "0x514910771af9ca656af840dff83e8264ecf986ca",
>         "0x5401b9687a08b15cfca344edec7c1486bdaf9e32",
>         "0xbbc455cb4f1b9e4bfc4b73970d360c8f032efee6",
>         "0x261efcdd24cea98652b9700800a13dfbca4103ff",
>         "0x757de3ac6b830a931ef178c6634c5c551773155c",
>         "0x5e74c9036fb86bd7ecdcb084a0673efc32ea31cb",
>         "0xc14103c2141e842e228fbac594579e798616ce7a",
>         "0xe36e2d3c7c34281fa3bc737950a68571736880a1",
>         "0xe1afe1fd76fd88f78cbf599ea1846231b8ba3b6b",
>         "0x5299d6f7472dcc137d7f3c4bcfbbb514babf341a",
>         "0x2e59005c5c0f0a4d77cca82653d48b46322ee5cd",
>         "0xfe18be6b3bd88a2d2a7f928d00292e7a9963cfc6",
>         "0x57ab1ec28d129707052df4df418d58a2d46d5f51",
>         "0x0f83287ff768d1c1e17a42f44d644d7f22e8ee1d",
>         "0xf6b1c627e95bfc3c1b4c9b825a032ff0fbf3e07d",
>         "0xd71ecff9342a5ced620049e616c5035f1db98620",
>         "0x97fe22e7341a0cd8db6f6c021a24dc8f4dad855f",
>         "0xf48e200eaf9906362bb1442fca31e0835773b8b4"
>         ]
> 
>         for each in l {
>             if AlphaWallet.Address(string: each)?.eip55String == each {
>                 NSLog("xxx match: \(each)")
>             } else {
>                 NSLog("xxx not match: \(each)")
>             }
>         }
>     }

@hboon Am i undastand right, i need to update `tokenImage` raw values with eip55String their values?

**Comment by hboon** [comment]
> Am i undastand right, i need to update tokenImage raw values with eip55String their values?

Yes, you need to run something like: `AlphaWallet.Address(string: "0xabc")?.eip55String` for each of them and let `tokenImage` return that version so that the `foo()` func above matches.

We could have do it less manually by just relying on `AlphaWallet.Address.sameContract(as:)` But using it is much slower at runtime. Hardcoding the the EIP55 version is much faster and we can use it a giant Switch (or dictionary). We can probably rename the image files too, but that bypasses `R` and is a bit less type-safe. So we'll see how this approach goes.

**Pull request merged**
