### PR TITLE
improve displaying accounts view #4436

### LINKED ISSUE #4436: improve displaying accounts view

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4436

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
How is it improved?

**Comment by oa-s** [comment]
> How is it improved?

I will record a video of how it works

**Comment by oa-s** [comment]
### After PR

https://user-images.githubusercontent.com/96283950/165448592-fc7c0208-384c-459e-9e52-afd665bd4673.MP4

### Before PR

https://user-images.githubusercontent.com/96283950/165448611-a55fb53a-04f0-48ba-ac77-bdafd25bba35.MP4

**Comment by oa-s** [comment]
Merge after https://github.com/AlphaWallet/alpha-wallet-ios/issues/4405

**Review by hboon — APPROVED** [review]

**Pull request merged**
