### PR TITLE
Display suggestions from wordlist when typing seed phrase to import

### LINKED ISSUE #1568: Display suggestions when importing seed phrase
Please use Moonlight app as a reference. 
Please improve the look of segmented controls. 

Import_with_Seed_iOS

### PR DESCRIPTION
**Pull request by hboon**
Closes #1568 

Supersedes #1799 

After PR:

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon looks good but when you get to the next work the last word hangs there, is that supposed to happen?

**Comment by hboon** [comment]
@James-Sangalli I guess we can remove the suggestions when there's only 1 word and it matches the last word?

I just noticed a strange side-effect, if you type: "tea" and it suggests "teach team" and you tap one of the words, the suggests "teach team" still appear. It wasn't intended but looks like it's nice to keep it around because you can tap again to correct it. What do you think?

**Comment by James-Sangalli** [comment]
> @James-Sangalli I guess we can remove the suggestions when there's only 1 word and it matches the last word?
> 
> I just noticed a strange side-effect, if you type: "tea" and it suggests "teach team" and you tap one of the words, the suggests "teach team" still appear. It wasn't intended but looks like it's nice to keep it around because you can tap again to correct it. What do you think?

well it should only suggest one word, cannot suggest two words at once... 

Why not simply clear the last suggestion and start fresh when you go onto the new word? The past word has zero influence on the next.

**Comment by hboon** [comment]
It's autocompletion.

tea -> Possible words are "teach" and "team". So 2 words suggested, with the prefix "tea".

It still displays the suggestions "teach" and "team" after tapping on one of them, but before typing the next word. So while it's a bit odd, I'm thinking that the user can tap it again to choose a different word if they have tapped wrongly. eg.

1\. Start with ""
2\. Type "tea". Suggests "teach" and "team"
3\. Tap "teach". Now shows "teach" in the textbox. Still suggests "teach" and "team"
4\. Whoops, tapped wrongly. Tap "team". Now shows "team in the textbox.

**Comment by hboon** [comment]
> Why not simply clear the last suggestion and start fresh when you go onto the new word? The past word has zero influence on the next.

Yes, that or keep the strange behavior, which seems useful https://github.com/AlphaWallet/alpha-wallet-ios/pull/1821#issuecomment-632573266

**Pull request merged**
