### PR TITLE
[Update] Replaced old mascot_happy image with new light and dark mode images

### LINKED ISSUE #5288: List of missing images for dark mode
There are some images which are required for dark mode. 

- [x] [#5267 Large logo](https://github.com/AlphaWallet/alpha-wallet-ios/pull/5267)

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #5288

# Changes

Background color has been modified because in dark mode with Configuration.Color.Semantic.dialogBackground (black) background, the centre ball of the logo does not show up.

Simulator Screen Shot - iPhone 14 Pro - 2023-03-10 at 00 39 07 copy

# Screen shots

Device | Light | Dark
-|-|-
iPhone SE 3 | iPhoneSE3-light | iPhoneSE3-dark
iPhone 14 Pro | iPhone14Pro-light | iPhone14Pro-dark
iPad Pro 6 | iPadPro6-light | iPadPro6-dark

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Can you help rename the image files to be like what we had — icon-200x200 etc? The filenames that GitHub creates for uploads are unwieldy.

**Comment by hboon** [comment]
@eviltofu and this is not a refactor (have to fix the PR title and commit message)

**Comment by eviltofu** [comment]
@hboon updated file names, pr title, and commit message.

**Review by hboon — APPROVED** [review]
Thanks! Not sure "[Update]" is informative though. I usually leave them out if I can't think of anything better.

**Pull request merged**
