### PR TITLE
Set `next` bool bar button for `inputAccessoryButtonType: InputAccess

### LINKED ISSUE #5784: Tapping Done button in Custom gas ("Set Speed") screen does nothing so we can't set custom gas for transactions

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #5784

### CODE REVIEW

**Comment by oa-s** [comment]
looks like we have to check `Done` `Next` buttons, not always work properly, we could use `IQKeyboardManager` really helps with keyboard.

**Comment by hboon** [comment]
Let's try `IQKeyboardManagerSwift` then

**Comment by oa-s** [comment]
@hboon while adding `IQKeyboardManager` i found that it can't resolve next response (when next button selected) for complex view hierarchy. This resoles by setting `self.view` for `UIViewController`.So we have to inherit out view controllers from newvelly added one `ViewController`. is that acceptable, or we need look for an another solution? its related to screens with multiple inputs.

**Comment by hboon** [comment]
Hmm.. How about if we do it (focus next and scroll) manually? If we need it for more screens, we can find a more general approach? It looks like this might be the only screen in the app that is tall with textboxes

**Pull request merged**
