### PR TITLE
Increased size of logo on launch screen

### LINKED ISSUE #4672: App icon on "launch" screen looks a little small
Want to tweak it, @colourfreak ? Maybe at least bigger to close match the app icon size in the homescreen?

IMG_6A29A449417D-1

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #4672 

Somehow I am not able to view the launch screen with the new logo on the simulator but I am able to see the new logo when testing on hardware.

### CODE REVIEW

**Comment by oa-s** [comment]
Have you tried to reinstall the app?

**Comment by eviltofu** [comment]
> Have you tried to reinstall the app?

Yes but it doesn't appear to work for my simulator. It works on my iPhone X.

**Comment by eviltofu** [comment]
The PR should be closed. I have done the same thing in #4700.

**Comment by hboon** [comment]
@eviltofu is this working as expected? if it is, lets merge it unless #4700 is already ready (and it's supposed to do a different thing any way)

**Pull request closed without merging**
