### PR TITLE
2985 improve backup screen

### PR DESCRIPTION
**Pull request by Mac3n**
Fixes https://github.com/AlphaWallet/alpha-wallet-ios/issues/2985

[x] kill the thin, top, gray line
[x] break down the text into
[x] Increase the picture size
[x] Make the text break accordingly
[ ] Move the bottom button a bit more to the top -> Remain out of scope because of dependency on other views.

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Thanks @Mac3n. Works great! Could you help rebase master? Probably something like:

1. git checkout 2985-imporove-backup-screen #correct branch
2. git fetch upstream master:master #replace `upstream` with your remote pointing to https://github.com/AlphaWallet/alpha-wallet-ios
3. git rebase master #make it so your PR contains the latest commits from `master`

And to change the commit message?

The current commit message is quite descriptive (good!):

```
 fix issues
    
    - kill the thin, top gray line
    - break down text
    - increase picture size
```

But if we make the first line a summary, eg. "Tweak backup intro screen layout", we'll see that first line when we run `git log  --pretty=oneline`. (useful when we want to look through many commits for various reasons)

If you have configured `$EDITOR`, this might work:

```
git commit --amend
```

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Thank you @Mac3n !

**Comment by Mac3n** [comment]
Your welcome @hboon . I am glad to could help more in the project.
Please feel free to assign a task to me if you need it.

**Comment by hboon** [comment]
@Mac3n Sure, would you help give #2987 a go? It probably involves a slight change in flow.

**Pull request merged**
