### PR TITLE
Show a generic "token" icon in send screen when sending ERC20 token #1883

### LINKED ISSUE #1883: Show a generic "token" icon in send screen when sending ERC20 token
In `SendViewController`, assuming the ERC20 token has the symbol "OMG".

This icon:

https://app.zeplin.io/styleguide/5e0b15e46049c216fb7ab4d5/components?coid=5e27130e1d43768074cedd2d

Remember to handle 4 cases to update or not to update `SelectCurrencyButton` correctly:

- [x] User tapped the OMG token in the wallet tab
- [x] User tapped ETH in the wallet tab and then scan an EIP681 link with OMG token
- [x] User tapped ETH in the wallet tab and then scan an EIP681 link for ETH
- [x] User tapped the OMG token in the wallet tab and then scan an EIP681 link with OMG token
- [x] User tapped the OMG token in the wallet tab and then scan an EIP681 link with ETH token

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1883

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev 

A. When we tap on the DAI card to send, it shows this. It's good:



B. But when we tap on ETH, and then scan an EIP681 to send DAI, it becomes:



Can you make the result of (B) work/look like (A)?

- [  ] So the down arrow is hidden
- [  ] and also tapping the DAI button shouldn't toggle to fiat

C. Also verify that when user tap ERC20 and then scan and EIP681 to send ETH (i.e the reverse o

**Comment by vladyslav-iosdev** [comment]
> C. Also verify that when user tap ERC20 and then scan and EIP681 to send ETH (i.e the reverse of B), that it shows the ETH icon + down arrow + ability to tap to toggle to fiat

@hboon  Am i undarstand correctly, if i tap DAI than scan an ETH, it should show fiat button, and switch will be between DAI and ETH or ETH and USA?

**Comment by hboon** [comment]
@vladyslav-iosdev 
> Am i undarstand correctly, if i tap DAI than scan an ETH, it should show fiat button, and switch will be between DAI and ETH or ETH and USA?

No. It's always just "DAI" (or whatever ERC20 token) or switch between ETH and USD.

There are only 2 possible states for the send screen:
(not using A and B to avoid confusion with previous labelling)

X) Eth (`.nativeCryptocurrency`) — can only toggle between Eth and USD
Y) ERC20 token (eg. DAI) — User can't toggle

The user might tap Eth to reach (X), or tap Eth/ERC20 and scan EIP681 for Eth to reach (X).
The user might tap ERC20 to reach (Y), or tap Eth/ERC20 and scan EIP681 for ERC20 to reach (Y).

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev
> 
> > Am i undarstand correctly, if i tap DAI than scan an ETH, it should show fiat button, and switch will be between DAI and ETH or ETH and USA?
> 
> No. It's always just "DAI" (or whatever ERC20 token) or switch between ETH and USD.
> 
> There are only 2 possible states for the send screen:
> (not using A and B to avoid confusion with previous labelling)
> 
> X) Eth (`.nativeCryptocurrency`) — can only toggle between Eth and USD
> Y) ERC20 token (eg. DAI) — User can't toggle
> 
> The user might tap Eth to reach (X), or tap Eth/ERC20 and scan EIP681 for Eth to reach (X).
> The user might tap ERC20 to reach (Y), or tap Eth/ERC20 and scan EIP681 for ERC20 to reach (Y).

i guess i realized where problem was. now should be ok.

**Comment by hboon** [comment]
@vladyslav-iosdev I think it's — being able to toggle to fiat and the down arrow appearing after scanning EIP 681 link for Dai — still happening if you wait for a while. Here's the sequence to reproduce it:

1. Tap ETH card in wallet tab
2. Scan EIP681 link for ERC20
3. Cannot toggle to fiat and down arrow doesn't appear as expected
4. Wait
5. Down arrow appears and user can toggle to fiat again

Maybe it's due to either the balance or ETH price being refreshed triggering the UI to be reloaded?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev I think it's — being able to toggle to fiat and the down arrow appearing after scanning EIP 681 link for Dai — still happening if you wait for a while. Here's the sequence to reproduce it:
> 
> 1. Tap ETH card in wallet tab
> 2. Scan EIP681 link for ERC20
> 3. Cannot toggle to fiat and down arrow doesn't appear as expected
> 4. Wait
> 5. Down arrow appears and user can toggle to fiat again
> 
> Maybe it's due to either the balance or ETH price being refreshed triggering the UI to be reloaded?

@hboon  now should be ok

**Pull request merged**
