### PR TITLE
Hide bottom bar for send token screen when pushing #5574

### LINKED ISSUE #5574: Hide bottom bar for send token screen when pushing

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5574

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
How do you reproduce this, or a before/after PR screenshots pair?

**Comment by oa-s** [comment]
it appears after sacaning any eip681 qrcode

**Comment by oa-s** [comment]
will update pr

**Comment by oa-s** [comment]
Before pr

https://user-images.githubusercontent.com/96283950/195798572-273fa0c3-4e12-4c3f-ae17-63e38ffa5290.MP4

**Comment by oa-s** [comment]
After pr

https://user-images.githubusercontent.com/96283950/195800115-ba648396-6685-42cd-94ae-5ffcd5b3f00b.MP4

**Review by hboon — APPROVED** [review]
I see! Thanks. Would you help mention that this fixes it when scanning an EIP681 QR code?

**Review by hboon — APPROVED** [review]

**Pull request merged**
