### PR TITLE
App icon in launch (aka splash) screen should not move (up) abruptly #1897

### PR DESCRIPTION
**Pull request by hadwanihardik**
Fixes : #1897

### CODE REVIEW

**Comment by hadwanihardik** [comment]
@hboon I have changed commit message to proper sentence.

**Comment by hboon** [comment]
@hadwanihardik thanks. Will look at it soon.

**Comment by hadwanihardik** [comment]
@hboon any have you reviewed?

**Comment by hboon** [comment]
@hadwanihardik not yet. But you can consider it done on your side. Thanks.

**Pull request closed without merging**
