### PR TITLE
Added dark mode to WellDoneViewController

### PR DESCRIPTION
**Pull request by eviltofu**
image 
Light mode

image
Dark mode

### CODE REVIEW

**Comment by eviltofu** [comment]
The image needs to be updated for dark mode.

**Comment by hboon** [comment]
> The image needs to be updated for dark mode.

So we have the small version of the icon  for dark mode, but not bigger version(s)? Can you help make a list of all these in a new issue? Then we can collect them and update at one go.

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
> > The image needs to be updated for dark mode.
> 
> So we have the small version of the icon for dark mode, but not bigger version(s)? Can you help make a list of all these in a new issue? Then we can collect them and update at one go.

@eviltofu in case you missed this

**Comment by eviltofu** [comment]
Going to see if there are any dark mode logos I can reuse.

**Pull request merged**
