### PR TITLE
Make "Add / Hide Tokens screen" table resize when keyboard is shown/hidden for searching #1990

### LINKED ISSUE #1990: Make "Add / Hide Tokens screen" table resize when keyboard is shown/hidden for searching

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1990

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon this PR depends on #1993

**Comment by hboon** [comment]
@vladyslav-iosdev is this good for review?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev is this good for review?

yes

**Comment by hboon** [comment]
@James-Sangalli you want to take a look?

**Comment by hboon** [comment]
@James-Sangalli bump

**Review by James-Sangalli — APPROVED** [review]

**Pull request merged**
