### PR TITLE
Update Ethereum Classic Endpoints

### PR DESCRIPTION
**Pull request by antsankov**
This PR updates the block explorer and RPC endpoints for Ethereum Classic:

- Gastracker.io has unfortunately gone out of business (all of their pages redirect to the new service Emerald.cash), so the ETC community uses Blockscout now for a block explorer (https://blockscout.com/etc/mainnet/)

- For Web3 Endpoints, ethereumclassic.network and Gastracker are no longer reliable, so the ETC Cooperative launched Ethercluster.com which is an Infura for ETC. The endpoint provided is what is on their main page, and used in a variety of ETC applications/wallets.

Let me know if there are any other areas that need changing or questions, I am happy to help Alpha Wallet support Ethereum Classic!

### CODE REVIEW

**Comment by hboon** [comment]
@antsankov thanks! Would you help to update `ConfigExplorer.explorerName(for:)` too?

**Comment by antsankov** [comment]
Did it! @hboon (https://github.com/antsankov/alpha-wallet-ios/blob/master/AlphaWallet/Settings/Types/ConfigExplorer.swift#L37)

Was there any more files I missed with ETC references?

**Comment by hboon** [comment]
@antsankov maybe a quick check to see if `RPCServers.transactionInfoEndpoints` is correct? Then buzz @James-Sangalli once you are happy with it. Thanks again.

**Comment by antsankov** [comment]
@hboon - good call. I added in some more endpoints on the constants page, and verified the RPC information is correct. Commits are squashed and ready for commit @James-Sangalli 

Let me know if you see anything I'm missing, and thanks for the guidance!

**Pull request merged**
