### PR TITLE
[Refactor] Changed all Colors.clear to Configuration.Color.Semantic.backgroundClear and Configuration.Color.Semantic.borderClear. No change in actual color.

### PR DESCRIPTION
**Pull request by eviltofu**
I didn't see a need to have a color called clear when we already have .clear.

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
I don't know why it was added, but keeping it might be better. Say we want to debug colors and figure out where/if it is use in a certain screen? We can override the value to `.red` with alpha and it'll jump out.

**Comment by hboon** [comment]
If we keep it, can you add a comment to the color definition to explain why?

**Comment by eviltofu** [comment]
> I don't know why it was added, but keeping it might be better. Say we want to debug colors and figure out where/if it is use in a certain screen? We can override the value to `.red` with alpha and it'll jump out.

We would need to split this into two. There is a clear for borders and clear for backgrounds. I'd split them into `clearBackground` and `clearBorder`. @hboon

**Comment by oa-s** [comment]
> I don't know why it was added, but keeping it might be better. Say we want to debug colors and figure out where/if it is use in a certain screen? We can override the value to .red with alpha and it'll jump out.

the idea was to keep colors in single namespace, `Colors` as it was, its easier to track actual used colors and yes, override them when needed.

**Comment by hboon** [comment]
>> I don't know why it was added, but keeping it might be better. Say we want to debug colors and figure out where/if it is use in a certain screen? We can override the value to .red with alpha and it'll jump out.
> We would need to split this into two. There is a clear for borders and clear for backgrounds. I'd split them into clearBackground and clearBorder

> Does this make sense?

@eviltofu Yes, this works; bottom line is to not replace them with `UIColor.clear`

**Comment by hboon** [comment]
Remember to update PR title and commit messages too.

**Comment by eviltofu** [comment]
Needs approval @hboon

**Review by hboon — APPROVED** [review]

**Pull request merged**
