### PR TITLE
Sort tokens Value: Descending in the Wallet tab by default #3528

### LINKED ISSUE #3528: Sort tokens Value: Descending in the Wallet tab by default
Native coin should go first for a network, then the rest with the value descending. Usually, you are the most interested in tokens that have the highest value in your wallet.

- Ethereum
- Token with the highest value in USD
- Token with the second highest value in USD
- Token with the third highest value in USD
- ...

**Now:**

**Should be:**
Screenshot 2021-12-10 at 12 24 48

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3528

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Descending by fiat value, not by name :)

So those with fiat value first, most $ first and then followed by those without fiat value, by name ascending.

Now that we put it that way, let's see it in action if it makes sense..

**Comment by hboon** [comment]
@vladyslav-iosdev Good for review?

**Comment by vladyslav-iosdev** [comment]
@hboon bump

**Comment by hboon** [comment]
@vladyslav-iosdev by the fiat value (eg $10k of ETH) not the ticket price.

**Comment by vladyslav-iosdev** [comment]
@hboon not it should be ok

**Review by hboon — CHANGES_REQUESTED** [review]
Seems wrong (eg. $1.4 and $0.7 should be before $0):

Screenshot 2021-12-16 at 10 59 21 AM

**Comment by vladyslav-iosdev** [comment]
@hboon if i get it right, we don't sort eth by fiat value, and it's going to be first all the time, right?

**Comment by hboon** [comment]
> @hboon if i get it right, we don't sort eth by fiat value, and it's going to be first all the time, right?

Yes, you are right. I missed that. The native token for each chain goes first, no matter its value.

**Comment by vladyslav-iosdev** [comment]
> Yes, you are right. I missed that. The native token for each chain goes first, no matter its value.

ok, now should be fine

**Review by hboon — APPROVED** [review]

**Pull request merged**
