### PR TITLE
[Samoa] Add summary/total to Wallet tab for current wallet #2755

### LINKED ISSUE #2755: [Samoa] Add summary/total to Wallet tab for current wallet
Just the thing in the navigation bar

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/6045ee59577f8ba371b3deac

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes  #2755

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Seems ok visually, but because it's "All Wallets" in Zepplin. I think it's supposed to be the total across all wallets.

**Comment by vladyslav-iosdev** [comment]
hmm, ok. i thought that its related to selected wallet, as described in issue title.

**Comment by hboon** [comment]
Oh sorry. I only notice it’s all Wallets a few days ago and forgot to update the title of the issue

**Comment by vladyslav-iosdev** [comment]
> Oh sorry. I only notice it’s all Wallets a few days ago and forgot to update the title of the issue

ok, so does it mean that we need to create a new screen for all tokens of all wallets and show it by selection on `total summary` from `all wallets screen`?

**Comment by hboon** [comment]
How about this, if you haven't made the change to show the total for all wallets in the top section, let's just keep it as the total for the current wallet. If you have already made it, let's show the total for all wallets.

Either way, let's keep the rest of the wallet tab for just the current wallet. (It'll be a major change otherwise)

**Comment by hboon** [comment]
i.e. this PR just changes that top summary section of the Wallet tab

**Comment by vladyslav-iosdev** [comment]
> i.e. this PR just changes that top summary section of the Wallet tab

ok, got it. in current impl. displays `total info` for selected wallet. in this case no changes is needed.

**Comment by hboon** [comment]
Great thanks!

**Review by hboon — APPROVED** [review]
Merge when you are ready

**Pull request merged**
