### PR TITLE
[Samoa] Improve Add/Hide Tokens screen #2994

### LINKED ISSUE #2994: [Samoa] Improve Add/Hide Tokens screen
This is one of the last, major changes in regards to Samoa. I think we discussed this part somewhere else, but I could not find this. 

**I recorded two explainer videos:**
https://drive.google.com/file/d/1uG9gtK-TTwSxt2rJU-NpHIreakEYriTC/view?usp=sharing
https://drive.google.com/file/d/1AqZY531iIGT9tzM83vDEMd6EmISwzLit/view?usp=sharing

**What we are changing:**
- I moved the Add/Hide Tokens to the very bottom under all tokens in the wallet tab
- I moved the search bar where Add/Hide Tokens button was before
- I made the search bar in the wallet tab works exactly the same as the one in Add/Hide Tokens. 
- I removed an option to manually reorder tokens inside Add/Hide Tokens
- I added sorting options: by Name, by Value, Most Used
- The search box should have also not displayed tokens in the search results. It means, that we can add a database of tokens (James did this very well) and display tokens while searching for them. 

https://zpl.io/2GqwPL4

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2994

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Seems ok so far. How do you sort by "Most Used"?

What else is left?

**Comment by vladyslav-iosdev** [comment]
> Seems ok so far. How do you sort by "Most Used"?
> 
> What else is left?

hah, btw wanted to ask how we need to sort the `most used` tokens? i am waiting to

**Comment by hboon** [comment]
Ah, I see :) Can you remove that sort option first and just build that empty token screen without the image. Let's merge it and we can add those in when we have the details.

**Comment by vladyslav-iosdev** [comment]
> Ah, I see :) Can you remove that sort option first and just build that empty token screen without the image. Let's merge it and we can add those in when we have the details.

btw, for the placeholder image we can left the image that is using for now for empty views

**Comment by hboon** [comment]
Sounds good :)

**Review by hboon — APPROVED** [review]

**Pull request merged**
