### PR TITLE
UI refresh. Lighter-looking, more consistent UI

### LINKED ISSUE #1510: Update UI to be lighter

### PR DESCRIPTION
**Pull request by hboon**
Closes #1510 

Expecting there to be some follow up GitHub issues and PRs to fix it up.

This is on TestFlight as v2.17 (310)

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon checking it out

**Comment by hboon** [comment]
@James-Sangalli are you referring to it saying “-1088247”?

**Comment by James-Sangalli** [comment]
> @James-Sangalli are you referring to it saying “-1088247”?

Yes, believe this is the token id

**Comment by hboon** [comment]
Yes, I think it’s been like that for a while :)

**Comment by zhangzhongnan928** [comment]
0B79A24F-296C-4813-9172-2D169F5F55D1
38C0068C-263A-4231-B43D-1860F6071496

all my erc721 tokens become same in collectables tab. They work fine in the all tab.

**Comment by hboon** [comment]
@zhangzhongnan928 Thanks for catching the collectibles bug! I'll create a separate issue for the DAI symbol name. I can't reproduce it. #1540 

@James-Sangalli forced push, fixing the collectibles bug. Good for review again.

**Comment by hboon** [comment]
Will be available on TestFlight as v2.17 (311)

**Comment by James-Sangalli** [comment]
> @zhangzhongnan928 Thanks for catching the collectibles bug! I'll create a separate issue for the DAI symbol name (because it's a separate bug and I thought we have fixed it). I can't reproduce it. #1540
> 
> @James-Sangalli forced push, fixing the collectibles bug. Good for review again.

@hboon  You can't reproduce the DAI bug?

**Comment by hboon** [comment]
> @hboon You can't reproduce the DAI bug?

Oh, it's only reproducible on my phone, not simulator. I can reproduce it now. Will fix it separately.

**Comment by hboon** [comment]
@James-Sangalli  Hold on. Network name when adding custom token isn't displayed in the correct color

**Comment by hboon** [comment]
Missing closing parenthesis bug fixed in #1543

**Comment by hboon** [comment]
Build 313.

**Pull request merged**
