### PR TITLE
Remove Subscribable from TokenBalanceService #4106

### LINKED ISSUE #4106: Remove Subscribable from TokenBalanceService

### LINKED ISSUE #4118: New iOS Release Fails to Read the True ETH Balance and Can't Send
The new update for iOS fails to read the ETH balance on the info page and also it doesn't allow send the token. Observe that the main page shows the balance in ETH but not the value in USD. I attach screenshots.

image

image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4106 Closes #4118

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s this is essentially replacing `Subscribable`s with publishers, right?

**Comment by oa-s** [comment]
> @oa-s this is essentially replacing `Subscribable`s with publishers, right?

yes

**Comment by oa-s** [comment]
and it moves balance fetching up to main thread

**Comment by hboon** [comment]
> up to main thread

So good :)

**Comment by oa-s** [comment]
@hboon  The PR is ready for review

**Review by hboon — APPROVED** [review]
Just have to trust you for it :)

**Pull request merged**
