### PR TITLE
Add dark mode to initial network selection screen

### PR DESCRIPTION
**Pull request by eviltofu**
I think I might need dark versions of the check boxes, and the empty view graphic. I will rebase, squash, and restore the appearance settings before merge. The pop up PromptViewController is also hard to distinguish between the background and the Prompt.

image image

image
Overall view

image
Empty filter results

image
Popup

### CODE REVIEW

**Comment by hboon** [comment]
> I think I might need dark versions of the check boxes, and the empty view graphic. I will rebase, squash, and restore the appearance settings before merge. The pop up PromptViewController is also hard to distinguish between the background and the Prompt.

You can also see if the Android Zeplin has them already if the one on iOS doesn't. Otherwise let's merge it in anyway. It's not enabled yet so not going to be a problem. Better merge sooner than later.

**Comment by colourfreak** [comment]
> image

Please make the checkboxes with white #ffffff in dark mode

Screen Shot 2022-07-20 at 14 04 31

**Comment by colourfreak** [comment]
image

Working on it...

**Comment by hboon** [comment]
> Please make the checkboxes with white #ffffff in dark mode

Created #5020

**Comment by eviltofu** [comment]
> image
> 
> Working on it...
@colourfreak 
Ok the light mode version is also off. I just detected it. Maybe transparent background?
image

**Comment by hboon** [comment]
@eviltofu better to create a new issue. Easy to be lost

**Comment by colourfreak** [comment]
> @eviltofu better to create a new issue. Easy to be lost

#5042 
#5041

**Pull request merged**
