### PR TITLE
After scanning QR code during import wallet during onboarding, switch to the appropriate tab #2354

### LINKED ISSUE #2354: After scanning QR code during import wallet during onboarding, switch to the appropriate tab
Eg. if the QR code is an address, we should switch to the `Watch` tab and populate the textbox. Similarly, if

* Address, switch to "Watch"
* Looks like JSON (maybe just check start with "{"), switch to "Keystore JSON" tab
* Multiple words with spaces (maybe a split by " " and if there are a few words?) switch to "Seed" tab
* 64 character string with no spaces, switch to "Private key"

This screen:

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2354

### CODE REVIEW

**Review by James-Sangalli — CHANGES_REQUESTED** [review]
@vladyslav-iosdev everything is working except if I scan a private key, if I scan a private key it takes me to the seed phrase tab rather than the private key tab

Edit: sorry I scanned the wrong thing, let me get back to you

**Comment by vladyslav-iosdev** [comment]
> everything is working except if I scan a private key, if I scan a private key it takes me to the seed phrase tab rather than the private key tab

@James-Sangalli  i suggest that checking for string length is not enough for private key, isn't it? maybe u have any suggestions how i can update it?

**Comment by vladyslav-iosdev** [comment]
@James-Sangalli what value did u use for private key? can u she example with me?

**Comment by James-Sangalli** [comment]
> @James-Sangalli what value did u use for private key? can u she example with me?

@vladyslav-iosdev you can generate on here: https://vanity-eth.tk/ make it into a QR code and scan it, you will see what i mean (you might have to prefix with 0x however)

**Comment by vladyslav-iosdev** [comment]
> > @James-Sangalli what value did u use for private key? can u she example with me?
> 
> @vladyslav-iosdev you can generate on here: https://vanity-eth.tk/ make it into a QR code and scan it, you will see what i mean (you might have to prefix with 0x however)

check is, now it should be ok.

**Comment by James-Sangalli** [comment]
> > > @James-Sangalli what value did u use for private key? can u she example with me?
> > 
> > 
> > @vladyslav-iosdev you can generate on here: https://vanity-eth.tk/ make it into a QR code and scan it, you will see what i mean (you might have to prefix with 0x however)
> 
> check is, now it should be ok.

@vladyslav-iosdev nearly but if the 0x prefix is added it goes to seed, correct that and it should be fine :)

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev nearly but if the 0x prefix is added it goes to seed, correct that and it should be fine :)

can u please check `trimmedValue` in `ScanQRCodeResolution`, and send it to me, because i checked cases with adding 0x and without it. and it worked for me.

**Comment by hboon** [comment]
@vladyslav-iosdev this good for review? (can you rebase first?)

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev this good for review? (can you rebase first?)

yes

**Comment by hboon** [comment]
@James-Sangalli bump

**Review by James-Sangalli — APPROVED** [review]

**Pull request merged**
