### PR TITLE
Activity

### PR DESCRIPTION
**Pull request by hboon**
Looks like time to merge this in so @vladyslav-iosdev can work on his parts like #2056

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon i need to `merge` activity into `train-leaves`, and then rebase train-leaves to branche i working on, right?

**Comment by hboon** [comment]
Answered offline.

**Comment by James-Sangalli** [comment]
@hboon merged with the understanding that speed optimisation will be another PR

**Comment by hboon** [comment]
@James-Sangalli ok!

**Pull request merged**
