### PR TITLE
Make typing "swap" in Wallet tab search bar filter for tokens that support swapping #2332

### LINKED ISSUE #2332: Make typing "swap" in Wallet tab search bar filter for tokens that support swapping
i.e. change "uniswap" here to "swap" and make it work for tokens that show the "swap" button:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/0041387a9fd76290dc8388bd1c943c804f6077f2/AlphaWallet/Core/Coordinators/FilterTokensCoordinator.swift#L45

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2332

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Seems to work, but filtering is very slow when the keyword "swap" matches.

**Comment by hboon** [comment]
Creation of `AlphaWallet.Address` is generally very slow, maybe that could be the reason?

**Comment by vladyslav-iosdev** [comment]
> Creation of `AlphaWallet.Address` is generally very slow, maybe that could be the reason?

@hboon  i found that it takes too much time, because we perform search in array, replacing `available Tokens` with dictionary helps to resolve the issue.

**Comment by hboon** [comment]
Thanks!

I changed this line from:

```
        .init(symbol: "ETH", name: "ETH", address: Constants.nativeCryptoAddressInDatabase, decimal: 18)
```

to:

```
        .init(symbol: "ETH", name: "ETH", address: Constants.nativeCryptoAddressInDatabase, decimal: RPCServer.main.decimals)
```

and forced pushed

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
@vladyslav-iosdev looks like tests are not building. Can you help to fix them and merge?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev looks like tests are not building. Can you help to fix them and merge?

@hboon now should be ok.

**Comment by hboon** [comment]
@vladyslav-iosdev go ahead and merge it if the tests are good

**Comment by hboon** [comment]
Never mind. Merged :)

**Pull request merged**
