### PR TITLE
Add Support For Candle

### PR DESCRIPTION
**Pull request by samisbakedham**
1-liner summary: Adds support for another chain, Candle. 

Details if any (this should probably be in the commit message too):
Candle is an EVM-compatible chain/network similar to Polygon. This PR simply adds support for it on Alpha Wallet.

### CODE REVIEW

**Comment by oa-s** [comment]
Hi [samisbakedham](https://github.com/samisbakedham), it looks like you made PR to wrong repo, please check it out and recreate for a right repo. Close this pr.

**Comment by samisbakedham** [comment]
> Hi [samisbakedham](https://github.com/samisbakedham), it looks like you made PR to wrong repo, please check it out and recreate for a right repo. Close this pr.

How so?

**Comment by oa-s** [comment]
your PR contains bundle id changes as well as some default AW icons, i suppose you working on your own fork, and made pr to main repo instead for your own project.

**Comment by samisbakedham** [comment]
Did this merge add candle to alpha Wallet?

**Comment by hboon** [comment]
@samisbakedham no it did not. Do you think you can create a new PR for this?

**Comment by samisbakedham** [comment]
> @samisbakedham no it did not. Do you think you can create a new PR for this?

Of course! Doing now

**Pull request merged**
