### PR TITLE
Removed UITest files and connected CMD-U to start unit tests

### LINKED ISSUE #3470: Empty UI tests should be removed
The Empty UI tests are failing and prevents testers from running unit tests via CMD-T. These Empty UI tests should be removed.

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #3470 

# Testing and Running
The UI Test files have been removed and references to it have been removed from Podfile. The Podfile.lock is also changed due to this removal. CMD-U has also been hooked back to run unit tests.

We need to run the app and perform unit tests to confirm the code base is still functional.

## Running
Press CMD-R to run the app.

### Expects
To see the app running.

## Testing
Press CMD-U to run the unit tests.

### Expects
To the the unit tests running.

## Side notes
There is an option to turn on random testing. When activated, Xcode will select Test Suites randomly and execute the Suites' tests randomly until all Test Suites are executed. `AppCoordinatorTests` does not pass when run in this random manner.

### CODE REVIEW

**Comment by eviltofu** [comment]
Closes #3470

**Comment by hboon** [comment]
(edited to move the closes issue keyword to the first comment. Easier to locate)

**Review by hboon — CHANGES_REQUESTED** [review]
Thanks!

> There is an option to turn on random testing. When activated, Xcode will select Test Suites randomly and execute the Suites' tests randomly until all Test Suites are executed. AppCoordinatorTests does not pass when run in this random manner.

Strangely, `AppCoordinatorTests` passes for me, but some other tests don't. Maybe just random. Nevermind

- [ ] If you go to Product > Scheme > Manage Schemes, is "AlphaWalletUITests" still there? If so, shall we remove it too?

**Comment by hboon** [comment]
For posterity. and @vladyslav-iosdev:

Screenshot 2021-11-25 at 10 32 47 AM

**Comment by eviltofu** [comment]
@hboon pending check and merge

**Review by hboon — APPROVED** [review]

**Pull request merged**
