### PR TITLE
add cndl

### PR DESCRIPTION
**Pull request by samisbakedham**
Closes #4991 

1-liner summary: Adds support for Candle

Details if any (this should probably be in the commit message too):

Screenshots of Before PR and After PR if it's applicable (sometimes this make it much faster/easier to review):

Anything particular to test:

### CODE REVIEW

**Comment by samisbakedham** [comment]
@hboon

**Comment by jsun1** [comment]
alphawallet-candle

**Comment by hboon** [comment]
BTW, the icon on the top left of https://candleexplorer.com doesn't appear (both Safari and Chrome)
 
Screenshot 2022-09-06 at 10 28 31 AM

**Comment by samisbakedham** [comment]
> add cndl #4991

We're aware of this, Blockscout is hosting the explorer themselves most likely starting this week. Thank you for bringing it up though, we'll ask our team what their plans are to address this or wait for the transition to blockscout-hosting.

**Comment by samisbakedham** [comment]
merge before branch gets outdated @hboon

**Comment by hboon** [comment]
@samisbakedham looking at it at the moment

**Comment by hboon** [comment]
Also:

Also the base URLs displayed in 

* https://candleexplorer.com/api-docs
* https://candleexplorer.com/eth-rpc-api-docs

Should be updated (not `localhost:4000/`)

**Comment by hboon** [comment]
@samisbakedham can you help verify if the blockchain explorer API should be at https://candleexplorer.com/api instead of https://api.candlelabs.org/ (or https://api.candlelabs.org/api )?

Because:

```
curl "https://candleexplorer.com/api?module=account&action=tokentx&address=0xb59A29Fb24c76476f690B2d546c4a39fDd5D8d7a"

<something that looks valid>
```

but:

```
curl "https://api.candlelabs.org/api?module=account&action=tokentx&address=0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63"

<error>
```

and

```
curl "https://api.candlelabs.org?module=account&action=tokentx&address=0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63"

<error>
```

**Comment by hboon** [comment]
If that's correct, would you grant me write permission to the fork repo or fix this on your end and force push?

Replace this line:


```
            case .candle: return "https://api.candlelabs.org/"
```

with:

```
            case .candle: return "https://candleexplorer.com/api"
```

**Comment by jsun1** [comment]
Thanks for catching this - adding a commit to use `https://candleexplorer.com/api` instead.

**Comment by hboon** [comment]
@jsun1 thanks!

**Comment by hboon** [comment]
And thanks for squashing :)

**Review by hboon — APPROVED** [review]

**Pull request merged**
