### PR TITLE
Add Support for PHI v2 Smart Chain 

### PR DESCRIPTION
**Pull request by Phinetwork**
Added Support for PHI Smart Chain v2 Chain ID 144

https://chainlist.org/chain/144

### CODE REVIEW

**Comment by Phinetwork** [comment]
Need Some Help with editing documents. We dont need to edit every document care use same logo & such just add an additional chain with V2 & the original chain to V1 so users can tell the difference between the two chains. Thank you for your help.

**Comment by Phinetwork** [comment]
https://phiscan.com

chain ID: 144

https://connect.phi.network

**Comment by Phinetwork** [comment]
@hboon can we have support in adding PHI smart chain v2 chain id 144 https://chainlist.org/chain/144 thanks

**Comment by hboon** [comment]
@Phinetwork sure. Just to be sure, what's the difference/relationship between v1 and v2?

**Comment by Phinetwork** [comment]
> @Phinetwork sure. Just to be sure, what's the difference/relationship between v1 and v2?

V2 is an additional chain upgrade to the v1 smart chain that will be released to the community on 5/4/21 

it will be used for governance & high performant onchain gaming & NFTs. the v1 chain is more finance & focused on allowing users to transact in a more private manner. V2 chain is geared towards developers & has much better api documentation. 


Chain id:4181 is v1 
Explorer.phi.network 

Chain id:144
Phiscan.com

**Comment by hboon** [comment]
OK. Will look into it. I don't quite remember, but if I don't have access to https://github.com/Phinetwork/alpha-wallet-ios/, would you help grant me write access? I'll push to it once I have made changes.

**Comment by Phinetwork** [comment]
> https://github.com/Phinetwork/alpha-wallet-ios/

yes you have direct write access Thanks

**Comment by Phinetwork** [comment]
> OK. Will look into it. I don't quite remember, but if I don't have access to https://github.com/Phinetwork/alpha-wallet-ios/, would you help grant me write access? I'll push to it once I have made changes.

How's it going?

**Comment by hboon** [comment]
@Phinetwork not yet. Had to work on something else first.

**Comment by Phinetwork** [comment]
> @Phinetwork not yet. Had to work on something else first.

Ok awesome thanks for update. The community is Excited for the integration & phi will be scaling lots of new users over the coming months.

**Comment by Phinetwork** [comment]
How's it going on the v2 chain integration?  @hboon also please make sure the gas fees correct on not defaulting as 1 gwei

**Comment by Phinetwork** [comment]
How's this going

**Comment by hboon** [comment]
On it, working on some related refactoring first #5429

**Comment by Phinetwork** [comment]
> On it, working on some related refactoring first #5429

Perfect

**Comment by hboon** [comment]
Superseded by #5435

**Pull request closed without merging**
