### PR TITLE
Add "Show Seed Phrase" to Settings tab #2582

### LINKED ISSUE #2582: Add "Show Seed Phrase" to Settings tab
**Problem:**
Some users find it difficult to access their Seed Phrase. They have to go through "Back up my Wallet" flow, where we tried to warn users about not sharing seed phrases. 

**Solution:**
- [x] We add one more item to the Settings Menu. We keep "Back up my Wallet". If you open "Back up my Wallet" it goes exactly as it is now, but please remove the addition line in red "Do not share your backup. AlphaWallet team..." 

- [x] If you select "Show Seed Phrase" you will get into a flow like this:
Screenshot 2021-03-02 at 10 26 59

Zeplin:
https://zpl.io/a85xMnx

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2582

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Looks good. Just 1 change. Can you hide the new item "Show Seed Phrase" if it's a not based on a seed phrase? Maybe here: https://github.com/AlphaWallet/alpha-wallet-ios/blob/25b75e6364c8a300dac62ac1771505cceccac2c4/AlphaWallet/Settings/ViewModels/SettingsViewModel.swift#L34 ?

**Comment by hboon** [comment]
Remember to buzz me again if it's ready

**Comment by vladyslav-iosdev** [comment]
@hboon this one is done

**Comment by hboon** [comment]
Force pushed after rebase master

**Review by hboon — APPROVED** [review]

**Pull request merged**
