### PR TITLE
After switching from mainnet to testnet, list of wallets screen shows fiat balance for every wallet except current wallet #5786

### LINKED ISSUE #5786: After switching from mainnet to testnet, list of wallets screen shows fiat balance for every wallet except current wallet
Row for 0xbbc is not shown in the screenshot:

1. Switch to mainnet
2. Go to wallets screen
3. Observe $ show up for every wallet, even if "0.00 USD"
4. Switch to testnet
5. Go to wallets screen

Expected

6. Observe $ show up for every wallet, even if "0.00 USD"

Observed

6. Observe $ show up for every wallet, even if "0.00 USD", except the current wallet which shows "--"

If we then switch to another wallet and go to the list of wallets screen again, that wallet's fiat balance would be "--" too

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5786

### CODE REVIEW

**Comment by oa-s** [comment]
Touches pipeline, more testing is needed

**Comment by hboon** [comment]
Better to prefix with "Fix: "

**Comment by hboon** [comment]
It crashed when I switch wallets during testmode. I *think* like this:

1. Launch in mainnet
2. List of wallets
3. Choose same wallet
4. Switch to testnet
5. Choose different wallet

```
2022-11-16 11:34:38.754167+0800 AlphaWallet[65597:56485587] *** Assertion failure in void BUG_IN_CLIENT_OF_DIFFABLE_DATA_SOURCE__EQUAL_IDENTIFIERS_HAVE_DIFFERENT_HASH_VALUES(__strong id, __strong id, BOOL)(), _UIDiffableDataSourceHelpers.m:596
2022-11-16 11:34:39.217247+0800 AlphaWallet[65597:56485587] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Diffable data source detected item identifiers that are equal but have different hash values. Two identifiers which compare as equal must return the same hash value. You must fix this in the Hashable (Swift) or hash property (Objective-C) implementation for the type of these identifiers. Identifiers that are equal but have different hash values: (AlphaWallet.AccountsViewModel.ViewModelType.wallet(AlphaWallet.AccountViewModel(displayBalanceApprecation: false, current: Optional(.real(0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362)), accountRowViewModel: AlphaWallet.AccountsViewModel.AccountRowViewModel(wallet: .real(0x2390A3fF884439d97B0f2293267F019dCdb8C54C), blockie: AlphaWalletFoundation.BlockiesImage.image(image: <UIImage:0x600002b3e640 anonymous {64, 64} renderingMode=automatic(original)>, isEnsAvatar: false), addressOrEnsName: "0x2390A3fF884439d97B0f2293267F019dCdb8C54C", balance: AlphaWalletFoundation.WalletBalance(tokens: [AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x0000000000000000000000000000000000000000, symbol: "ETH", decimals: 18, server: AlphaWalletFoundation.RPCServer.goerli, type: AlphaWalletFoundation.TokenType.nativeCryptocurrency, name: "Goerli", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(currencyAmount: nil, amountFull: "0", amountShort: "0", symbol: "ETH", amount: 0.0, currencyAmountWithoutSymbol: nil, value: 0, balance: [], ticker: nil), tokenScriptOverrides: Optional(AlphaWalletFoundation.TokenScriptOverrides(title: "Goerli (ETH)", titleInPluralForm: "Goerli (ETH)", shortTitleInPluralForm: "ETH", symbolInPluralForm: "ETH", hasNoBaseAssetDefinition: false, server: nil, xmlHandler: AlphaWalletFoundation.XMLHandler))), AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x42A20a31e2f6158265898D27bD0AF5cF0805F387, symbol: "MSG", decimals: 0, server: AlphaWalletFoundation.RPCServer.goerli, type: AlphaWalletFoundation.TokenType.erc721, name: "Message Token", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(currencyAmount: nil, amountFull: "1", amountShort: "1", symbol: "MSG", amount: 1.0, currencyAmountWithoutSymbol: nil, value: 0, balance: [AlphaWalletFoundation.TokenBalanceValue(json: "{}", balance: "{\n  \"externalLink\" : \"https:\\/\\/github.com\\/TokenScript\",\n  \"contractName\" : \"Message Token\",\n  \"image_url\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\",\n  \"external_url\" : \"https:\\/\\/github.com\\/TokenScript\",\n  \"symbol\" : \"MSG\",\n  \"tokenType\" : \"ERC721\",\n  \"name\" : \"TokenScript Message Token\",\n  \"attributes\" : [\n    {\n      \"key\" : \"Token Type\",\n      \"value\" : \"Smart Token\",\n      \"trait_type\" : \"Token Type\"\n    },\n    {\n      \"key\" : \"Power\",\n      \"value\" : \"Over 9000\",\n      \"trait_type\" : \"Power\"\n    },\n    {\n      \"key\" : \"Year\",\n      \"value\" : \"2022\",\n      \"trait_type\" : \"Year\"\n    },\n    {\n      \"key\" : \"TokenScript\",\n      \"value\" : \"2nd Gen\",\n      \"trait_type\" : \"TokenScript\"\n    }\n  ],\n  \"description\" : \"This NFT is powered by ERC5169, which adds a utility script \'TokenScript\' to make the token smart. The script will be downloaded automatically from the contract scriptURI() endpoint. The script can be updated by the owner by calling updateScriptURI(string newURI). This token can be updated by calling setTokenURI(string new URI).\",\n  \"decimals\" : 0,\n  \"tokenId\" : \"1\",\n  \"thumbnailUrl\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\",\n  \"imageUrl\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\"\n}", nonFungibleBalance: Optional(AlphaWalletFoundation.NonFungibleFromTokenUri(tokenId: "1", tokenType: AlphaWalletOpenSea.NonFungibleFromJsonTokenType.erc721, value: 1, contractName: "Message Token", decimals: 0, symbol: "MSG", name: "TokenScript Message Token", thumbnailUrl: "ipfs://QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT", imageUrl: "ipfs://QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT", externalLink: "https://github.com/TokenScript", collectionCreatedDate: nil, collectionDescription: nil, meltStringValue: nil, meltFeeRatio: nil, meltFeeMaxRatio: nil, totalSupplyStringValue: nil, circulatingSupplyStringValue: nil, reserveStringValue: nil, nonFungible: nil, blockHeight: nil, mintableSupply: nil, transferable: nil, supplyModel: nil, issuer: nil, created: nil, transferFee: nil)))], ticker: nil), tokenScriptOverrides: Optional(AlphaWalletFoundation.TokenScriptOverrides(title: "August Lock Token (MSG)", titleInPluralForm: "August Lock Tokens (MSG)", shortTitleInPluralForm: "August Lock Tokens", symbolInPluralForm: "MSG", hasNoBaseAssetDefinition: true, server: Optional(AlphaWalletFoundation.RPCServerOrAny.any), xmlHandler: AlphaWalletFoundation.XMLHandler)))], wallet: .real(0x2390A3fF884439d97B0f2293267F019dCdb8C54C), totalAmountDouble: nil, changeDouble: nil)), backgroundColor: <UIDynamicProviderColor: 0x6000019529e0; provider = <__NSMallocBlock__: 0x6000016cf390>>))) and (AlphaWallet.AccountsViewModel.ViewModelType.wallet(AlphaWallet.AccountViewModel(displayBalanceApprecation: false, current: Optional(.real(0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362)), accountRowViewModel: AlphaWallet.AccountsViewModel.AccountRowViewModel(wallet: .real(0x2390A3fF884439d97B0f2293267F019dCdb8C54C), blockie: AlphaWalletFoundation.BlockiesImage.image(image: <UIImage:0x600002b3e640 anonymous {64, 64} renderingMode=automatic(original)>, isEnsAvatar: false), addressOrEnsName: "0x2390A3fF884439d97B0f2293267F019dCdb8C54C", balance: AlphaWalletFoundation.WalletBalance(tokens: [AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x0000000000000000000000000000000000000000, symbol: "ETH", decimals: 18, server: AlphaWalletFoundation.RPCServer.goerli, type: AlphaWalletFoundation.TokenType.nativeCryptocurrency, name: "Goerli", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(currencyAmount: nil, amountFull: "0", amountShort: "0", symbol: "ETH", amount: 0.0, currencyAmountWithoutSymbol: nil, value: 0, balance: [], ticker: nil), tokenScriptOverrides: Optional(AlphaWalletFoundation.TokenScriptOverrides(title: "Goerli (ETH)", titleInPluralForm: "Goerli (ETH)", shortTitleInPluralForm: "ETH", symbolInPluralForm: "ETH", hasNoBaseAssetDefinition: false, server: nil, xmlHandler: AlphaWalletFoundation.XMLHandler))), AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x42A20a31e2f6158265898D27bD0AF5cF0805F387, symbol: "MSG", decimals: 0, server: AlphaWalletFoundation.RPCServer.goerli, type: AlphaWalletFoundation.TokenType.erc721, name: "Message Token", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(currencyAmount: nil, amountFull: "1", amountShort: "1", symbol: "MSG", amount: 1.0, currencyAmountWithoutSymbol: nil, value: 0, balance: [AlphaWalletFoundation.TokenBalanceValue(json: "{}", balance: "{\n  \"externalLink\" : \"https:\\/\\/github.com\\/TokenScript\",\n  \"contractName\" : \"Message Token\",\n  \"image_url\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\",\n  \"external_url\" : \"https:\\/\\/github.com\\/TokenScript\",\n  \"symbol\" : \"MSG\",\n  \"tokenType\" : \"ERC721\",\n  \"name\" : \"TokenScript Message Token\",\n  \"attributes\" : [\n    {\n      \"key\" : \"Token Type\",\n      \"value\" : \"Smart Token\",\n      \"trait_type\" : \"Token Type\"\n    },\n    {\n      \"key\" : \"Power\",\n      \"value\" : \"Over 9000\",\n      \"trait_type\" : \"Power\"\n    },\n    {\n      \"key\" : \"Year\",\n      \"value\" : \"2022\",\n      \"trait_type\" : \"Year\"\n    },\n    {\n      \"key\" : \"TokenScript\",\n      \"value\" : \"2nd Gen\",\n      \"trait_type\" : \"TokenScript\"\n    }\n  ],\n  \"description\" : \"This NFT is powered by ERC5169, which adds a utility script \'TokenScript\' to make the token smart. The script will be downloaded automatically from the contract scriptURI() endpoint. The script can be updated by the owner by calling updateScriptURI(string newURI). This token can be updated by calling setTokenURI(string new URI).\",\n  \"decimals\" : 0,\n  \"tokenId\" : \"1\",\n  \"thumbnailUrl\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\",\n  \"imageUrl\" : \"ipfs:\\/\\/QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT\"\n}", nonFungibleBalance: Optional(AlphaWalletFoundation.NonFungibleFromTokenUri(tokenId: "1", tokenType: AlphaWalletOpenSea.NonFungibleFromJsonTokenType.erc721, value: 1, contractName: "Message Token", decimals: 0, symbol: "MSG", name: "TokenScript Message Token", thumbnailUrl: "ipfs://QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT", imageUrl: "ipfs://QmRFWn23HowsWFc11BUfBo5FBrBLis67TqN8JnXLXazDAT", externalLink: "https://github.com/TokenScript", collectionCreatedDate: nil, collectionDescription: nil, meltStringValue: nil, meltFeeRatio: nil, meltFeeMaxRatio: nil, totalSupplyStringValue: nil, circulatingSupplyStringValue: nil, reserveStringValue: nil, nonFungible: nil, blockHeight: nil, mintableSupply: nil, transferable: nil, supplyModel: nil, issuer: nil, created: nil, transferFee: nil)))], ticker: nil), tokenScriptOverrides: Optional(AlphaWalletFoundation.TokenScriptOverrides(title: "August Lock Token (MSG)", titleInPluralForm: "August Lock Tokens (MSG)", shortTitleInPluralForm: "August Lock Tokens", symbolInPluralForm: "MSG", hasNoBaseAssetDefinition: true, server: Optional(AlphaWalletFoundation.RPCServerOrAny.any), xmlHandler: AlphaWalletFoundation.XMLHandler))), AlphaWalletFoundation.TokenViewModel(contractAddress: ethereumAddress: 0x499d11E0b6eAC7c0593d8Fb292DCBbF815Fb29Ae, symbol: "Testv4", decimals: 18, server: AlphaWalletFoundation.RPCServer.goerli, type: AlphaWalletFoundation.TokenType.erc20, name: "Testv4", shouldDisplay: true, balance: AlphaWalletFoundation.BalanceViewModel(currencyAmount: nil, amountFull: "1", amountShort: "1", symbol: "Testv4", amount: 1.0, currencyAmountWithoutSymbol: nil, value: 1000000000000000000, balance: [], ticker: nil), tokenScriptOverrides: Optional(AlphaWalletFoundation.TokenScriptOverrides(title: "Testv4 (Testv4)", titleInPluralForm: "Testv4 (Testv4)", shortTitleInPluralForm: "Testv4", symbolInPluralForm: "Testv4", hasNoBaseAssetDefinition: false, server: Optional(AlphaWalletFoundation.RPCServerOrAny.any), xmlHandler: AlphaWalletFoundation.XMLHandler)))], wallet: .real(0x2390A3fF884439d97B0f2293267F019dCdb8C54C), totalAmountDouble: nil, changeDouble: nil)), backgroundColor: <UIDynamicProviderColor: 0x6000019529e0; provider = <__NSMallocBlock__: 0x6000016cf390>>)))'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109ea0304 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00000001041b931c objc_exception_throw + 56
	2   Foundation                          0x000000010ad250bc -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
	3   UIKitCore                           0x000000012359a0f4 BUG_IN_CLIENT_OF_DIFFABLE_DATA_SOURCE__EQUAL_IDENTIFIERS_HAVE_DIFFERENT_HASH_VALUES + 212
	4   UIKitCore                           0x000000012359a98c _UIDiffableDataSourceValidateIdentifiersForDiff + 324
	5   UIKitCore                           0x0000000122960fac -[_UIDiffableDataSourceDiffer _computeUpdatesForIdentifierBasedDiff] + 888
	6   UIKitCore                           0x0000000122960c1c -[_UIDiffableDataSourceDiffer _computeUpdates] + 20
	7   UIKitCore                           0x00000001229606f8 -[_UIDiffableDataSourceDiffer initWithBeforeDataSource:afterDataSource:itemIdentifierDiffer:] + 148
	8   UIKitCore                           0x0000000122960b78 +[_UIDiffableDataSourceDiffer differWithBeforeDataSourceState:afterDataSourceState:] + 64
	9   UIKitCore                           0x000000012295cb0c __122-[__UIDiffableDataSource _applyDifferencesFromSnapshot:viewPropertyAnimator:customAnimationsProvider:animated:completion:]_block_invoke + 104
	10  UIKitCore                           0x000000012295cedc __122-[__UIDiffableDataSource _applyDifferencesFromSnapshot:viewPropertyAnimator:customAnimationsProvider:animated:completion:]_block_invoke_7 + 80
	11  libdispatch.dylib                   0x0000000109c63768 _dispatch_client_callout + 16
	12  libdispatch.dylib                   0x0000000109c73f04 _dispatch_lane_barrier_sync_invoke_and_complete + 92
	13  UIKitCore                           0x000000012295c8cc -[__UIDiffableDataSource _applyDifferencesFromSnapshot:viewPropertyAnimator:customAnimationsProvider:animated:completion:] + 832
	14  UIKitCore                           0x000000012295bff0 -[__UIDiffableDataSource applyDifferencesFromSnapshot:animatingDifferences:completion:] + 92
	15  libswiftUIKit.dylib                 0x00000001099d3474 $s5UIKit34UICollectionViewDiffableDataSourceC5apply_20animatingDifferences10completionyAA010NSDiffableeF8SnapshotVyxq_G_SbyycSgtFTm + 232
	16  AlphaWallet                         0x00000001004e56a0 $s11AlphaWallet22AccountsViewControllerC4bind33_6A412BA72F1DD83610722897022070DCLL9viewModelyAA0cdM0C_tFyAH0D5StateVcfU_ + 276
	17  Combine                             0x0000000103d79858 $s7Combine11SubscribersO4SinkC7receiveyAC6DemandVxF + 88
	18  Combine                             0x0000000103d79e78 $s7Combine11SubscribersO4SinkCy_xq_GAA10SubscriberA2aGP7receiveyAC6DemandV5InputQzFTW + 20
	19  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	20  Combine                             0x0000000103e01d34 $s7Combine10PublishersO12HandleEventsV5Inner33_9464E9048FC4C9C669F954B681B5AD45LLC7receiveyAA11SubscribersO6DemandV6OutputQzF + 136
	21  Combine                             0x0000000103e01f1c $s7Combine10PublishersO12HandleEventsV5Inner33_9464E9048FC4C9C669F954B681B5AD45LLCy_x_qd__GAA10SubscriberA2aJP7receiveyAA11SubscribersO6DemandV5InputQzFTW + 20
	22  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	23  Combine                             0x0000000103d8aa6c $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC7receive_5indexAA11SubscribersO6DemandVyp_SitF + 596
	24  Combine                             0x0000000103d8a1f4 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC4SideV7receiveyAA11SubscribersO6DemandVqd__F + 80
	25  Combine                             0x0000000103dea6d8 $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLC12receiveInneryAA11SubscribersO6DemandV6OutputQz_SitF + 220
	26  Combine                             0x0000000103dea5f0 $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLC4SideV7receiveyAA11SubscribersO6DemandV6OutputQzF + 20
	27  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	28  Combine                             0x0000000103d8aa6c $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC7receive_5indexAA11SubscribersO6DemandVyp_SitF + 596
	29  Combine                             0x0000000103d8a1f4 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC4SideV7receiveyAA11SubscribersO6DemandVqd__F + 80
	30  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	31  Combine                             0x0000000103d6bcbc $s7Combine14FilterProducerC7receiveyAA11SubscribersO6DemandVq_F + 1620
	32  Combine                             0x0000000103d6c610 $s7Combine14FilterProducerCyxq_q0_q1_q2_GAA10SubscriberA2aEP7receiveyAA11SubscribersO6DemandV5InputQzFTW + 20
	33  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	34  Combine                             0x0000000103d8aa6c $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC7receive_5indexAA11SubscribersO6DemandVyp_SitF + 596
	35  Combine                             0x0000000103d8a1f4 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC4SideV7receiveyAA11SubscribersO6DemandVqd__F + 80
	36  Combine                             0x0000000103e044c0 $s7Combine10PublishersO11ConcatenateV5InnerC13prefixReceiveyAA11SubscribersO6DemandV6OutputQzF + 232
	37  Combine                             0x0000000103e043cc $s7Combine10PublishersO11ConcatenateV5InnerC16PrefixSubscriberV7receiveyAA11SubscribersO6DemandV6OutputQzF + 20
	38  Combine                             0x0000000103e16bf4 $s7Combine10PublishersO8SequenceV5Inner33_8116E0FA2B2A13BBC974430F9C6D956ELLC7requestyyAA11SubscribersO6DemandVF + 1476
	39  Combine                             0x0000000103e17008 $s7Combine10PublishersO8SequenceV5Inner33_8116E0FA2B2A13BBC974430F9C6D956ELLCy_xq__qd__qd_0_qd_1_GAA12SubscriptionA2aJP7requestyyAA11SubscribersO6DemandVFTW + 20
	40  Combine                             0x0000000103e050b8 $s7Combine10PublishersO11ConcatenateV5InnerC7requestyyAA11SubscribersO6DemandVF + 296
	41  Combine                             0x0000000103e056f0 $s7Combine10PublishersO11ConcatenateV5InnerCy_xq__qd__GAA12SubscriptionA2aIP7requestyyAA11SubscribersO6DemandVFTW + 20
	42  Combine                             0x0000000103d8b8e4 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC7requestyyAA11SubscribersO6DemandVF + 312
	43  Combine                             0x0000000103d8bca0 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLCyxq_q0_GAA12SubscriptionA2aFP7requestyyAA11SubscribersO6DemandVFTW + 20
	44  Combine                             0x0000000103d6b41c $s7Combine14FilterProducerC7requestyyAA11SubscribersO6DemandVF + 244
	45  Combine                             0x0000000103d6c650 $s7Combine14FilterProducerCyxq_q0_q1_q2_GAA12SubscriptionA2aEP7requestyyAA11SubscribersO6DemandVFTW + 20
	46  Combine                             0x0000000103d8b8e4 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC7requestyyAA11SubscribersO6DemandVF + 312
	47  Combine                             0x0000000103d8bca0 $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLCyxq_q0_GAA12SubscriptionA2aFP7requestyyAA11SubscribersO6DemandVFTW + 20
	48  Combine                             0x0000000103dea5d4 $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLC12receiveInner12subscription_yAA12Subscription_p_SitF + 364
	49  Combine                             0x0000000103dea45c $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLC4SideV7receive12subscriptionyAA12Subscription_p_tF + 20
	50  Combine                             0x0000000103d8bacc $s7Combine08AbstractA6Latest33_CA620F28370EDE9EC7213099A507EBCELLC9subscribeyyF + 320
	51  Combine                             0x0000000103d89120 $s7Combine10PublishersO0A7Latest3V7receive10subscriberyqd___tAA10SubscriberRd__7FailureQyd__AIRt0_6OutputQz_ALQy_ALQy0_t5InputRtd__lF + 732
	52  Combine                             0x0000000103e0c7ac $s7Combine10PublishersO3MapV7receive10subscriberyqd___t5InputQyd__Rs_AA10SubscriberRd__7FailureQyd__AKRtzlF + 320
	53  Combine                             0x0000000103e0c060 $s7Combine12PublisherBoxC7receive10subscriberyqd___tAA10SubscriberRd__7FailureQyd__AGRtz5InputQyd__6OutputRtzlF + 36
	54  Combine                             0x0000000103e0c2b0 $s7Combine12AnyPublisherV7receive10subscriberyqd___t5InputQyd__Rsz7FailureQyd__Rs_AA10SubscriberRd__lF + 36
	55  Combine                             0x0000000103deb1c8 $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLC7receiveyAA11SubscribersO6DemandVxF + 512
	56  Combine                             0x0000000103deb994 $s7Combine10PublishersO14SwitchToLatestV5Outer33_632F562448277D2437131227129423E9LLCy_xq__qd__GAA10SubscriberA2aJP7receiveyAA11SubscribersO6DemandV5InputQzFTW + 20
	57  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	58  Combine                             0x0000000103e0ca8c $s7Combine10PublishersO3MapV5Inner33_5A6CD15A64659A6248DAF677D4BB6188LLV7receiveyAA11SubscribersO6DemandV6OutputQzF + 104
	59  Combine                             0x0000000103ddb340 $s7Combine10PublishersO7_Merged33_3ECDDD5E136557E37A635C683348124DLLC7receiveyAA11SubscribersO6DemandVx_SitFAKq0_XEfU0_TA + 40
	60  Combine                             0x0000000103dcf638 $s7Combine10PublishersO7_Merged33_3ECDDD5E136557E37A635C683348124DLLC22guardedApplyDownstreamyqd__qd__q0_XElF + 120
	61  Combine                             0x0000000103dcfdc4 $s7Combine10PublishersO7_Merged33_3ECDDD5E136557E37A635C683348124DLLC7receiveyAA11SubscribersO6DemandVx_SitF + 204
	62  Combine                             0x0000000103dcfcec $s7Combine10PublishersO7_Merged33_3ECDDD5E136557E37A635C683348124DLLC4SideV7receiveyAA11SubscribersO6DemandVxF + 20
	63  Combine                             0x0000000103d85048 $s7Combine18PassthroughSubjectC7ConduitC5offeryyxF + 396
	64  Combine                             0x0000000103d86170 $s7Combine18PassthroughSubjectC4sendyyxFyAA11ConduitBaseCyxq_GXEfU_TA + 40
	65  Combine                             0x0000000103dbc0b4 $s7Combine11ConduitListO7forEachyyyAA0B4BaseCyxq_GKXEKF + 212
	66  Combine                             0x0000000103d84af0 $s7Combine18PassthroughSubjectC4sendyyxF + 168
	67  AlphaWallet                         0x00000001004e5ebc $s11AlphaWallet22AccountsViewControllerC14viewWillAppearyySbF + 144
	68  AlphaWallet                         0x00000001004e5f0c $s11AlphaWallet22AccountsViewControllerC14viewWillAppearyySbFTo + 56
	69  UIKitCore                           0x0000000122b0d728 -[UIViewController _setViewAppearState:isAnimating:] + 608
	70  UIKitCore                           0x0000000122b0df5c -[UIViewController __viewWillAppear:] + 112
	71  UIKitCore                           0x0000000122a61cd0 -[UINavigationController _startCustomTransition:] + 1048
	72  UIKitCore                           0x0000000122a73050 -[UINavigationController _startDeferredTransitionIfNeeded:] + 492
	73  UIKitCore                           0x0000000122a73f20 -[UINavigationController __viewWillLayoutSubviews] + 92
	74  UIKitCore                           0x0000000122a5b914 -[UILayoutContainerView layoutSubviews] + 168
	75  UIKitCore                           0x000000012361e14c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1920
	76  QuartzCore                          0x00000001082ce49c _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
	77  QuartzCore                          0x00000001082d8f54 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 128
	78  QuartzCore                          0x00000001082087d0 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 452
	79  QuartzCore                          0x000000010823447c _ZN2CA11Transaction6commitEv + 652
	80  QuartzCore                          0x00000001082358b0 _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
	81  CoreFoundation                      0x0000000109e040e4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
	82  CoreFoundation                      0x0000000109dfea84 __CFRunLoopDoObservers + 512
	83  CoreFoundation                      0x0000000109dfef3c __CFRunLoopRun + 968
	84  CoreFoundation                      0x0000000109dfe75c CFRunLoopRunSpecific + 584
	85  GraphicsServices                    0x0000000117983c98 GSEventRunModal + 160
	86  UIKitCore                           0x0000000123188b74 -[UIApplication _run] + 868
	87  UIKitCore                           0x000000012318cb1c UIApplicationMain + 124
	88  AlphaWallet                         0x000000010042d2bc main + 64
	89  dyld                                0x0000000102b7dfa0 start_sim + 20
	90  ???                                 0x0000000102cdd08c 0x0 + 4342009996
	91  ???                                 0xa224000000000000 0x0 + 11683463333305909248
)
libc++abi: terminating with uncaught exception of type NSException
```

**Review by hboon — APPROVED** [review]

**Comment by oa-s** [comment]
checking crash, latest commit looks ok

**Comment by hboon** [comment]
I can't reproduce the crash too. So, good to merge if it's ready. I'll be making a release soon on top of the previous release (v3.57-465), so we still have time to test `master`

**Pull request merged**
