### PR TITLE
Adding support for Candle as a network

### PR DESCRIPTION
**Pull request by jsun1**
1-liner summary:

Proposes to add support for Candle (CNDL) as a network:

alphawallet-candle

Anything particular to test:

I've tested enabling Candle, and sending/receiving CNDL from Metamask.

### CODE REVIEW

**Comment by samisbakedham** [comment]
@hboon closes #4991 !

**Comment by hboon** [comment]
@samisbakedham does this PR supersede #4991? If so, you can force push to the same repo+branch and it will update it instead of creating a new PR.

Also, would you help `git rebase master` after fetching the latest master. As usually we wouldn't want merge commits in the PR; usually they will have the commit message "Merge branch 'AlphaWallet:master'", and is the result of running `git pull origin/upstream master" (never do that)

**Comment by jsun1** [comment]
Thanks yes, this supersedes 4991 - I'll follow your advice and look into force-pushing to 4991 then (and rebasing to squash the commits there)

**Comment by samisbakedham** [comment]
> @samisbakedham does this PR supersede #4991? If so, you can force push to the same repo+branch and it will update it instead of creating a new PR.
> 
> Also, would you help `git rebase master` after fetching the latest master. As usually we wouldn't want merge commits in the PR; usually they will have the commit message "Merge branch 'AlphaWallet:master'", and is the result of running `git pull origin/upstream master" (never do that)

Please see #5273

**Comment by hboon** [comment]
Superseded by #5273 (for posterity)

**Pull request closed without merging**
