### PR TITLE
Replace .green/.white button options with .primary/.secondary button options

### LINKED ISSUE #3838: Replace the primary button color "green" to "cod"
Cod #141414

https://zpl.io/ag7YvpO
https://zpl.io/AmkONme
https://zpl.io/AmkONme

Screenshot 2022-01-27 at 12 37 58

### LINKED ISSUE #3839: Replace the secondary button color
https://zpl.io/V1gKq1w
https://zpl.io/g8qgRnN

We need to change the outline color of secondary buttons from "Azure" to "Cod" #141414

Screenshot 2022-01-27 at 12 39 13

Screenshot 2022-01-27 at 12 41 13

### LINKED ISSUE #3843: Update `BarButton`'s primary and secondary colors
- [x] #3838
- [x] #3839

Follow up with: #3819

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #3838
Closes #3839 
Closes #3843 

Before change.
Simulator Screen Shot - iPhone 11 - 2022-02-11 at 08 02 34 copy 2

After change.
Simulator Screen Shot - iPhone 11 - 2022-02-11 at 08 03 29 copy 2

### CODE REVIEW

**Review by oa-s — APPROVED** [review]

**Comment by hboon** [comment]
@eviltofu can you help include #3839 in the same commit?

**Comment by hboon** [comment]
Or PR if you like

**Comment by eviltofu** [comment]
> @eviltofu can you help include #3839 in the same commit. Also #3843

You mean do the changes for the secondary button in this PR? @hboon

**Comment by hboon** [comment]
> > @eviltofu can you help include #3839 in the same commit. Also #3843
> 
> You mean do the changes for the secondary button in this PR? @hboon

Yes. Sorry, should have been more clear. This should be a single change/PR: #3843

**Comment by eviltofu** [comment]
@hboon @oa-s review please

**Review by hboon — APPROVED** [review]
Looks great. Thanks.

There's a problem with the inactive state when it's first rendered. It has an unwanted border. For example, in the verify seed phrase screen:

First time screen is shown|After tapping a word and then tap clear
-|-
|

I think the one on the right should be the correct version?

Have approved, so you can see if you want to merge this PR first (since it's quite big, merging sooner might cuase fewer conflicts) or fix it together.

---

@oa-s @eviltofu For future reference, this is one of those PRs that might be better if it's broken down into 2 separate commits where the messages are something like:

> * Replace .green/.white button options with .primary/.secondary button options //this will be just a few line change
> * Refactor button bar

Makes it much easier to review and address concerns (or even git revert, though rarely)

**Comment by hboon** [comment]
> might be better if it's broken down into 2 separate commits

But sometimes this isn't possible without spending a lot more unnecessary time though. So it depends.

**Pull request merged**
