### PR TITLE
Remove BalanceTitleView if it's not used anymore #1848

### LINKED ISSUE #1848: Remove BalanceTitleView if it's not used anymore

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1848

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev looks good, can you help remove `BalanceTokenViewModel` too? Seems not used.

**Comment by vladyslav-iosdev** [comment]
> BalanceTokenViewModel

@hboon But it used in  
```
case .ERC20Token(let token, _, _):
            let viewModel = BalanceTokenViewModel(token: token)
            let amount = viewModel.amountShort
            //Note that if we want to display the token name directly from token.name, we have to be careful that DAI token's name has trailing \0
            headerViewModel.title = "\(amount) \(token.titleInPluralForm(withAssetDefinitionStore: assetDefinitionStore))"
            let etherToken = TokensDataStore.etherToken(forServer: session.server)
            let ticker = tokensDataStore.coinTicker(for: etherToken)
            headerViewModel.ticker = ticker
            headerViewModel.currencyAmount = session.balanceCoordinator.viewModel.currencyAmount
            headerViewModel.currencyAmountWithoutSymbol = session.balanceCoordinator.viewModel.currencyAmountWithoutSymbol
            if let viewModel = self.viewModel {
                configure(viewModel: viewModel)
            }
        case .ERC875Token, .ERC875TokenOrder, .ERC721Token, .ERC721ForTicketToken, .dapp:
            break
        }
```

**Comment by vladyslav-iosdev** [comment]
> looks good, can you help remove BalanceTokenViewModel too? Seems not used.

done

**Comment by hboon** [comment]
@vladyslav-iosdev can you help rebase master and make it a single commit? Sorry, got caught up and didn't get to this earlier.

**Comment by vladyslav-iosdev** [comment]
> ou help rebase master and make it a single commit? Sorry, got caught up and didn't get to this earlier.

Done

**Pull request merged**
