### PR TITLE
Update WebImageView with right width scale  #3597

### LINKED ISSUE #3597: Adjust Web ImageView content
Its need properly adjust large and small web images. The current implementation doesn't handle it, large images are displayed mostly ok, but small images stretched on all container that causes quality loosing.

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3597, Closes #3632

### CODE REVIEW

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Whoops. Didn't mean to approve.

Looks like both before and after this PR, the vertical placement (or maybe the height?) of bigger web images are not correct. Might not be in the scope of this PR, but seems realated? Examples taken from my wallet:

Screenshot 2021-12-28 at 10 25 43 AM
Screenshot 2021-12-28 at 10 25 45 AM
Screenshot 2021-12-28 at 10 25 48 AM

**Comment by oa-s** [comment]
@hboon  please check out this Debug version, it has updated with resizing image to center it and fit with containers width if its large

**Comment by hboon** [comment]
I broke `TokenImageView` #3631 causing it to show the chain overlay in the Collectibles tab and after tapping an NFT. You'll see it when you rebase master. I'll try to fix it separately.

Seems OK in the few examples I tried because it's fitting by height. Does it work if the token image is wide and short? I suppose it'll just be truncated at the sides (I think that's OK).

Screenshot 2022-01-05 at 10 46 27 AM

Why is this red rectangle not stretch to fill the height or width though?

Screenshot 2022-01-05 at 10 48 36 AM

**Comment by oa-s** [comment]
@hboon `red rectangle` its actual images frame, we can made it to stretch but in this case small images are going to be in bad quality. Wide images also would be fitted to containers width.

**Comment by hboon** [comment]
@vladyslav-iosdev ok, if this is good, let's get it merged first then.

**Comment by oa-s** [comment]
@hboon Updated PR with scaling token images to fill frame, and remove rounding 
| Before PR     | After PR |
| ------------ | -------- |
|  |  |
|  |  |

**Comment by oa-s** [comment]
@hboon  Please confirm these changes, and if its ok, we could merge it

**Review by hboon — APPROVED** [review]

**Pull request merged**
