### PR TITLE
Display failed transactions in Activity tab

### LINKED ISSUE #2238: Display failed transactions in Activity tab

### LINKED ISSUE #2252: Failed transactions transaction looks like successful transactions
Looks like the failed status for Eth transactions are not captured correctly. 

Screen recording: https://drive.google.com/file/d/1fB-p6VUpDZwk8G2riIgYDo86xWcRXigF/view?usp=sharing

Designs: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e5396f1b3fc047479f08600

Wallet: 0xfCABe3451aC8EDfB8FB6b9274C2E095D9cCC8082

### PR DESCRIPTION
**Pull request by hboon**
Closes #2252, closes #2238

Before PR|After PR
-|-
|

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev bump :)

**Comment by vladyslav-iosdev** [comment]
@hboon what do i need to check here?

**Comment by hboon** [comment]
@vladyslav-iosdev compare the screenshots to check if it matches the title/body of the PR, as well as the code that was modified.

**Comment by vladyslav-iosdev** [comment]
@hboon not it seems like ok. Updated titles with appropriate values

**Comment by hboon** [comment]
@vladyslav-iosdev approve it and merge then :)

**Review by vladyslav-iosdev — APPROVED** [review]

**Pull request merged**
