### PR TITLE
remove issuer label

### PR DESCRIPTION
**Pull request by James-Sangalli**
https://github.com/AlphaWallet/alpha-wallet-android/issues/1453

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli but the problem on Android is that the issuer is always shown as "AlphaWallet", right? Do we want to remove it entirely?

**Comment by James-Sangalli** [comment]
> @James-Sangalli but the problem on Android is that the issuer is always shown as "AlphaWallet", right? Do we want to remove it entirely?

Nope, it works correctly. It displays AlphaWallet because we signed it with that certificate and therefore it says that. Same in iOS

**Comment by hboon** [comment]
@James-Sangalli got it.

**Comment by James-Sangalli** [comment]
@hboon we should probably also remove the "ethereum blockchain" text since it's pretty redundant (but keep the spacing), keen?

**Comment by hboon** [comment]
> @hboon we should probably also remove the "ethereum blockchain" text since it's pretty redundant (but keep the spacing), keen?

@James-Sangalli going in here: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1902#issuecomment-641034194

**Pull request merged**
