### PR TITLE
Show error message if dapp selects a chain for WalletConnect that is disabled in the app #2652

### LINKED ISSUE #2652: Show error message if dapp selects a chain for WalletConnect that is disabled in the app
1. Disable mainnet
2. Visit https://example.walletconnect.org
3. Tap "Connect to WalletConnect"

Expected:

4. Show error: "<Ethereum> is disabled. You can enable it in Settings > Select Active Networks" (replace with `RPCServer.name`)

Observed (screenshot):

Screenshot 2021-03-18 at 12 29 14 PM

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2652

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Still seems to work like before the PR.

**Comment by vladyslav-iosdev** [comment]
> Still seems to work like before the PR.

it appears when we tap `connect` button on appeared connection alert. Maybe i misunderstood something?

**Comment by hboon** [comment]
Oh. Will check again. Thanks

**Review by hboon — APPROVED** [review]
@vladyslav-iosdev I was thinking to show the error and not show the actionsheet at all, but this works too. Thanks!

**Pull request merged**
