### PR TITLE
Group logic components in core folder #5234

### LINKED ISSUE #5234: Make a build so that the artifacts (jars for Android, frameworks for iOS) and their dependencies can be included in another project
* We can keep the UI, but not spin it up
* Make a dummy function in the code that signs a message
* Create a new skeleton driver project that uses this AlphaWallet project that includes something like this pseudocode:

```
import SDK
let wallet = SDK.Wallet("hardcoded seed phrase")
let result = wallet.signPersonal("some message")
let address = SDK.ecrecover(result)
print(wallet.address == address)
```

Goals
---
- [ ] Check feasibility
- [ ] Check constraints (including usage of dependencies, operating system requirements, build options)

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5234

### CODE REVIEW

**Comment by oa-s** [comment]
Too many files, might be missed some, no functional changes, just files grouping

**Review by hboon — APPROVED** [review]
@oa-s OK. Too big to review. Let's merge it as soon as it build and passes tests (at least locally).

**Comment by oa-s** [comment]
> @oa-s OK. Very big indeed. Let's merge it as soon as it builds and passes tests (at least locally).

ok, i will be ready at least when remove all dependencies from resources (for now strings have left), so we could easily move files to another folder. Apply public interfaces and importing we could make in another pr

**Comment by hboon** [comment]
@oa-s OK, merge ASAP because you might have conflicts from other PRs.

**Comment by oa-s** [comment]
squashed prs, once trevis will finish without errors will merge pr

**Pull request merged**
