### PR TITLE
Replace modal presentation for confimation view controller #4120

### LINKED ISSUE #3495: Stuck at send ERC20 screen after tapping Send button. Screen grayed out
Can't reproduce.

Expecting the actionsheet to show up next.

Maybe a race condition or problem related to `DispatchQueue`?

IMG_9695

### LINKED ISSUE #4120: Freeze with grayed out screen after sending ETH on Ropsten successfully
This is right after the actionsheet is closed. The transaction was sent successfully (confirmed in Etherscan). Could be intermittent.

IMG_0096

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4120, Closes #3495

### CODE REVIEW

**Review by hboon — APPROVED** [review]
Could you help give the commit a more descriptive comment (and the PR title)? Is it a refactor (replacing the implementation, but no functional changes yet) or does it provide some functionality change right away?

**Comment by oa-s** [comment]
Functionally this PR replace our custom implementation of confirmation screen representation, and replaces it with other more configurable and tested pod `FloatingPanel`. It allows to present any view controller as modal action sheet. 

One more this that implements this pr is order of presentation for view controllers after confirmation transaction. during testing were found that askUserToRateAppOrSubscribeToNewsletter doesn't appear because of  `Warning: Attempt to present * on * which is already presenting`. `askUserToRateAppOrSubscribeToNewsletter` was moved to in coordinator and presented after closing `transaction in progress` view.

my fault is that i missed to create another brach for `Improve error presentation when transaction has sent` this comming is based on other prev changes and improves displaying error message when failure to send tx. It fixes `Warning: Attempt to present..` error.

`Tweak send transaction error view controller` fixes test cases, as `lastViewControllerInNavigationStack` can be nil, it was need to be updated.

**Comment by oa-s** [comment]
Seesm like both #4120 and #3495 a related to our custom modal presentation,  for confirmation screen. For both cases we are facing that host navigation controller has presented, but view with content hasn't.

**Comment by hboon** [comment]
Thanks for the clarification. Merge after resolving conflicts?

**Pull request merged**
