### PR TITLE
Replace multiple filters in EventsActivityDataStore, EventsDataStore with single predicate #3981

### LINKED ISSUE #3981: Replace multiple filters with single predicate

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3981

### CODE REVIEW

**Comment by hboon** [comment]
Does this not work out to the same code at real time?

**Comment by oa-s** [comment]
Here is some measurement results:
### First - `.filter(predicate)`
### Second - `.filter("contract = '\(contract.eip55String)'")...`
```
[XXX] First Took 0.00018393993377685547 seconds
[XXX] Second Took 0.0006090402603149414 seconds

[XXX] First Took 0.00014901161193847656 seconds
[XXX] Second Took 0.0005180835723876953 seconds

[XXX] First Took 0.00010001659393310547 seconds
[XXX] Second Took 0.0002770423889160156 seconds

[XXX] First Took 0.0001220703125 seconds
[XXX] Second Took 0.00020897388458251953 seconds

[XXX] First Took 0.0001499652862548828 seconds
[XXX] Second Took 0.00022804737091064453 seconds

[XXX] First Took 0.00012600421905517578 seconds
[XXX] Second Took 0.00032889842987060547 seconds

[XXX] First Took 0.00012099742889404297 seconds
[XXX] Second Took 0.00024402141571044922 seconds

[XXX] First Took 0.00010097026824951172 seconds
[XXX] Second Took 0.00021409988403320312 seconds

[XXX] First Took 0.0001239776611328125 seconds
[XXX] Second Took 0.00025403499603271484 seconds

[XXX] First Took 0.00015997886657714844 seconds
[XXX] Second Took 0.00028908252716064453 seconds

[XXX] First Took 0.00015294551849365234 seconds
[XXX] Second Took 0.0001919269561767578 seconds

[XXX] First Took 0.00011491775512695312 seconds
[XXX] Second Took 0.0005960464477539062 seconds

[XXX] First Took 0.0001360177993774414 seconds
[XXX] Second Took 0.00045299530029296875 seconds

[XXX] First Took 0.00011992454528808594 seconds
[XXX] Second Took 0.000308990478515625 seconds

[XXX] First Took 0.00015401840209960938 seconds
[XXX] Second Took 0.00029397010803222656 seconds
```

**Review by hboon — APPROVED** [review]
Ah interesting. Thought it would be the same.

**Comment by hboon** [comment]
Merge when ready

**Comment by hboon** [comment]
Good in such PRs to explain why in the commit message, i.e. mentioning "to improve performance". The "why" is often more useful than what.

**Pull request merged**
