### PR TITLE
add debug logs #6725

### LINKED ISSUE #6725: Token on Polygon Mumbai testnet shows collection image, but not token image
Token: https://mumbai.polygonscan.com/address/0xC9419ebd3DcBdFf2FaD35a8e13AcA24C26E9A38d
Wallet: hweeboon.eth

It could be because the token's `tokenURI(tokenId)` value was invalid when it was downloaded, but it has now been fixed

Screenshot 2023-04-25 at 10 25 20 AM

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6725

### CODE REVIEW

**Comment by oa-s** [comment]
@hboon could u please check it on your side, and share debug logs?

**Review by hboon — COMMENTED** [review]
It appears now:

```
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.getUriOrTokenUri: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "273207563", value: "{\n  \"animationUrl\" : \"\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"description\" : \"Glenn Maxwell #273207563\",\n  \"externalLink\" : \"\",\n  \"tokenType\" : \"erc721\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"symbol\" : \"CATCHMAX\",\n  \"name\" : \"Glenn Maxwell\",\n  \"attributes\" : [\n    {\n      \"value\" : \"Team Australia\",\n      \"trait_type\" : \"background\"\n    },\n    {\n      \"value\" : \"Kangaroo\",\n      \"trait_type\" : \"topSticker\"\n    },\n    {\n      \"value\" : \"T20 All-Rounder\",\n      \"trait_type\" : \"bottomSticker\"\n    },\n    {\n      \"value\" : \"Vertical\",\n      \"trait_type\" : \"name\"\n    },\n    {\n      \"value\" : \"Autograph White\",\n      \"trait_type\" : \"autograph\"\n    }\n  ],\n  \"contractName\" : \"Catch Max\",\n  \"thumbnailUrl\" : \"\",\n  \"tokenId\" : \"273207563\",\n  \"decimals\" : 0\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "2463086978", value: "{\n  \"animationUrl\" : \"\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"description\" : \"Glenn Maxwell #2463086978\",\n  \"externalLink\" : \"\",\n  \"tokenType\" : \"erc721\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"symbol\" : \"CATCHMAX\",\n  \"name\" : \"Glenn Maxwell\",\n  \"attributes\" : [\n    {\n      \"trait_type\" : \"background\",\n      \"value\" : \"Abstract Orange\"\n    },\n    {\n      \"trait_type\" : \"topSticker\",\n      \"value\" : \"India\"\n    },\n    {\n      \"trait_type\" : \"bottomSticker\",\n      \"value\" : \"Bat Kookaburra\"\n    },\n    {\n      \"trait_type\" : \"name\",\n      \"value\" : \"Vertical\"\n    },\n    {\n      \"trait_type\" : \"autograph\",\n      \"value\" : \"Autograph Black\"\n    }\n  ],\n  \"contractName\" : \"Catch Max\",\n  \"thumbnailUrl\" : \"\",\n  \"tokenId\" : \"2463086978\",\n  \"decimals\" : 0\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchTokenJson: success(423 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "3044018833", value: "{\n  \"animationUrl\" : \"\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"externalLink\" : \"\",\n  \"description\" : \"Glenn Maxwell #3044018833\",\n  \"tokenType\" : \"erc721\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"symbol\" : \"CATCHMAX\",\n  \"name\" : \"Glenn Maxwell\",\n  \"attributes\" : [\n    {\n      \"trait_type\" : \"background\",\n      \"value\" : \"Space 2\"\n    },\n    {\n      \"trait_type\" : \"topSticker\",\n      \"value\" : \"Batting Gloves\"\n    },\n    {\n      \"trait_type\" : \"bottomSticker\",\n      \"value\" : \"Helmet Masuri Green\"\n    },\n    {\n      \"trait_type\" : \"name\",\n      \"value\" : \"Vertical\"\n    },\n    {\n      \"trait_type\" : \"autograph\",\n      \"value\" : \"Autograph White\"\n    }\n  ],\n  \"contractName\" : \"Catch Max\",\n  \"thumbnailUrl\" : \"\",\n  \"tokenId\" : \"3044018833\",\n  \"decimals\" : 0\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.fetchJsonFromTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.getUriOrTokenUri: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "273207563", value: "{\n  \"animationUrl\" : \"\",\n  \"attributes\" : [\n    {\n      \"trait_type\" : \"background\",\n      \"value\" : \"Team Australia\"\n    },\n    {\n      \"trait_type\" : \"topSticker\",\n      \"value\" : \"Kangaroo\"\n    },\n    {\n      \"trait_type\" : \"bottomSticker\",\n      \"value\" : \"T20 All-Rounder\"\n    },\n    {\n      \"trait_type\" : \"name\",\n      \"value\" : \"Vertical\"\n    },\n    {\n      \"trait_type\" : \"autograph\",\n      \"value\" : \"Autograph White\"\n    }\n  ],\n  \"contractName\" : \"Catch Max\",\n  \"name\" : \"Glenn Maxwell\",\n  \"tokenType\" : \"erc721\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"description\" : \"Glenn Maxwell #273207563\",\n  \"thumbnailUrl\" : \"\",\n  \"symbol\" : \"CATCHMAX\",\n  \"externalLink\" : \"\",\n  \"tokenId\" : \"273207563\",\n  \"decimals\" : 0\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchTokenJson: success(423 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "3044018833", value: "{\n  \"animationUrl\" : \"\",\n  \"attributes\" : [\n    {\n      \"value\" : \"Space 2\",\n      \"trait_type\" : \"background\"\n    },\n    {\n      \"value\" : \"Batting Gloves\",\n      \"trait_type\" : \"topSticker\"\n    },\n    {\n      \"value\" : \"Helmet Masuri Green\",\n      \"trait_type\" : \"bottomSticker\"\n    },\n    {\n      \"value\" : \"Vertical\",\n      \"trait_type\" : \"name\"\n    },\n    {\n      \"value\" : \"Autograph White\",\n      \"trait_type\" : \"autograph\"\n    }\n  ],\n  \"decimals\" : 0,\n  \"tokenId\" : \"3044018833\",\n  \"externalLink\" : \"\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"name\" : \"Glenn Maxwell\",\n  \"description\" : \"Glenn Maxwell #3044018833\",\n  \"thumbnailUrl\" : \"\",\n  \"symbol\" : \"CATCHMAX\",\n  \"contractName\" : \"Catch Max\",\n  \"tokenType\" : \"erc721\"\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "2463086978", value: "{\n  \"tokenId\" : \"2463086978\",\n  \"attributes\" : [\n    {\n      \"value\" : \"Abstract Orange\",\n      \"trait_type\" : \"background\"\n    },\n    {\n      \"value\" : \"India\",\n      \"trait_type\" : \"topSticker\"\n    },\n    {\n      \"value\" : \"Bat Kookaburra\",\n      \"trait_type\" : \"bottomSticker\"\n    },\n    {\n      \"value\" : \"Vertical\",\n      \"trait_type\" : \"name\"\n    },\n    {\n      \"value\" : \"Autograph Black\",\n      \"trait_type\" : \"autograph\"\n    }\n  ],\n  \"symbol\" : \"CATCHMAX\",\n  \"decimals\" : 0,\n  \"description\" : \"Glenn Maxwell #2463086978\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"contractName\" : \"Catch Max\",\n  \"name\" : \"Glenn Maxwell\",\n  \"animationUrl\" : \"\",\n  \"tokenType\" : \"erc721\",\n  \"externalLink\" : \"\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"thumbnailUrl\" : \"\"\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.fetchJsonFromTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.getUriOrTokenUri: finished
xxx.getUriOrTokenUri: uri(https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.getUriOrTokenUri: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "273207563", value: "{\n  \"attributes\" : [\n    {\n      \"trait_type\" : \"background\",\n      \"value\" : \"Team Australia\"\n    },\n    {\n      \"trait_type\" : \"topSticker\",\n      \"value\" : \"Kangaroo\"\n    },\n    {\n      \"trait_type\" : \"bottomSticker\",\n      \"value\" : \"T20 All-Rounder\"\n    },\n    {\n      \"trait_type\" : \"name\",\n      \"value\" : \"Vertical\"\n    },\n    {\n      \"trait_type\" : \"autograph\",\n      \"value\" : \"Autograph White\"\n    }\n  ],\n  \"decimals\" : 0,\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"symbol\" : \"CATCHMAX\",\n  \"tokenType\" : \"erc721\",\n  \"externalLink\" : \"\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_aus_style.png\",\n  \"description\" : \"Glenn Maxwell #273207563\",\n  \"name\" : \"Glenn Maxwell\",\n  \"tokenId\" : \"273207563\",\n  \"thumbnailUrl\" : \"\",\n  \"animationUrl\" : \"\",\n  \"contractName\" : \"Catch Max\"\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/273207563)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchTokenJson: success(423 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "3044018833", value: "{\n  \"animationUrl\" : \"\",\n  \"attributes\" : [\n    {\n      \"value\" : \"Space 2\",\n      \"trait_type\" : \"background\"\n    },\n    {\n      \"value\" : \"Batting Gloves\",\n      \"trait_type\" : \"topSticker\"\n    },\n    {\n      \"value\" : \"Helmet Masuri Green\",\n      \"trait_type\" : \"bottomSticker\"\n    },\n    {\n      \"value\" : \"Vertical\",\n      \"trait_type\" : \"name\"\n    },\n    {\n      \"value\" : \"Autograph White\",\n      \"trait_type\" : \"autograph\"\n    }\n  ],\n  \"tokenId\" : \"3044018833\",\n  \"decimals\" : 0,\n  \"name\" : \"Glenn Maxwell\",\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_international_style_1.png\",\n  \"thumbnailUrl\" : \"\",\n  \"contractName\" : \"Catch Max\",\n  \"externalLink\" : \"\",\n  \"symbol\" : \"CATCHMAX\",\n  \"tokenType\" : \"erc721\",\n  \"description\" : \"Glenn Maxwell #3044018833\"\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/3044018833)
xxx.fetchJsonFromTokenUri: finished
xxx.fetchTokenJson: success(407 bytes)
xxx.fetchTokenJson: finished
xxx.fetchJsonFromTokenUri: NonFungibleBalanceAndItsSource<String>(tokenId: "2463086978", value: "{\n  \"name\" : \"Glenn Maxwell\",\n  \"thumbnailUrl\" : \"\",\n  \"tokenType\" : \"erc721\",\n  \"decimals\" : 0,\n  \"imageUrl\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"tokenId\" : \"2463086978\",\n  \"attributes\" : [\n    {\n      \"value\" : \"Abstract Orange\",\n      \"trait_type\" : \"background\"\n    },\n    {\n      \"value\" : \"India\",\n      \"trait_type\" : \"topSticker\"\n    },\n    {\n      \"value\" : \"Bat Kookaburra\",\n      \"trait_type\" : \"bottomSticker\"\n    },\n    {\n      \"value\" : \"Vertical\",\n      \"trait_type\" : \"name\"\n    },\n    {\n      \"value\" : \"Autograph Black\",\n      \"trait_type\" : \"autograph\"\n    }\n  ],\n  \"image\" : \"https:\\/\\/resources.catchmax.io\\/predefined\\/predefined_india_style.png\",\n  \"description\" : \"Glenn Maxwell #2463086978\",\n  \"contractName\" : \"Catch Max\",\n  \"externalLink\" : \"\",\n  \"animationUrl\" : \"\",\n  \"symbol\" : \"CATCHMAX\"\n}", source: https://resources.smarttokenlabs.com/80001/0xc9419ebd3dcbdff2fad35a8e13aca24c26e9a38d/2463086978)
xxx.fetchJsonFromTokenUri: finished
```

**Comment by hboon** [comment]
Yeah. Is it supposed to only show the problem or fix it? It works for me

**Comment by oa-s** [comment]
yes, its only shows the problem

**Comment by hboon** [comment]
Strange. Not need to do anything then I guess?

**Comment by oa-s** [comment]
don't know, maybe figure our the other ways to handle this flow

**Comment by hboon** [comment]
Ok. Since it works, unless you come up with something quickly, no rush. Better work towards shipping push then.

**Pull request closed without merging**
