### PR TITLE
Deeplink-based wallet API #4659

### LINKED ISSUE #4659: Deeplink-based wallet API
So we'll need 2 actionsheets, 1 for connect and one for sign message. We might have sign transaction in the future (but not now).

The fields/values are:

For Connect
---
* icon
* name
* URL
* Hardcoded description with address value (feel free to rewrite it, including the address format)

For Sign Message
---
* icon
* name
* URL
* Message

Maybe a good idea to mirror how we present actionsheets for WalletConnect. We don't need to track sessions like we do for WalletConnect.

Roughly like this:

deeplink-wallet-api

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4659

### CODE REVIEW

**Comment by oa-s** [comment]
**signpersonalmessage**

let url2 = URL(string: "https://aw.app/wallet/v1/signpersonalmessage?redirecturl=https%3A%2F%2Fmyapp.com&metadata=%7B%22name%22%3A%22Some+app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D&message=0x48656c6c6f20416c7068612057616c6c6574")!

**connect**

let url2 = URL(string: "https://aw.app/wallet/v1/connect?redirecturl=https%3A%2F%2Fmyapp.com&metadata=%7B%22name%22%3A%22Some+app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D")!

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — CHANGES_REQUESTED** [review]
Great. Mostly there:

- [ ] Can you help to modify the query parameters appended to the `redirecturl` upon success to:

* connect:
    * success
        * call=connect&address=<address>
    * failure
        * call=connect

* signpersonalmessage:
    * success
        * call=signpersonalmessage&signature=<signature>
    * failure
        * call=signature

- [ ] Rejecting (including tapping the `X` button or tapping outside the actionsheet) for a `connect` or `signpersonalmessage` should also redirect to `redirecturl` but with query parameters described above under "failure"

- [ ] Redirecting to `redirecturl` should open in Safari (or whichever app handles the deeplink) instead of our dapp browser. Probably `UIApplication.shared.open(_:)`?

- [ ] Can you try if `redirecturl` already includes `?` and optional, query parameters that it would work too? I didn't try :) examples: `redirecturl=https://myapp.com?somethinghere=already`, `redirecturl=https://myapp.com?` and `redirecturl=https://myapp.com?key=value&` (escaped). Maybe add test cases?

- [ ] "Connect to Site?" should be "Connect to"

- [ ] `connect`'s '"Connected to" should be "URL" (for `appurl`)

- [ ] The "Note" row with text "This will inform them your wallet address is 0xb0b" should appear for `connect` (Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/4659#issuecomment-1147310194)

- [ ] Connect and Reject buttons should be swapped around

- [ ] "Some+app" should be "Some app" (or is the example URL not encoded correct by using `+`?)

- [ ] `signpersonalmessage` should not show "Network"

- [ ] `signpersonalmessage`'s '"Website" should be `URL` (for `appurl`)

- [ ] Sign and Cancel buttons should be swapped around

**Comment by hboon** [comment]
I forgot to check so:

- [ ] Verify WalletConnect v1 still works :)

**Comment by oa-s** [comment]
an example of metadata json for `connect`:

`{"name":"Some app","iconurl":"https://img.icons8.com/nolan/344/ethereum.png", "appurl": "https://uniswap.org/", "note":"This will inform them your wallet address is 0x2322…2324"}`

**Comment by oa-s** [comment]
%7B%22name%22%3A%22Some%20app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D%26message%3D0x48656c6c6f20416c7068612057616c6c6574

> * [ ]  "Some+app" should be "Some app" (or is the example URL not encoded correct by using `+`?)
> *

white space just need to be encoded right when passing url. instead of `+` character there should be `%20`

**Comment by oa-s** [comment]
Ready for review

**Comment by hboon** [comment]
> %7B%22name%22%3A%22Some%20app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D%26message%3D0x48656c6c6f20416c7068612057616c6c6574
> 
> > * [ ]   "Some+app" should be "Some app" (or is the example URL not encoded correct by using `+`?)
> 
> white space just need to be encoded right when passing url. instead of `+` character there should be `%20`

Ah I see. Then we have to support both `+` and `%20`, because:

* https://www.google.com.sg/search?q=some+app (it uses `+`)
* https://www.rfc-editor.org/rfc/rfc1866#section-8.2.1

Also ruby:

```
#!/usr/bin/ruby

require 'cgi'

s = "some app"
#s = "some%20app"
#s = "some+app"

p "start: #{s}"

unescaped = CGI.unescape s
p "test : #{unescaped}"
if unescaped == s
    p "same so escape instead…"
    p CGI.escape s
else
    p "different, so use unescaped: #{unescaped}"
end
```

prints effectively:

> "some app" -> "some+app"
> "some%20app" -> "some app"
> "some+app" -> "some app"

**Review by hboon — CHANGES_REQUESTED** [review]
- [ ] "Connect to <url>" in the title/header should just be "Connect to"

Seems to be missing this:

- [ ] The "Note" row with text "This will inform them your wallet address is 0xb0b" should appear for connect (Refer to #4659 (comment))

@oa-s I'm sorry I mentioned this elsewhere in passing but not here, `signpersonalmessage` needs an additional `address` key and value and AlphaWallet should check that this matches the current address, otherwise return to `redirecturl` as a failure.

So from your example above in this PR:

```
let url2 = URL(string: "https://aw.app/wallet/v1/signpersonalmessage?redirecturl=https%3A%2F%2Fmyapp.com&metadata=%7B%22name%22%3A%22Some+app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D&message=0x48656c6c6f20416c7068612057616c6c6574")!
```

It should be:

```
let url2 = URL(string: "https://aw.app/wallet/v1/signpersonalmessage?redirecturl=https%3A%2F%2Fmyapp.com&metadata=%7B%22name%22%3A%22Some+app%22%2C%22iconurl%22%3A%22https%3A%2F%2Fimg.icons8.com%2Fnolan%2F344%2Fethereum.png%22%7D&message=0x48656c6c6f20416c7068612057616c6c6574&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3")!
```

(The caller should have figured out the address value from the initial `connect` call)

- [x] If `address` is missing or doesn't match the current address, the signing prompt should not appear at all (maybe we'll need to provide a reason in the callback, but let's get this merged in first without the reason, I've dragged your PR for long enough)

**Comment by oa-s** [comment]
> [ ] The "Note" row with text "This will inform them your wallet address is 0xb0b" should appear for connect (Refer to [Deeplink-based wallet API #4659](https://github.com/AlphaWallet/alpha-wallet-ios/issues/4659) (comment))

@hboon is this block should be presented all the time we trying to connect? or only when metadata contains `note` field?

**Comment by hboon** [comment]
> @hboon is this block should be presented all the time we trying to connect? or only when metadata contains `note` field?

Always shown when `connect` is triggered. In other words, the text is something like this (in Swift):

```
"This will inform them your wallet address is \(address.eip55String)"
```

There is no "note" field in the metadata.

**Comment by oa-s** [comment]
@hboon  and `address.eip55String` is your active wallet?, as we don't have address in connect params

**Comment by hboon** [comment]
> @hboon and `address.eip55String` is your active wallet?, as we don't have address in connect params

Yes, it's the active wallet and the same one that is returned to the callback for that `connect` call

**Comment by hboon** [comment]
@oa-s want me to look at this again?

**Comment by oa-s** [comment]
@hboon, yes please. also i will update localization for it and its ready to merge

**Review by hboon — CHANGES_REQUESTED** [review]
- [x] Missed out this one (support both "+" and "%20"): https://github.com/AlphaWallet/alpha-wallet-ios/pull/4829#issuecomment-1158439696

- [x] I noticed that after tapping the `Connect` button, there is a noticeable pause compared to after tapping the `Reject` button for `.connect` calls. Not so important, but just in case there's a bug

- [x] `signpersonalmessage` without an address or with an invalid address should redirect back to `redirecturl` too, as if it was cancelled, see the 2 links under "Invalid" in https://wallet-deeplink-api.hboon.repl.co

**Comment by oa-s** [comment]
> Missed out this one (support both "+" and "%20"): https://github.com/AlphaWallet/alpha-wallet-ios/pull/4829#issuecomment-1158439696

made new commit, but not sure in it. tested with `+` and '%20', looks like it works

**Review by hboon — APPROVED** [review]
Looks good. Thanks.

I'm wondering if `WalletApiServiceError.connectionAddressNotFound` should be displayed to the user, but let's keep it as it is.

**Pull request merged**
