### PR TITLE
[Refactor] Rename fetch smartcontract data coordinator with provider suffix #4529

### LINKED ISSUE #4529: [Refactor] Rename fetch smartcontract data coordinator with provider suffix

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4529

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
This goes towards #4282 right? Do you think we can just NativeCryptoCurrencyBalanceProvider

Instead of `NativeCryptoCurrencyBalanceProvider`, do you think it's better to call it: `GetNativeCryptoCurrencyBalance`? It's shorter (not a big deal), violates the noun convention (not a big deal I think), but can attach more meaning eg. "GetXXX" fetches some value, "ENSResolver" resolves.

Going by this rationale:

> — these are just logic and non-UI eg. What used to be GetENSOwnerCoordinator, ENSReverseLookupCoordinator.swift, GetENSTextRecordsCoordinator. They are used once and destroyed. They will soon be renamed to ENSResolver, ENSReverseResolver, GetENSTextRecord. Conventional wisdom says they should all be nouns, but I don't think it's easy to come up with a noun that is better than GetENSTextRecord — GetENSTextRecordManager is silly!

Similar for the other renamed types.

Also, remember to move the files out of the `coordinators` directories either in this PR.

**Comment by oa-s** [comment]
@oa-s is this related only to NativeCryptoCurrencyBalanceProvider? or the rest too?

**Comment by hboon** [comment]
@oa-s the rest too. Generally. Let provider bring a fallback when we don’t have a better name.

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — APPROVED** [review]

**Pull request merged**
