### PR TITLE
tweak canceling a subscription on receiving completion, remove storing in cancellable #6220

### LINKED ISSUE #6220: Crash soon after launch while testing #6217 but probably unrelated
No TokenScript overrides.

```
2023-01-26 10:12:48.340913+0800 AlphaWallet[95412:2180191] -[NSIndexPath member:]: unrecognized selector sent to instance 0x8000000000000000
2023-01-26 10:12:48.739620+0800 AlphaWallet[95412:2180191] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSIndexPath member:]: unrecognized selector sent to instance 0x8000000000000000'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018041d47c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001804126c8 ___forwarding___ + 1308
	4   CoreFoundation                      0x0000000180414b4c _CF_forwarding_prep_0 + 92
	5   libswiftCore.dylib                  0x000000018be9d634 $ss17__CocoaDictionaryV6lookupyyXlSgyXlFTm + 52
	6   Combine                             0x000000019ba902f4 $sSh8_VariantV6insertySb8inserted_x17memberAfterInserttxnF7Combine14AnyCancellableC_Tg5 + 100
	7   Combine                             0x000000019ba8fec8 $s7Combine14AnyCancellableC5store2inyShyACGz_tF + 44
	8   AlphaWalletFoundation               0x0000000106ed0464 $s21AlphaWalletFoundation20AssetDefinitionStoreC8fetchXML11forContract6server16useCacheAndFetch17completionHandlery0aB7Address0aB0O0R0O_AA9RPCServerOSgSbyAC6ResultOcSgtF + 1456
	9   AlphaWalletFoundation               0x0000000106f87720 $s21AlphaWalletFoundation20ContractDataDetectorC5fetch10completionyyAA0dE0Oc_tF + 468
	10  AlphaWalletFoundation               0x0000000107159444 $s21AlphaWalletFoundation19ContractDataFetcherC05fetchdE03for6server10completiony0aB7Address0aB0O0K0O_AA9RPCServerOyAA0dE0OctF + 340
	11  AlphaWalletFoundation               0x00000001071596ec $s21AlphaWalletFoundation19ContractDataFetcherCAA0dE9FetchableA2aDP05fetchdE03for6server10completiony0aB7Address0aB0O0L0O_AA9RPCServerOyAA0dE0OctFTW + 20
	12  AlphaWalletFoundation               0x000000010715da40 $s21AlphaWalletFoundation11ImportTokenC17fetchContractData3for6server10completiony0aB7Address0aB0O0L0O_AA9RPCServerOyAA0gH0OctF + 164
	13  AlphaWalletFoundation               0x0000000107160218 $s21AlphaWalletFoundation11ImportTokenC05fetchE19OrContractPublisher3for6server21onlyIfThereIsABalance7Combine03AnyI0VyAA0egH0OAC0dE5ErrorOG0aB7Address0aB0O0T0O_AA9RPCServerOSbtFAoTcfU_yys6ResultOyAlNGccfU_ + 360
	14  Combine                             0x000000019bac518c $s7Combine6FutureCyACyxq_Gyys6ResultOyxq_GcccfcTf4gn_n + 232
	15  Combine                             0x000000019bac28e0 $s7Combine6FutureCyACyxq_Gyys6ResultOyxq_GcccfC + 56
	16  AlphaWalletFoundation               0x000000010715fa5c $s21AlphaWalletFoundation11ImportTokenC05fetchE19OrContractPublisher3for6server21onlyIfThereIsABalance7Combine03AnyI0VyAA0egH0OAC0dE5ErrorOG0aB7Address0aB0O0T0O_AA9RPCServerOSbtFAoTcfU_ + 1172
	17  Combine                             0x000000019bb53aa4 $s7Combine10PublishersO7FlatMapV5Outer33_E91C3F00A6DFAAFEA2009FAF507AE039LLC7receiveyAA11SubscribersO6DemandV6OutputQy_F + 132
	18  Combine                             0x000000019bb55308 $s7Combine10PublishersO7FlatMapV5Outer33_E91C3F00A6DFAAFEA2009FAF507AE039LLCy_xq__qd__GAA10SubscriberA2aJP7receiveyAA11SubscribersO6DemandV5InputQzFTW + 20
	19  Combine                             0x000000019bad851c $s7Combine10PublishersO9ReceiveOnV5Inner33_1178A6B2012BC46DB46053E713A746B4LLC7receiveyAA11SubscribersO6DemandV6OutputQzFyycfU_ + 208
	20  libswiftDispatch.dylib              0x00000001a1a97cd4 $sIeg_IeyB_TR + 28
	21  libdispatch.dylib                   0x0000000180133fa4 _dispatch_call_block_and_release + 24
	22  libdispatch.dylib                   0x0000000180135768 _dispatch_client_callout + 16
	23  libdispatch.dylib                   0x000000018013d7f8 _dispatch_lane_serial_drain + 780
	24  libdispatch.dylib                   0x000000018013e43c _dispatch_lane_invoke + 392
	25  libdispatch.dylib                   0x000000018014a624 _dispatch_workloop_worker_thread + 772
	26  libsystem_pthread.dylib             0x00000001b059a8fc _pthread_wqthread + 284
	27  libsystem_pthread.dylib             0x00000001b05996c0 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException

Process finished with exit code 0
```

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6220

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Can you point out which part fix the crash?

**Comment by oa-s** [comment]
> Can you point out which part fix the crash?

my bad, this one applying inflight for fetching xml

fixing is here: https://github.com/oa-s/alpha-wallet-ios/blob/bd286f773bb860df03c38cd99de5fb72b1c11629/modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/AssetDefinitionStore.swift#L216

**Comment by oa-s** [comment]
Skip this pr for now

**Comment by hboon** [comment]
I see. Do you mean to close this PR?

**Comment by oa-s** [comment]
hold this one, maybe we could use something from it or close it

**Comment by hboon** [comment]
Close for now

**Pull request closed without merging**
