### PR TITLE
Followup tasks for ERC1155 support #3224

### LINKED ISSUE #3224: Followup tasks for ERC1155 support
There are pending tasks for ERC1155 support after #3221:

- [ ] Classify token IDs in an ERC1155 contract into collections. i.e. 1 contract, N collections
    * James seems to have a solution
- [ ] Can we take decimals > 0 as meaning the token ID is fungible? (But can it be a fractional NFT?)
 Support batch transfers (and Select at top right hand corner of Assets sub-tab needs to be enabled)
- [x] Looks like a bug: `let view = SingleTokenCardAmountSelectionToolbarView(viewModel: .init(availableAmount: 20, selectedAmount: 1))`
    * Affects ERC721 ? Beause it's not used  for ERC1155
- [ ] Missing fields in token collection. Not sure we can get all of them (refer to UI design)
    * Issuer
    * Assets
    * Melts
    * Hodlers/Holders
    * Transfers
- [x] Missing fields in token ID screen (refer to UI design)
    * Issuer
    * Circulating Supply
    * Total Supply
    * Reserve Value
    * Type
    * Transferable
    * Melt Fee
    * Transfer Fee
    * Created (i.e. date)
- [ ] Some token URI JSONs have more metadata (e.g. properties?) eg. https://lostrelics.io/item-metadata/18000000000005e1000000000000000000000000000000000000000000000000
- [ ] Check add custom token from UI handles ERC1155 correctly. Especially balance. Also name/symbol is not part of ERC1155 (e.g. Enjin), and symbol is not applicable
- [ ] Check if relevant, about how tokenURI is interpreted: https://github.com/AlphaWallet/AlchemyNFT/issues/513
- [x] Tap token row in send 1155 should expand to show each tokenId + value
- [x] The big image after tapping on a token (tokenId) should almost fill the screen horizontally
- [x] Show default/fallback token ID icon when they are not available #3223

### LINKED ISSUE #3504: TokensCardCollectionCoordinator instance's delegate not set
https://github.com/AlphaWallet/alpha-wallet-ios/blob/79ae11b8b97cac88f013b54c9e0f9b0b313c04d5/AlphaWallet/Tokens/ViewControllers/Collectibles/Coordinators/TokensCardCollectionCoordinator.swift#L35

Looks like a bug?

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3224, Closes #3504

### CODE REVIEW

**Review by hboon — APPROVED** [review]
Need to rebase and fix conflicts

**Comment by hboon** [comment]
@oa-s tests seems broken

**Comment by hboon** [comment]
@oa-s let me know if I still need to check anything? Otherwise rebase and merge whenever you are ready. It involves many files, better for you to merge and verify.

**Comment by oa-s** [comment]
@hboon u can merge it, i have no rights to merge it.

**Comment by hboon** [comment]
@oa-s accepted your invite yet? :)

**Comment by oa-s** [comment]
> @oa-s accepted your invite yet? :)

seems like yes

**Comment by hboon** [comment]
So strange:

Screenshot 2021-12-28 at 3 55 19 PM

But I have just changed your collabarator settings too. Try again?

**Comment by eviltofu** [comment]
Didn't I already accept??

**Comment by oa-s** [comment]
Could you please cancel request and resent a new one?

**Comment by hboon** [comment]
Done.

**Comment by oa-s** [comment]
> Done.

Perfect, thanks :)

**Pull request merged**
