### PR TITLE
EIP 3085 doesn't work #2966

### LINKED ISSUE #2966: EIP 3085 doesn't work
I was trying out https://chainlist.org/. None of the chains that I tried to add works on AlphaWallet. However, most of them works on Metamask.

image

One random example that worked in Metamask Thai Chain:
Network Name: ThaiChain
Network URL: https://rpc.dome.cloud
Chain ID: 7
Currency Symbol: TCH
Block Explorer URL: https://thaichain.io

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2966

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
So take the example of ThaiChain (chainId = 7), it sends this payload:

```
{"id":51530,"object":{"chainType":"ETH","chainId":"0x7","rpcUrls":["https:\/\/rpc.dome.cloud"],"blockExplorerUrls":["https:\/\/thaichain.io"],"chainName":"ThaiChain","nativeCurrency":{"name":"ThaiChain Ether","decimals":18,"symbol":"TCH"}},"name":"walletAddEthereumChain"}
```

(We can log it by looking at `jsonString` in `DappAction.fromMessage(_:)`).

So we can't figure out the blockchain explorer endpoint URL in the payload for the key `blockExplorerUrls`.

If this is the problem, then I think we should just show the user an error that the blockchain explorer URL is invalid, similar to the error we show with, but with a different error message and not allow them to proceed:

```
return Promise(error: AddCustomChainError.others(R.string.localizable.addCustomChainErrorNoBlockchainExplorerUrl()))
```

I think this would be better than adding adding the URL and then failing silently when fetching transaction history. We probably should, in the future, support cases where there is no blockchain explorer better, than we can improve this by just confirming with the user to add it without a blockchain explorer.

What do you think?

PS: Googling suggests it should be https://exp.tch.in.th/home, but I can't form the correct endpoint from that too. We can't fix this manually anyway.

**Comment by vladyslav-iosdev** [comment]
i guess if case when we can't resolve explorer url, then yes, we could show to user warning message, "Explorer URL wasn't resolved. You willn't see transactions." or something like that. And continue without explorer url. anyway as i understand user can edit it later, right?

**Comment by hboon** [comment]
Makes sense. But can you check if we have implemented edits yet? :) I don't think we have.

**Comment by vladyslav-iosdev** [comment]
> Makes sense. But can you check if we have implemented edits yet? :) I don't think we have.
> 
> We can swipe to remove custom chains though.

ah, seems like we can't edit or delate it for now.

**Comment by hboon** [comment]
Yeah. Also to check it is consistent for chains added manually and via EIP3085. After this, we ought to ping Tomek so we set up edits. It's also not clear in the list of chains which chain can be deleted/edited (i.e. not built-into the app).

**Comment by vladyslav-iosdev** [comment]
in current PR it works in the next way: when we are not able to resolve url from `checkBlockchainExplorerApiHostname` method we return instance without url right in 
`
.recover { _ -> Guarantee<(customChain: WalletAddEthereumChainObject, chainId: Int, rpcUrl: String)> in
            return .value((customChain: customChain, chainId: chainId, rpcUrl: rpcUrl))
        }
` 
do i need to update it with throwing an error? for now

**Comment by vladyslav-iosdev** [comment]
> Yeah. Also to check it is consistent for chains added manually and via EIP3085. After this, we ought to ping Tomek so we set up edits. It's also not clear in the list of chains which chain can be deleted/edited (i.e. not built-into the app).

ok, i see.

**Comment by hboon** [comment]
For now, either:

A. throw an error so a message is displayed and user can't add it and
B. show them the message like in (A) and let them proceed anyway

**Comment by hboon** [comment]
And then create an issue so we figure out editing, etc: https://github.com/AlphaWallet/alpha-wallet-ios/pull/3209#issuecomment-926391018

**Comment by vladyslav-iosdev** [comment]
Maybe tweak warning massage is needed, not sure about it;)

**Review by hboon — APPROVED** [review]
Looks great. How about this message:

> Blockchain explorer URL can't be resolved. Would you like to continue without it? Transaction history will not be fetched

Feel free to merge.

**Comment by vladyslav-iosdev** [comment]
> Blockchain explorer URL can't be resolved. Would you like to continue without it? Transaction history will not be fetched

awesome! will update with it.

**Pull request merged**
