### PR TITLE
Not displaying crypto rate for xDai #4183

### LINKED ISSUE #4183: Not displaying crypto rate for xDai

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4183

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Can you describe why it doesn't work, and how it's fixed?

Also reword the commit message to include "Fix:" :

> Fix: Not displaying crypto rate for xDai #4183 #4184

**Comment by oa-s** [comment]
Before PR:
Screenshot 2022-03-30 at 08 07 03

After PR:
Screenshot 2022-03-29 at 16 09 53

**Comment by oa-s** [comment]
`CoinTickersFetcher` isn't able to resolve coin rate for native coin for **gnosis** (**xdai**) 
xdai has symbol `xDai` and resolved ticker has rate for ticker `gno`

**Comment by hboon** [comment]
Ah. I see. Thanks.

**Review by hboon — APPROVED** [review]
Merge after you tweak the commit message

**Comment by hboon** [comment]
> `CoinTickersFetcher` isn't able to resolve coin rate for native coin for **gnosis** (**xdai**)
> xdai has symbol `xDai` and resolved ticker has rate for ticker `gno`

Buzz @JamesSmartCell in case this affects Android

**Pull request merged**
