### PR TITLE
Fix: ERC721 token detection and fetch balance

### PR DESCRIPTION
**Pull request by hboon**
This PR will:

* Detect correctly that a non-CryptoKitties ERC721 token is actually ERC721
* Fetch balance of ERC721 tokens correctly (when autodetecting or adding a custom token)

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon I understand that you can reliably get the token balance but how does it handle getting the token ids for transferring etc?

**Comment by hboon** [comment]
@James-Sangalli we can't. This PR only gets the balance as a single number, 8 tokens (not even the token index). We still have to use OpenSea to get the balance (as in tokenID). But this means that if a contract implements ERC721 correctly, even if it's not in OpenSea, we will display them as an un-bundled list of "x1 Tokens" in the app.

**Comment by James-Sangalli** [comment]
@hboon but then we need to blank out the transfer button?

**Comment by hboon** [comment]
@James-Sangalli good for review. Have made it so it only enables the transfer button for ERC721 tokens if it's CryptoKitties.

**Pull request merged**
