### PR TITLE
Switch wallet Connect v2 to develop branch #4333

### LINKED ISSUE #4333: Switch wallet Connect v2 to develop branch
Develop branch contains crash fix

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4333

### CODE REVIEW

**Comment by oa-s** [comment]
Not able to test, example app returns invalid connection url

**Comment by hboon** [comment]
@oa-s it's also possible they broke or modified their example though, so might need to check with them.

**Comment by oa-s** [comment]
i was able to reproduce it when you have connected v2 session, on apps launch it causes crash `Bad Access`
Thiss PR fixes the issue https://github.com/WalletConnect/WalletConnectSwiftV2/issues/156

**Comment by oa-s** [comment]
> @oa-s it's also possible they broke or modified their example though, so might need to check with them.

yep, there missing some parts of url, i will create issue.

**Comment by hboon** [comment]
Ok, do you want to merge first?

**Comment by oa-s** [comment]
Will do it later after testing

**Comment by oa-s** [comment]
@hboon I found that we can manually download walletConnect v2 (its 0.5.0). (even for **spm**) change it locally and add to the proj. And later update code base when a new release will be available.

**Comment by hboon** [comment]
Ok sure

**Pull request closed without merging**
