### PR TITLE
remove dependency from resources #5234

### LINKED ISSUE #5234: Make a build so that the artifacts (jars for Android, frameworks for iOS) and their dependencies can be included in another project
* We can keep the UI, but not spin it up
* Make a dummy function in the code that signs a message
* Create a new skeleton driver project that uses this AlphaWallet project that includes something like this pseudocode:

```
import SDK
let wallet = SDK.Wallet("hardcoded seed phrase")
let result = wallet.signPersonal("some message")
let address = SDK.ecrecover(result)
print(wallet.address == address)
```

Goals
---
- [ ] Check feasibility
- [ ] Check constraints (including usage of dependencies, operating system requirements, build options)

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5234

### CODE REVIEW

**Comment by hboon** [comment]
Looks like the files must be referred to multiple times in the project, according to Travis?

**Review by hboon — APPROVED** [review]
Merge when ready.

**Comment by oa-s** [comment]
> AlphaWalletFoundation

firstly it was `AlphaWallet` but we can't use this name as app extensions and tests can't resolve right link to the app, as app and pod has the same name.

**Comment by oa-s** [comment]
> Merge when ready.

will do that after making interface public, because without it there is over **5k** error

**Comment by oa-s** [comment]
also what about the name for lib? any suggestions, for now when there is no added files it couble be easier to change it. also we need to think about AlphaWallet core, maybe remove it or rename (which is preffered) or left as it is

**Comment by hboon** [comment]
> will do that after making interface public, because without it there is over 5k error

😆

**Comment by hboon** [comment]
> also what about the name for lib? any suggestions, for now when there is no added files it couble be easier to change it. also we need to think about AlphaWallet core, maybe remove it or rename (which is preffered) or left as it is

No idea at the moment. Don't worry about it. Use foundation first. Renaming files if we don't change the contents is still tracked in the history so only the project file will have some changes if/when we rename the pod.

**Pull request merged**
