### PR TITLE
Group internal transactions in Activity tab

### LINKED ISSUE #2442: "Dumb" grouping of the transactions and events data we already have together in Activities tab

### PR DESCRIPTION
**Pull request by hboon**
Closes #2442

### CODE REVIEW

**Comment by hboon** [comment]
Needs to rebase and clean up

**Comment by hboon** [comment]
Force pushed after rebase master. @vladyslav-iosdev good for review again.

**Review by vladyslav-iosdev — APPROVED** [review]

**Comment by vladyslav-iosdev** [comment]
@hboon need to rebase

**Comment by hboon** [comment]
Thanks. Done.

**Pull request merged**
