### PR TITLE
Add logs for OpenSea fetches

### PR DESCRIPTION
**Pull request by hboon**

### CODE REVIEW

**Comment by eviltofu** [comment]
@hb how do I see the logs?

**Comment by hboon** [comment]
They appear in Xcode's console and Apple System Log (Console.app). Refer to https://github.com/AlphaWallet/alpha-wallet-ios/pull/3217#pullrequestreview-766497418 and newer for more information.

**Comment by eviltofu** [comment]
@hboon What address do you recommend I watch? I tried watching `nftmachine.eth` but that just crashes the app after a while. Nothing with `OpenSea` was every logged to the `Console.app` or the `Xcode` console.

**Comment by hboon** [comment]
@eviltofu trace the call for OpenSea.swift: https://github.com/AlphaWallet/alpha-wallet-ios/blob/a26abf3ed2169a4f784bf85af4c9d8f086143e96/AlphaWallet/EtherClient/OpenSea.swift#L133 and see why it isn't called.

Good to know a little about it anyway.

> What address do you recommend I watch? 

nftmachine.eth  / 0xaa9772d31476e85fedd1099e40dd2ff5dee214ff actually looks like a good one to test again. Decent number of transactions and many NFTs. So if it crashes with it, it's worth investigating.

**Comment by eviltofu** [comment]
@hboon
```
2022-01-27 14:14:29.119808+0800 AlphaWallet[1647:89429] Task <58FA4D31-A826-461C-BF3D-C9F75C79FB7C>.<3> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x126335130 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <58FA4D31-A826-461C-BF3D-C9F75C79FB7C>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <58FA4D31-A826-461C-BF3D-C9F75C79FB7C>.<3>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://polygon-mainnet.infura.io/v3/da3717f25f824cc1baa32d812386d93f, NSErrorFailingURLKey=https://polygon-mainnet.infura.io/v3/da3717f25f824cc1baa32d812386d93f, _kCFStreamErrorDomainKey=4}
2022-01-27 14:14:29.121981+0800 AlphaWallet[1647:89429] Task <8F23B20A-694C-49B8-9378-F6D794772A59>.<5> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x126327be0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8F23B20A-694C-49B8-9378-F6D794772A59>.<5>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <8F23B20A-694C-49B8-9378-F6D794772A59>.<5>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://rpc.xdaichain.com/, NSErrorFailingURLKey=https://rpc.xdaichain.com/, _kCFStreamErrorDomainKey=4}
▿ [Request]: GET https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0
[Request Body]: 
None
[Response]: nil
[Response Body]: 

[Result]: FAILURE
[Timeline]: Timeline: { "Request Start Time": 664956505.674, "Initial Response Time": 664956739.798, "Request Completed Time": 664956739.798, "Serialization Completed Time": 664956750.080, "Latency": 234.124 secs, "Request Duration": 234.124 secs, "Serialization Duration": 10.282 secs, "Total Duration": 244.406 secs }
  ▿ request : Optional<URLRequest>
    ▿ some : https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0
      ▿ url : Optional<URL>
        ▿ some : https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0
          - _url : https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0
      - cachePolicy : 0
      - timeoutInterval : 60.0
      - mainDocumentURL : nil
      - networkServiceType : __C.NSURLRequestNetworkServiceType
      - allowsCellularAccess : true
      ▿ httpMethod : Optional<String>
        - some : "GET"
      ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
        ▿ some : 1 element
          ▿ 0 : 2 elements
            - key : "X-API-KEY"
            - value : "11ba1b4f0c4246aeb07b1f8e5a20525f"
      - httpBody : nil
      - httpBodyStream : nil
      - httpShouldHandleCookies : true
      - httpShouldUsePipelining : false
  - response : nil
  ▿ data : Optional<Data>
    ▿ some : 0 bytes
      - count : 0
      ▿ pointer : 0x00000001708646b0
        - pointerValue : 6182815408
      - bytes : 0 elements
  ▿ result : FAILURE: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x11ee27730 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <AAB26328-B3C2-497A-A70C-4392695A1C58>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <AAB26328-B3C2-497A-A70C-4392695A1C58>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0, NSErrorFailingURLKey=https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0, _kCFStreamErrorDomainKey=4}
    - failure : Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x11ee27730 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <AAB26328-B3C2-497A-A70C-4392695A1C58>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <AAB26328-B3C2-497A-A70C-4392695A1C58>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0, NSErrorFailingURLKey=https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0, _kCFStreamErrorDomainKey=4}
  ▿ timeline : Timeline: { "Request Start Time": 664956505.674, "Initial Response Time": 664956739.798, "Request Completed Time": 664956739.798, "Serialization Completed Time": 664956750.080, "Latency": 234.124 secs, "Request Duration": 234.124 secs, "Serialization Duration": 10.282 secs, "Total Duration": 244.406 secs }
    - requestStartTime : 664956505.673971
    - initialResponseTime : 664956739.797847
    - requestCompletedTime : 664956739.797847
    - serializationCompletedTime : 664956750.080323
    - latency : 234.12387597560883
    - requestDuration : 234.12387597560883
    - serializationDuration : 10.28247594833374
    - totalDuration : 244.40635192394257
  ▿ _metrics : Optional<AnyObject>
    - some : (Task Interval) <_NSConcreteDateInterval: 0x1264e0fc0> (Start Date) 2022-01-27 06:08:25 +0000 + (Duration) 98.394740 seconds = (End Date) 2022-01-27 06:10:04 +0000
(Redirect Count) 0
(Transaction Metrics) (Request) <NSMutableURLRequest: 0x11eb5a060> { URL: https://api.opensea.io/api/v1/assets/?owner=0x8EC934DFf9943dE4b7312eDB67bB16f204528145&order_by=pk&order_direction=asc&limit=50&offset=0 }
(Response) (null)
(Fetch Start) 2022-01-27 06:08:25 +0000
(Domain Lookup Start) (null)
(Domain Lookup End) (null)
(Connect Start) (null)
(Secure Connection Start) (null)
(Secure Connection End) (null)
(Connect End) (null)
(Request Start) (null)
(Request End) (null)
(Response Start) (null)
(Response End) (null)
(Protocol Name) (null)
(Proxy Connection) NO
(Reused Connection) NO
(Fetch Type) Network Load
(Request Header Bytes) 0
(Request Body Transfer Bytes) 0
(Request Body Bytes) 0
(Response Header Bytes) 0
(Response Body Transfer Bytes) 0
(Response Body Bytes) 0
(Local Address) (null)
(Local Port) (null)
(Remote Address) (null)
(Remote Port) (null)
(TLS Protocol Version) 0x0000
(TLS Cipher Suite) 0x0000
(Cellular) NO
(Expensive) NO
(Constrained) NO
(Multipath) NO
```

**Comment by eviltofu** [comment]
@hboon 
```
    public func responseData(queue: DispatchQueue? = nil) -> Promise<(data: Data, response: PMKAlamofireDataResponse)> {
        return Promise { seal in
            responseData(queue: queue) { response in
                switch response.result {
                case .success(let value):
                    seal.fulfill((value, PMKAlamofireDataResponse(response)))
                case .failure(let error):
                    seal.reject(error)
                }
            }
        }
    }
```

I've traced the call to `responseData(queue: queue) { response in` but the promise appears to never be fulfilled.

**Comment by eviltofu** [comment]
Ok, I'm not seeing any OpenSea logs... @hboon

**Comment by hboon** [comment]
0x8EC934DFf9943dE4b7312eDB67bB16f204528145 doesn't seem to have any NFTs. But 0xaa9772d31476e85fedd1099e40dd2ff5dee214ff does. Seems like the API key is rate limited. Try waiting a bit? You can curl to verify (when the API key works). If it's throttled, can you make sure the code logs it, if it doesn't already?

**Comment by hboon** [comment]
@eviltofu anything else you need for this one? If you get to this, but somehow aren't seeing the logs, you can still approve the PR since it's not related and if you think it doesn't break anything (functionality and repo style).

**Comment by hboon** [comment]
Force pushed after rebase master.

**Pull request merged**
