### PR TITLE
Tweak how result of resolving ENS name (-> address) in Send screen is displayed

### PR DESCRIPTION
**Pull request by hboon**
Before PR|After PR
-|-
|

### CODE REVIEW

**Comment by tomekalphawallet** [comment]
> Personally don't think this is an improvement, what do you think @tomekalphawallet?

Hmmm... why?

In the future, we will have to find a space for "Address Book"
When validating, you usually look at the last 4 characters. 

Screenshot 2020-06-23 10 59 18

**Comment by James-Sangalli** [comment]
> > Personally don't think this is an improvement, what do you think @tomekalphawallet?
> 
> Hmmm... why?
> 
> In the future, we will have to find a space for "Address Book"
> When validating, you usually look at the last 4 characters.
> 
> Screenshot 2020-06-23 10 59 18

@tomekalphawallet from my perspective I find it unsettling not to see the whole address... I may have a bias there however

**Comment by hboon** [comment]
@James-Sangalli I'll rebase and push again

**Comment by hboon** [comment]
> rebase

@James-Sangalli done. Would you do a quick check again because `master` had changed quite a bit.

**Comment by tomekalphawallet** [comment]
> > > Personally don't think this is an improvement, what do you think @tomekalphawallet?
> > 
> > 
> > Hmmm... why?
> > In the future, we will have to find a space for "Address Book"
> > When validating, you usually look at the last 4 characters.
> > Screenshot 2020-06-23 10 59 18
> 
> @tomekalphawallet from my perspective I find it unsettling not to see the whole address... I may have a bias there however

If that would be a case, maybe on tap you can view the whole address. 

Screenshot 2020-06-24 10 33 19

**Pull request merged**
