### PR TITLE
Tweak slippage value selection for swap #5201

### LINKED ISSUE #5201: Tweak slippage value selection for swap
1. Update slippage value selection, add ranging with max available value 1. 
2. update selection titles: 10%, 50%, 100%

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5201

### CODE REVIEW

**Review by hboon — APPROVED** [review]
- [ ] Needs a bit more space for the label "Custom". Maybe the rightmost textbox can be narrower?

Screenshot 2022-08-23 at 11 27 40 AM

- [x] The custom slippage value seems to be parsed or displayed wrongly

    1. Enter 10
    2. Close and open and it shows 0.1 (divided by 100 for percents?)
    3. Enter 0.32
    4. Close and open and it shows 0.0032

- [x] "SLIPPAGE CAUSED BY TRANSACTION DELAY" should be "SLIPPAGE TOLERANCE" (sorry didn't notice this earlier, maybe it was in the UI design?)

**Comment by oa-s** [comment]
Updated code with comments about, applied rounding for editable slippage text field, (as on design)

**Comment by hboon** [comment]
Feel free to merge if you are ready

**Comment by oa-s** [comment]
| Before PR | After PR |
| ------- | ------- |
| | |

**Pull request merged**
