### PR TITLE
Add dark mode to TransactionConfirmationViewController

### PR DESCRIPTION
**Pull request by eviltofu**
Before PR | Light mode | Dark mode
-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 15 42 01 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 15 39 47 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 15 39 50 copy 2

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
The `Recipient` expanded row needs a bit of tweaking, the text colors are not good. Try send to "hweeboon.eth" and you'll see it.
 
Screenshot 2022-10-07 at 4 50 06 PM

Also the custom gas/nonce screen (that edit beside Speed/gas), but maybe that can be a separate PR?

Screenshot 2022-10-07 at 4 50 29 PM

**Comment by eviltofu** [comment]
> The `Recipient` expanded row needs a bit of tweaking, the text colors are not good. Try send to "hweeboon.eth" and you'll see it.
> 
> Screenshot 2022-10-07 at 4 50 06 PM
> 
> Also the custom gas/nonce screen (that edit beside Speed/gas), but maybe that can be a separate PR?
> 
> Screenshot 2022-10-07 at 4 50 29 PM

The gas screen is another PR.

**Comment by eviltofu** [comment]
Light mode | Dark mode
-|- 
Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 18 30 00 copy | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 18 30 02 copy

**Comment by eviltofu** [comment]
On hold as AmountTextField conflict is hard to resolve. Have to figure out what changed and put my fixes back in.

**Comment by eviltofu** [comment]
@hboon updated

**Comment by hboon** [comment]
@eviltofu remember to not include the commit for `UIUserInterfaceStyle` in PRs and/or add the "WIP/Don't merge" or make it a draft. Otherwise it's too easy merge it in accidentally.

**Comment by hboon** [comment]
Force pushed after rebase master

**Pull request merged**
