### PR TITLE
add ARTIS network https://artis.eco (untested)

### PR DESCRIPTION
**Pull request by PeterTheOne**
Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
slip0044: [246529](https://github.com/satoshilabs/slips/pull/495) (sigma1) & [246785](https://github.com/satoshilabs/slips/pull/495) (tau1)
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1)

This code ist untested..

RPCServers.swift may be incomplete: priceID, blockChainName, was not sure how to set these.

( Android: https://github.com/AlphaWallet/alpha-wallet-android/pull/803 )

### CODE REVIEW

**Comment by hboon** [comment]
Thank your for contributing @PeterTheOne. This looks like it may need some changes and some testing. Before we risk more of your time on working it out technically, can you help us understand what this PR is about and why it would be good to have?

**Comment by PeterTheOne** [comment]
@hboon I want to add the ARTIS network as another network to choose from.

**Comment by hboon** [comment]
> > Thank you for contributing @PeterTheOne. This looks like it may need some changes and some testing. Before we risk more of your time on working it out technically, can you help us understand what this PR is about and why it would be good to have?

> @hboon I want to add the ARTIS network as another network to choose from.

@zhangzhongnan928 @James-Sangalli can you decide if this is viable for us?

**Comment by hboon** [comment]
> @hboon I want to add the ARTIS network as another network to choose from. I want users to have easy option to use the ARTIS network and users of ARTIS to have a great wallet on iOS. ARTIS is a network that is close to the technology stack of the POA network which is already in use.

@PeterTheOne Ok, thanks. Please go ahead :)

Let us know if you need any help. When you are ready for review, would you help run `git rebase master` on your branch and pushing again?

**Comment by James-Sangalli** [comment]
@PeterTheOne the network label is not present in the enabled networks list

**Comment by PeterTheOne** [comment]
@James-Sangalli Where is this enabled networks list? (or did I already get it now?)

I'll do a `git rebase master` once testing passes.

**Comment by PeterTheOne** [comment]
so, I rebased and squashed my commits.

**Comment by hboon** [comment]
Bump @James-Sangalli

**Comment by James-Sangalli** [comment]
Reviewing now

**Comment by James-Sangalli** [comment]
@PeterTheOne looks good but please add "ARTIS blockchain" to the localisation strings and assign it in the case here (in RPCServers.swift):

`var blockChainName: String {
        switch self {
        case .xDai:
            return R.string.localizable.blockchainXDAI()
        case .main, .rinkeby, .ropsten, .custom, .callisto, .classic, .kovan, .sokol, .poa, .goerli, .artis_sigma1, .artis_tau1:
            return R.string.localizable.blockchainEthereum()
        }
    }`

So that it says ARTIS blockchain rather than Ethereum blockchain. After this please rebase your commits into one and I will be happy to merge it :) 

Don't forget to make posts about it to so your users know they can use AlphaWallet!

**Comment by PeterTheOne** [comment]
> Don't forget to make posts about it to so your users know they can use AlphaWallet!

Our communication team is on to it. :) Do you have a planned release date already?

**Pull request merged**
