### PR TITLE
Make Wallet tab table resize when keyboard is shown/hidden for searching #1989

### LINKED ISSUE #1989: Make Wallet tab table resize when keyboard is shown/hidden for searching

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1989

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon This PR depends on changes in #1993

**Comment by James-Sangalli** [comment]
@vladyslav-iosdev doesn't compile: 

> (66, 40) Use of unresolved identifier 'KeyboardChecker'

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev doesn't compile:
> 
> > (66, 40) Use of unresolved identifier 'KeyboardChecker'

it depends on https://github.com/AlphaWallet/alpha-wallet-ios/pull/1999, the same as #1990

**Comment by hboon** [comment]
@vladyslav-iosdev is this good for review?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev is this good for review?

yes

**Comment by hboon** [comment]
@James-Sangalli you want to take a look?

**Comment by hboon** [comment]
@James-Sangalli bump

**Review by James-Sangalli — APPROVED** [review]
Tested working

**Pull request merged**
