### PR TITLE
Implement send screen design for native cryptocurrency and ERC20 #1162

### LINKED ISSUE #1162: Implement send screen design for native cryptocurrency and ERC20
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc4ced734c3d9725f640b3

* Main class: `SendViewController`
* Keep it as presented modally instead of push.
* Note that this is used for both ERC20s and native crypto (i.e. ETH and equivalent). ERC20s don't allow toggling to fiat/USD.

Out of scope:

* The lock and aw.app on the right of navigation bar
* "Address Book"

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1162

### CODE REVIEW

**Comment by hboon** [comment]
For Boon, later:

- [ ] `AmountTextField` should not always say "Done".
- [ ] `AmountTextField` should have a delegate function (like AddressTextField` to let client code decide what to do.
- [ ] `AddressTextField` should not always say "Next" in the keyboard

**Comment by vladyslav-iosdev** [comment]
> Looks good. Can you do this too:
> 
> * [x]  Make the amount first responder immediately when the screen is shown (new behavior)
> * [x]  Make tapping Next in the keyboard when focused in the address textfield hide the keyboard instead of making the amount textfield the first responder, i.e. Change the body of `SendViewController.shouldReturn(in:)`. Just keep the button as "Next", for now. (this is necessary because of the earlier PR where we switch the textboxes)
> * [x]  Hide `SelectCurrencyButton` (i.e the icon, "ETH" and little down arrow) when it's an ERC20 and not sending Ether (can't toggle when ERC20 and also because it shouldn't show "ETH") #1863

done

**Comment by hboon** [comment]
@vladyslav-iosdev thanks! Looks good. I made a bit of changes due to time constraints (would like to have a build out today). You can check the diff between the last forced push to see what was modified.

> hboon force-pushed the vladyslav-iosdev:#1162  branch from db71f44 to 474953e 1 minute ago

**Comment by hboon** [comment]
@James-Sangalli I reviewed the code already. I add some slight modifications. But would you help to double check these cases in the send screen works especially?

A.

1. Tap ETH card
2. enter amount
3. enter recipient
4. Title is: Send ETH
5. Tap Send and it shows the amount and recipient correctly

B. ETH -> ERC20 by EIP681

1. Tap ETH card
2. enter amount
3. enter recipient
4. Scan EIP681 link for ERC20
5. Check amount and recipient updated
6. Title updates to: Send <symbol>
7. Check fiat amount appears (maybe after a short while)
8. Tap Send and it shows the amount and recipient correctly

C. ERC20 -> ETH by EIP681

1. Tap ERC20 card
2. enter amount
3. enter recipient
4. Scan EIP681 link for ETH
5. Title updates to: Send ETH
6. Check amount and recipient updated
7. Check fiat amount does not appear
8. Tap Send and it shows the token, amount and recipient correctly

D. ETH -> ETH by EIP681

Repeat C, but tap ETH in (1)

E. ERC20 -> ERC20 by EIP681

Repeat B, but tap ERC20 in (1)


Save you the time to look it up: https://brunobar79.github.io/eip681-link-generator/

**Comment by James-Sangalli** [comment]
> @James-Sangalli I reviewed the code already. I add some slight modifications. But would you help to double check these cases in the send screen works especially?
> 
> A.
> 
> 1. Tap ETH card
> 2. enter amount
> 3. enter recipient
> 4. Title is: Send ETH
> 5. Tap Send and it shows the amount and recipient correctly
> 

@hboon this works fine

> B. ETH -> ERC20 by EIP681
> 
> 1. Tap ETH card
> 2. enter amount
> 3. enter recipient
> 4. Scan EIP681 link for ERC20
> 5. Check amount and recipient updated
> 6. Title updates to: Send
> 7. Check fiat amount appears (maybe after a short while)
> 8. Tap Send and it shows the amount and recipient correctly
> 

@hboon this does not work, stays the same

> C. ERC20 -> ETH by EIP681
> 
> 1. Tap ERC20 card
> 2. enter amount
> 3. enter recipient
> 4. Scan EIP681 link for ETH
> 5. Title updates to: Send ETH
> 6. Check amount and recipient updated
> 7. Check fiat amount does not appear
> 8. Tap Send and it shows the token, amount and recipient correctly
> 

@hboon this works fine

> D. ETH -> ETH by EIP681
> 
@hboon this works fine

> Repeat C, but tap ETH in (1)
> 

@hboon this works fine

> E. ERC20 -> ERC20 by EIP681
> 

@hboon this does not work

> Repeat B, but tap ERC20 in (1)
> 

@hboon this does not work, details stay the same

> Save you the time to look it up: https://brunobar79.github.io/eip681-link-generator/

@hboon cheers!

**Comment by hboon** [comment]
Added #1874

**Comment by James-Sangalli** [comment]
@vladyslav-iosdev feel free to use the main repo instead of forking

**Pull request merged**
