### PR TITLE
Display traits for NFTs (ERC721 and ERC1155) retrieved from OpenSea #3741

### LINKED ISSUE #3741: Display traits for NFTs (ERC721 and ERC1155) retrieved from OpenSea
We used to display them for ERC721s like CryptoKitties before we aligned the UI for ERC721 with 1155's.

Let's show them again.

Buzz @colourfreak if we need design help.

This screen, for individual token IDs:

Screenshot 2022-01-18 at 12 29 48 PM

Sample, in the OpenSea API output:

```
"traits" : [
   {
      "display_type" : null,
      "max_value" : null,
      "order" : null,
      "trait_count" : 34,
      "trait_type" : "Affinity",
      "value" : "Earth II, Fire I"
   },
   {
      "display_type" : null,
      "max_value" : null,
      "order" : null,
      "trait_count" : 18,
      "trait_type" : "Slabs",
      "value" : "â¢ â¢ â¢ â¢"
   },
   //…
]
 ```

- [ ] Buzz Android too, in case it's missing?

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3741

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
- [ ] Right after importing a wallet and going to the Collectibles tab and waiting for a short while, the app shows this (a vertical gap). Not sure if it's because the data is already loaded and not filled yet or is it a layout issue:

Screenshot 2022-01-20 at 12 33 49 PM

- [ ] It looks OK after a while:

Screenshot 2022-01-20 at 12 35 17 PM

- [ ] But when I scroll down a few rows, I see this:

Screenshot 2022-01-20 at 12 35 37 PM

- [ ] Sometimes an empty "Attributes" header show up. Could we remove those when it's empty? :

Screenshot 2022-01-20 at 12 36 46 PM

Sometimes it's OK (i.e the "Attributes" header don't show up when there are none) Maybe different NFTs? :

Screenshot 2022-01-20 at 12 36 53 PM

- [ ] The last row of attributes is sometimes clipped (maybe different NFTs, maybe depends on number of rows?) :

Screenshot 2022-01-20 at 12 37 23 PM

- [ ] This might be unrelated to this GitHub issue/PR, but could we make list (collection view too) cover all the way to the bottom of the screen with safe area margins to handle the virtual home button?

Screenshot 2022-01-20 at 12 37 53 PM

- [ ] There seems to be many changes that are unrelated to the original issue. Would you help to separate them out into a separate PR?

**Comment by hboon** [comment]
@oa-s this good for review?

**Comment by oa-s** [comment]
> @oa-s this good for review?

not yet

**Review by hboon — APPROVED** [review]
>  Sometimes an empty "Attributes" header show up. Could we remove those when it's empty? :

Looks good. But still seeing "Attributes" appearing with no attribute pairs for "The Holy Fool 172" (screenshot in earlier comment). Can we fix that?

Merge when you are ready

**Comment by oa-s** [comment]
> > Sometimes an empty "Attributes" header show up. Could we remove those when it's empty? :
> 
> Looks good. But still seeing "Attributes" appearing with no attribute pairs for "The Holy Fool 172" (screenshot in earlier comment). Can we fix that?
> 
> Merge when you are ready

thanks a lot, missed to update it for erc1155

**Pull request merged**
