### PR TITLE
[WalletConnect] Improve WalletConnect user experience by automatically switch back to previous app (if iOS has detected one) after WalletConnect actions

### PR DESCRIPTION
**Pull request by hboon**
A. WalletConnect session approval
B. WalletConnect session rejection
C. WalletConnect signing

This is for this scenario:

1. User access dapp in Safari iOS
2. Taps to use WalletConnect
3. Choose AlphaWallet
4. iOS switches to AlphaWallet
5. User approves session in AlphaWallet
6. This PR forces iOS to automatically switch back to the previous app. Before this PR, the user stays in AlphaWallet and might be lost

Similar if the user had rejected the session or sign messages/transactions during a session.

This wouldn't (shouldn't) happen when browsing using the dapp browser or any desktop browsers because there is (hopefully!) no previous app to go to.

Do not merge. Will try a submission to test it out

### CODE REVIEW

**Review by oa-s — APPROVED** [review]

**Comment by hboon** [comment]
Out as TestFlight v3.46 build 442

**Comment by hboon** [comment]
Should have made it a GitHub draft PR to be sure it's not merged. Just did it.

**Comment by hboon** [comment]
@oa-s App was approved with this functionality. Have rebased master for merging.

**Comment by hboon** [comment]
Force-pushed after rebase master

**Pull request merged**
