### PR TITLE
move importing to background queue, to avoid ui stucking #6204

### LINKED ISSUE #6091: Import "Keystore JSON" in "Import Wallet" tab should show an indicator that it's doing something
1. Import Wallet
2. Keystore JSON
3. Paste a JSON
4. Enter a password
5. Tap Import

Expected
---
6. Show an "Importing…" indicator

Observed
---
6. App appears to hang
7. Shows success/failure after a while

### LINKED ISSUE #6204: Display loading indicator when importing a new wallet, the app stucks

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6204, Closes #6091

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Will come back and check this again since it involves key management.

In catch-up mode now. When I'm not rushed :)

**Review by hboon — CHANGES_REQUESTED** [review]
Importing a keystore JSON with the wrong password crashes with:

```
2023-01-25 15:03:54.646903+0800 AlphaWallet[71913:949817] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'MBProgressHUD needs to be accessed on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018040e7c8 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051144 objc_exception_throw + 56
	2   Foundation                          0x0000000180b13b98 _userInfoForFileAndLine + 0
	3   MBProgressHUD                       0x00000001052144dc -[MBProgressHUD hideAnimated:] + 120
	4   MBProgressHUD                       0x0000000105213ac8 +[MBProgressHUD hideHUDForView:animated:] + 144
	5   AlphaWallet                         0x0000000102d51cf4 $sSo16UIViewControllerC11AlphaWalletE11hideLoading8animatedySb_tF + 272
	6   AlphaWallet                         0x0000000102e7a8a4 $s11AlphaWallet06ImportB14ViewControllerC06importB0yyFy7Combine11SubscribersO10CompletionOy_0aB10Foundation13KeystoreErrorOGcfU0_ + 68
	7   Combine                             0x000000019baa2a70 $s7Combine11SubscribersO4SinkC7receive10completionyAC10CompletionOy_q_G_tF + 364
	8   Combine                             0x000000019baa2f28 $s7Combine11SubscribersO4SinkCy_xq_GAA10SubscriberA2aGP7receive10completionyAC10CompletionOy_7FailureQzG_tFTW + 20
	9   Combine                             0x000000019bb541cc $s7Combine10PublishersO7FlatMapV5Outer33_E91C3F00A6DFAAFEA2009FAF507AE039LLC7receive10completionyAA11SubscribersO10CompletionOy_7FailureQzG_tF + 1516
	10  Combine                             0x000000019bb55328 $s7Combine10PublishersO7FlatMapV5Outer33_E91C3F00A6DFAAFEA2009FAF507AE039LLCy_xq__qd__GAA10SubscriberA2aJP7receive10completionyAA11SubscribersO10CompletionOy_7FailureQzG_tFTW + 20
	11  Combine                             0x000000019ba92a58 $s7Combine10PublishersO11SubscribeOnV5Inner33_A96F1007E71D689A6E205AEC35F016EBLLC7receive10completionyAA11SubscribersO10CompletionOy_7FailureQzG_tF + 216
	12  Combine                             0x000000019ba92ac4 $s7Combine10PublishersO11SubscribeOnV5Inner33_A96F1007E71D689A6E205AEC35F016EBLLCy_xq__qd__GAA10SubscriberA2aJP7receive10completionyAA11SubscribersO10CompletionOy_7FailureQzG_tFTW + 20
	13  CombineExt                          0x0000000105de061c $s10CombineExt12DemandBufferC5flush33_0B602ACEA720B7846AD42455D083F45BLL6adding0A011SubscribersO0C0VAKSg_tF + 2144
	14  CombineExt                          0x0000000105ddfdb0 $s10CombineExt12DemandBufferC6demandy0A011SubscribersO0C0VAIF + 52
	15  CombineExt                          0x0000000105ddb46c $s7Combine10PublishersO0A3ExtE6CreateV12Subscription33_A8EA4785FE21D12564CC2A00E73B4214LLC7requestyyAA11SubscribersO6DemandVF + 100
	16  CombineExt                          0x0000000105ddb634 $s7Combine10PublishersO0A3ExtE6CreateV12Subscription33_A8EA4785FE21D12564CC2A00E73B4214LLCy_xq__qd__GAagdaGP7requestyyAA11SubscribersO6DemandVFTW + 28
	17  Combine                             0x000000019ba92444 $s7Combine10PublishersO11SubscribeOnV5Inner33_A96F1007E71D689A6E205AEC35F016EBLLC7requestyyAA11SubscribersO6DemandVFyycfU_ + 128
	18  Combine                             0x000000019ba93c50 $s7Combine10PublishersO11SubscribeOnV5Inner33_A96F1007E71D689A6E205AEC35F016EBLLC7requestyyAA11SubscribersO6DemandVFyycfU_TA + 44
	19  libswiftDispatch.dylib              0x00000001a1a97cd4 $sIeg_IeyB_TR + 28
	20  libdispatch.dylib                   0x0000000180133fa4 _dispatch_call_block_and_release + 24
	21  libdispatch.dylib                   0x0000000180135768 _dispatch_client_callout + 16
	22  libdispatch.dylib                   0x000000018013d7f8 _dispatch_lane_serial_drain + 780
	23  libdispatch.dylib                   0x000000018013e43c _dispatch_lane_invoke + 392
	24  libdispatch.dylib                   0x000000018014a624 _dispatch_workloop_worker_thread + 772
	25  libsystem_pthread.dylib             0x00000001b059a8fc _pthread_wqthread + 284
	26  libsystem_pthread.dylib             0x00000001b05996c0 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException
2023-01-25 15:03:54.853807+0800 AlphaWallet[71913:948243] [TrackApiCalls] (sub)domains accessed: 10. Calls for each (sub)domain: [(key: "goerli.infura.io", value: 128), (key: "repo.tokenscript.org", value: 31), (key: "api-goerli.etherscan.io", value: 29), (key: "api.coingecko.com", value: 17), (key: "mainnet.infura.io", value: 5), (key: "li.quest", value: 4), (key: "resolve.unstoppabledomains.com", value: 4), (key: "firebaselogging-pa.googleapis.com", value: 2), (key: "api-instant.ramp.network", value: 2), (key: "api.1inch.exchange", value: 2)] from: start()

Process finished with exit code 0
```

Seems to work if the password is correct. Can you add a commit instead of modifying the existing one for this PR? Easier to review.

**Comment by hboon** [comment]
Buzz to check #6213 after this is reviewed and merged?

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — APPROVED** [review]
I only checked against the last few comments I made. Hope you didn't change it too much from since the review…

**Pull request merged**
