### PR TITLE
add candle

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by hboon** [comment]
@samisbakedham hi! Could you describe what this PR is for? I have a feeling it's sent to the wrong repo :)

**Comment by samisbakedham** [comment]
> @samisbakedham hi! Could you describe what this PR is for? I have a feeling it's sent to the wrong repo :)

Hi, to add support for Candle chain on Alpha wallet. It's still a WIP!

**Comment by hboon** [comment]
> > @samisbakedham hi! Could you describe what this PR is for? I have a feeling it's sent to the wrong repo :)
> 
> Hi, to add support for Candle chain on Alpha wallet. It's still a WIP!

OK. In that case, you probably don't want to change things like https://github.com/AlphaWallet/alpha-wallet-ios/pull/4629/commits/01f27c1bd8ec767d7c1832b4f19ba59a46655f2f

**Comment by samisbakedham** [comment]
> > > @samisbakedham hi! Could you describe what this PR is for? I have a feeling it's sent to the wrong repo :)
> > 
> > 
> > Hi, to add support for Candle chain on Alpha wallet. It's still a WIP!
> 
> OK. In that case, you probably don't want to change things like [01f27c1](https://github.com/AlphaWallet/alpha-wallet-ios/commit/01f27c1bd8ec767d7c1832b4f19ba59a46655f2f)

Agreed. I'll fix

**Comment by samisbakedham** [comment]
> > > @samisbakedham hi! Could you describe what this PR is for? I have a feeling it's sent to the wrong repo :)
> > 
> > 
> > Hi, to add support for Candle chain on Alpha wallet. It's still a WIP!
> 
> OK. In that case, you probably don't want to change things like [01f27c1](https://github.com/AlphaWallet/alpha-wallet-ios/commit/01f27c1bd8ec767d7c1832b4f19ba59a46655f2f)

See #4853

**Comment by hboon** [comment]
Supersded by #4991

**Pull request closed without merging**
