### PR TITLE
Add Support for Candle Network

### PR DESCRIPTION
**Pull request by samisbakedham**
If not a bug:
Closes #4629 

1-liner summary:
Adds another supported network to Alpha Wallet, Candle. 
Details:
Candle is an evm-compatible chain built using polygon's "EDGE" technology. 

Anything particular to test:
Functionality of the new chain.

### CODE REVIEW

**Comment by samisbakedham** [comment]
@hboon @oa-s

**Comment by samisbakedham** [comment]
@hboon good to go?

**Comment by hboon** [comment]
@samisbakedham do you think you can help `rebase master` and make sure it is just 1 commit on top of `master`? That way we can look at what are the changes. Thanks.

**Comment by samisbakedham** [comment]
> @samisbakedham do you think you can help `rebase master` and make sure it is just 1 commit on top of `master`? That way we can look at what are the changes. Thanks.

Yes thank you

**Comment by samisbakedham** [comment]
> @samisbakedham do you think you can help `rebase master` and make sure it is just 1 commit on top of `master`? That way we can look at what are the changes. Thanks.

@hboon Done

**Comment by hboon** [comment]
>> do you think you can help rebase master and make sure it is just 1 commit on top of master? That way we can look at what are the changes.

Thanks, but I mean like this:

```
git fetch upstream master:master #assumes `upstream` points to github.com/AlphaWallet/alpha-wallet-ios. Makes local repo's master updated
git rebase master #rebases current branch on top of `master`, i.e. make all the commits be applied onto of `master`
```

After that, there should be no merge commits, i.e. commits like this should be gone:

> Merge branch 'AlphaWallet:master' into master

**Comment by samisbakedham** [comment]
> >> do you think you can help rebase master and make sure it is just 1 commit on top of master? That way we can look at what are the changes.
> 
> 
> 
> Thanks, but I mean like this:
> 
> 
> 
> ```
> 
> git fetch upstream master:master #assumes `upstream` points to github.com/AlphaWallet/alpha-wallet-ios. Makes local repo's master updated
> 
> git rebase master #rebases current branch on top of `master`, i.e. make all the commits be applied onto of `master`
> 
> ```
> 
> 
> 
> After that, there should be no merge commits, i.e. commits like this should be gone:
> 
> 
> 
> > Merge branch 'AlphaWallet:master' into master

Done

**Comment by hboon** [comment]
Screenshot 2022-07-13 at 11 54 27 AM

Thanks. Unfortunately, they are still there. Refer to the screenshot:

* There are 13 commits. It should be exactly 1
* And among those commits, there are commits with the message "Merge branch 'master' into master". Those shouldn't be there too

I just realised your branch is called `master` too which might be confusing, can you try this (best to back up your code first):

```
git fetch upstream master #assumes `upstream` points to github.com/AlphaWallet/alpha-wallet-ios. Makes local repo's `upstream/master` updated
git rebase upstream/master #rebases branch (which is `master`) on top of `upstream/master`, i.e. make all the commits be applied onto of `master`
git rebase -i upstream/master #This would open up an editor. You'd have to squash all the new commits you added into exactly 1
```

Once you verify there is exactly 1 commit above `upstream/master`:

```
git push origin master --force
```

Then you would see that this GitHub PR page will say "1" beside the Commits tab.

**Comment by samisbakedham** [comment]
> Screenshot 2022-07-13 at 11 54 27 AM
> 
> 
> 
> Thanks. Unfortunately, they are still there. Refer to the screenshot:
> 
> 
> 
> * There are 13 commits. It should be exactly 1
> 
> * And among those commits, there are commits with the message "Merge branch 'master' into master". Those shouldn't be there too
> 
> 
> 
> I just realised your branch is called `master` too which might be confusing, can you try this (best to back up your code first):
> 
> 
> 
> ```
> 
> git fetch upstream master #assumes `upstream` points to github.com/AlphaWallet/alpha-wallet-ios. Makes local repo's `upstream/master` updated
> 
> git rebase upstream/master #rebases branch (which is `master`) on top of `upstream/master`, i.e. make all the commits be applied onto of `master`
> 
> git rebase -i upstream/master #This would open up an editor. You'd have to squash all the new commits you added into exactly 1
> 
> ```
> 
> 
> 
> Once you verify there is exactly 1 commit above `upstream/master`:
> 
> 
> 
> ```
> 
> git push origin master --force
> 
> ```
> 
> 
> 
> Then you would see that this GitHub PR page will say "1" beside the Commits tab.

Will try now!

**Comment by hboon** [comment]
Supersded by #4991

**Pull request closed without merging**
