### PR TITLE
Tweak name/symbol display in Wallet #3182

### LINKED ISSUE #3182: Tweak name/symbol display in Wallet
Refer to https://github.com/AlphaWallet/alpha-wallet-android/issues/2000

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3182

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon BTW does it contradict with https://github.com/AlphaWallet/alpha-wallet-ios/issues/2830 ?

**Comment by hboon** [comment]
Yes, I think it supersedes #2830, so we can close that.

**Review by hboon — APPROVED** [review]
Merge when ready :)

**Review by hboon — APPROVED** [review]
Didn't check. Merge when ready.

**Comment by vladyslav-iosdev** [comment]
@hboon can u please check it, if it works ok. not pretty sure in implementation

**Comment by hboon** [comment]
Will do

**Review by hboon — APPROVED** [review]
Looks ok to me. Thanks!

**Pull request merged**
