### PR TITLE
Removed gray line under navigation bar of TokenInstanceViewController #3798

### LINKED ISSUE #3798: Removed gray line under navigation bar of TokenInstanceViewController

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3798

### CODE REVIEW

**Comment by eviltofu** [comment]
@oa-s Can you tell me where I go in the app to observe this?

**Comment by hboon** [comment]
Before and after screenshots :)

**Comment by oa-s** [comment]
| Before PR | After PR  |
| -------- | -------- |
|  | |

**Comment by eviltofu** [comment]
@oa-s How do I get to this screen? See #3813 for an example.

**Comment by hboon** [comment]
@eviltofu Like this:

Info and Activity sub-tabs, so it must be from tapping a token.

Displays "hweeboon.eth". So it's an ENS -> It's an ENS token

**Comment by eviltofu** [comment]
> @eviltofu Like this:
> 
> Info and Activity sub-tabs, so it must be from tapping a token.
> 
> Displays "hweeboon.eth". So it's an ENS -> It's an ENS token

@hboon What is you wallet address?

**Comment by hboon** [comment]
@eviltofu hweeboon.eth :)

**Review by eviltofu — APPROVED** [review]

**Comment by eviltofu** [comment]
@oa-s merge when ready

**Pull request merged**
