### PR TITLE
#3205 fix build and particularly signing with fastlane

### LINKED ISSUE #3205: Fix build (and particularly signing) with Fastlane
I was trying to do this a while back, but for some reason, signing just doesn't work for me.

PS: try not to upload. You should be able to fix it without uploading.

### PR DESCRIPTION
**Pull request by eviltofu**
closes #3205

1. Check the directory where the AlphaWallet.ipa is stored. If it is there, delete or move it.

2. Try to install the certs via:
```
output_path=~/path/to/store/certs FASTLANE_USER=xxx@yyy.zzz FASTLANE_PASSWORD=aaaaa bundle exec fastlane certs
```
where output_path is someplace you want to safely store the certs in your machine. Make sure the path exists.

3. Then try to sign
```
bundle exec fastlane testrelease
```

4. Then check the AlphaWallet directory to see if AlphaWallet.ipa is recreated. If the file exists, then signing works for you.

I will then re-enable all the other fastlane options and we can try once more. When that succeeds, I will enable the Build Phases in Xcode, squash the commits and pushed to merge. Then we are done.

@hboon

### CODE REVIEW

**Comment by hboon** [comment]
Run:

```
output_path=~/Users/hboon/Desktop/certs FASTLANE_USER=<email> FASTLANE_PASSWORD=<password> bundle exec fastlane certs
```

Says:

> [!] Could not find lane 'ios certs'. Available lanes: ios release, ios screenshots, ios travis_tests, ios tests, ios testrelease

Run:

```
bundle exec fastlane testrelease
```

Prints:

> [13:02:53]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet.AlphaWalletShare' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet.AlphaWalletShare'. (in target 'AlphaWalletShare' from project 'AlphaWallet')
> [13:02:53]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet.AlphaWalletSafariExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet.AlphaWalletSafariExtension'. (in target 'AlphaWalletSafariExtension' from project 'AlphaWallet')
> [13:02:53]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet'. (in target 'AlphaWallet' from project 'AlphaWallet')
> [13:02:53]: ▸ ** ARCHIVE FAILED **

**Comment by hboon** [comment]
Hang on. Maybe it's the wrong version.

**Comment by hboon** [comment]
@eviltofu 

Run:

```
output_path=/Users/hboon/Desktop/certs FASTLANE_USER=<email> FASTLANE_PASSWORD=<password> bundle exec fastlane certs
```

Files created:

> -rw-r--r--  1 hboon  staff  14891 May  4 13:15 AppStore_com.stormbird.alphawallet.mobileprovision
> -rw-r--r--  1 hboon  staff   1497 May  4 13:15 RLX67HH29J.cer


```
bundle exec fastlane testrelease
```

Prints:


> [13:16:35]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet.AlphaWalletShare' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet.AlphaWalletShare'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'AlphaWalletShare' from project 'AlphaWallet')
> [13:16:35]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet.AlphaWalletSafariExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet.AlphaWalletSafariExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'AlphaWalletSafariExtension' from project 'AlphaWallet')
> [13:16:35]: ▸ ** ARCHIVE FAILED **
> [13:16:35]: ▸ ❌  error: No profiles for 'com.stormbird.alphawallet' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.stormbird.alphawallet'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'AlphaWallet' from project 'AlphaWallet')

Maybe these 2 issues?

* Need 2 more profiles, for the 2 extensions
* It doesn't seem to locate the cert + app provisioning profile. Need to set the path?

**Comment by eviltofu** [comment]
```
export_options: {
    provisioningProfiles: { 
      "com.example.bundleid" => "Provisioning Profile Name",
      "com.example.bundleid2" => "Provisioning Profile Name 2"
    }
  }
```
Needs to be added but I'm not sure what "Provisioning Profile Name" looks like. Do you have any clue? @hboon

**Comment by eviltofu** [comment]
I've added the commands to check the certs in the test build release. Can you repeat `bundle exec fastlane testrelease`? @hboon

**Comment by hboon** [comment]
@eviltofu might have gotten somewhere with this. Will update later.

**Comment by hboon** [comment]
@eviltofu I pushed a commit 035e94cdd7d0e5382f01edcd7fb68f994c461d2a

I think I found the reason why automatic signing doesn't work for me. xcodebuild doesn't want `~/Library/MobileDevice/Provisioning Profiles` to be a softlink. Xcode (and xcodebuild) can generate the provisioning profiles perfectly and drop them into the soft-linked folder, but for some reason would not read from it.

I made a commit with changes which builds+archive and then exports to `.ipa` (at the project root) for me.

Can you verify it works for you too and help clean it up?

I removed the call `get_certificates` since we can assume the developer has manually set it up. I haven't tried to see how it would work if automated. Have enough of signing and fastlane :)

**Comment by eviltofu** [comment]
> @eviltofu I pushed a commit [035e94c](https://github.com/AlphaWallet/alpha-wallet-ios/commit/035e94cdd7d0e5382f01edcd7fb68f994c461d2a)
> 
> I think I found the reason why automatic signing doesn't work for me. xcodebuild doesn't want `~/Library/MobileDevice/Provisioning Profiles` to be a softlink. Xcode (and xcodebuild) can generate the provisioning profiles perfectly and drop them into the soft-linked folder, but for some reason would not read from it.
> 
> I made a commit with changes which builds+archive and then exports to `.ipa` (at the project root) for me.
> 
> Can you verify it works for you too and help clean it up?
> 
> I removed the call `get_certificates` since we can assume the developer has manually set it up. I haven't tried to see how it would work if automated. Have enough of signing and fastlane :)

This works for me. I'll add back in the rest of the code and we can try again. @hboon

**Comment by hboon** [comment]
Thanks. I forgot to say:

This isn't necessary:

```
bundle exec fastlane certs
```

This alone works and was enough to build, archive + export when I tested:

```
FASTLANE_USER=<email> FASTLANE_PASSWORD=<password> bundle exec fastlane testrelease
```

**Comment by hboon** [comment]
Not sure why `AlphaWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` is not in sync. Maybe we need this?

```
xcargs: "-disableAutomaticPackageResolution",
```

But leave out `commit_version_bump`. I just want us to fastlane build the tip as it is (not even checking if it's a specific branch or if there are unsaved changes. I will in fact add some uncommitted changes for building, like API keys) and without modifying the source code and/or commit. So it should just literally do:

1. Build + archive with the current files. Should not care if there are uncommitted changes or which branch this is on
2. Upload

Anything else like exporting, signing etc is just a means to get those 2 steps done.

**Comment by eviltofu** [comment]
Ok, removing commit_version_bump.

**Comment by hboon** [comment]
I added a commit b0430af301970a49ce2905c3cf46ce3b66a8381e which disables version changes and fixes things like the team_id used by deliver (apparently it's different from the one used by `build_app`; I have no idea why). I had to upgrade the fastlane check so `deliver` works.

Can you check again and then clean up and squash into a single commit and review again? Uploading would probably work, but let's merge this after clean up and I'll try it again when I do an actual upload to be sure.

**Comment by eviltofu** [comment]
I will test, then squish, and restore the build phases I took out that prevents the test lane from executing. Then push that branch up and it should be it for now.

**Comment by eviltofu** [comment]
ok done @hboon

**Comment by hboon** [comment]
Force pushed after rebase master. This is meant as a checkpoint. Going to modify the commit a little to remove unnecessary changes (like to the project file where the run phase check was removed and re-added with a different identifier)

**Review by hboon — APPROVED** [review]
@eviltofu I've force pushed again to:

* remove the unintended diffs mentioned above
* remove the commented out fastlane "processes" (like incrementing the version number)
* rename the lane to `testflight`

Would you merge if it looks OK for you (I've pushed a commit just before this from `git rebase master` so you can compare). I will test it again when I do a release.

**Comment by hboon** [comment]
Force pushed after rebasing master to merge.

**Pull request merged**
