### PR TITLE
Title of cell in Settings tab is sometimes clipped at the bottom when there is a subtitle #1896

### LINKED ISSUE #1896: Title of cell in Settings tab is sometimes clipped at the bottom when there is a subtitle
Note the descender of the "g" in the screenshot

Reproducible after applying #1892. Can be observed after tapping on "Change / Add Wallet" and tapping "Done" again.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Fixes #1896

### CODE REVIEW

**Comment by hboon** [comment]
Remember to git rebase master

**Comment by vladyslav-iosdev** [comment]
> Remember to git rebase master

@hboon , ok! tell me device you reproduce this issue.

**Comment by hboon** [comment]
@vladyslav-iosdev iOS 12.4 iPhone X simulator

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev iOS 12.4 iPhone X simulator

@hboon  its strange but, i can't reproduce this on. tried on Iphone X 12.4  also will try on other devices.

**Comment by hboon** [comment]
@vladyslav-iosdev if you can't reproduce it after a while, let me know and I'll try to figure it out.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev if you can't reproduce it after a while, let me know and I'll try to figure it out.

@hboon  I sent new commit, check it, maybe it could help.

**Comment by hboon** [comment]
@vladyslav-iosdev I pushed a commit. It was complaining about constraint violation. Removing the margin appears to help. Would you help to verify that it still works for you on a few devices and then squash the 2 commits?

There are a few other constraint violations, but we can ignore those for now.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev I pushed a commit. It was complaining about constraint violation. Removing the spacing appears to help. Would you help to verify that it still works for you on a few devices and then squash the 2 commits?
> 
> There are a few other constraint violations, but we can ignore those for now.
> 
> (and git rebase master)

@hboon  Done, seems like its working, tested on several devices.

**Pull request merged**
