### PR TITLE
Covalent integration #4194

### LINKED ISSUE #4194: Integrate Covalent, use it for Klaytn only
Refer to #4191

https://www.covalenthq.com/platform

Dev key for Covalent: ckey_654d4af07b6f403ba893516dd0c

Next:

- [ ] #4192 lower priority

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4194

### CODE REVIEW

**Comment by hboon** [comment]
- [ ] Sending transaction on testnet to the same address (0xbbc) shows this:

Screenshot 2022-04-04 at 10 01 37 AM

- [ ] With only Klaytn testnet enabled (and 0xbbc), Collectibles from Ethereum mainnet are showing up in both All and Collectibles tab:

Screenshot 2022-04-04 at 10 08 13 AM

- [ ] Activities is still empty for both 0x424d0C6eD9aDdc9e80E81dbfe6e26911e4a25c8c and 0xbbc

**Comment by oa-s** [comment]
> * [ ]  Sending transaction on testnet to the same address (0xbbc) shows this:
> * [ ]  With only Klaytn testnet enabled (and 0xbbc), Collectibles from Ethereum mainnet are showing up in both All and 

fixed in #4193

**Comment by oa-s** [comment]
Tested `0x424d0C6eD9aDdc9e80E81dbfe6e26911e4a25c8c` for mainnet, displays activities

**Comment by oa-s** [comment]
**Covalent** doesn't support `klaytnBaobab`

**Comment by hboon** [comment]
>> With only Klaytn testnet enabled (and 0xbbc), Collectibles from Ethereum mainnet are showing up in both All and

> Fixed in #4193

- [ ] I still see them. Should I remove the wallet and import again?

---

For wallet 0x424d0C6eD9aDdc9e80E81dbfe6e26911e4a25c8c on mainnet:

- [ ] 0xd809d910b7c4fdf6130b55d9b569fd748749dddc/SKMF should have balance=3 and tapping into it should show a collectible view (it's an ERC721)

- [ ] 0xb6fc2d963979a78fc7351695fcb829bc3c8b5b29/KPXMF should have a balance=7

**Comment by oa-s** [comment]
> * [ ]  I still see them. Should I remove the wallet and import again?

updated code should work

**Comment by oa-s** [comment]
Calling methods to rpc like: `balanceOf` doesn't work for klaytn, seems like balances should be fetched with **covalent api**

**Comment by hboon** [comment]
>@hboon  Calling methods to rpc like: `balanceOf` doesn't work for klaytn, seems like balances should be fetched with **covalent api**

@oa-s it works when I used web3.js, so it should work. I’ll send you when I get to my computer again later or tomorrow

**Comment by oa-s** [comment]
so we don't neet to use covalent for it?
https://www.covalenthq.com/docs/api/#/0/Get%20token%20balances%20for%20address/USD/8217

**Comment by hboon** [comment]
Should not. The JSON/RPC endpoints should still work like how we use Infura’s. Maybe there are slight differences?

**Comment by oa-s** [comment]
i am trying to make a direct call generated from urlRequest we send in curl:
```
curl --request POST \
--url 'https://public-node-api.klaytnapi.com/v1/cypress' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '[{"jsonrpc":"2.0","method":"eth_call","id":34,"params":[{"data":"0x70a08231000000000000000000000000424d0c6ed9addc9e80e81dbfe6e26911e4a25c8c","to":"0xb6fc2d963979a78fc7351695fcb829bc3c8b5b29","value":"0x0","gasPrice":"0x0"},"latest"]}]'
```

and i am getting error:
`{\"code\":1205800,\"message\":\"rps exceeded\",\"requestId\":\"338917c3-0d98-98f0-a955-967c70473eda\"}`

**Comment by hboon** [comment]
I’m guessing. Seems like it’s rate limited?

**Comment by oa-s** [comment]
batch requests don't work here, got it

**Comment by hboon** [comment]
@oa-s do you need anything from me for this?

**Comment by oa-s** [comment]
> @oa-s do you need anything from me for this?

clean up, and testing i suppose. will do one after rebase

**Comment by hboon** [comment]
I get this:

```
XXX.reachablility: receive subscription: (SubscribeOn)
XXX.reachablility: request unlimited
XXX.<AlphaWallet.OldestTransactionProvider: 0x60000044f6c0>.start
XXX.reachablility: receive subscription: (SubscribeOn)
XXX.reachablility: request unlimited
XXX.AlphaWallet.PendingTransactionProvider.start
XXX.AlphaWallet.NewlyAddedTransactionSchedulerProvider.will fetch tsx for page: 0
XXX.NewlyAddedTransactionSchedulerProvider.operation: receive subscription: (HandleEvents)
XXX.OldestTransactionSchedulerProvider.operation: receive subscription: (HandleEvents)
XXX.OldestTransactionSchedulerProvider.operation: request unlimited
XXX.NewlyAddedTransactionSchedulerProvider.operation: request unlimited

XXX.AlphaWallet.NewlyAddedTransactionSchedulerProvider.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
XXX.<AlphaWallet.NewlyAddedTransactionProvider: 0x6000dc0648a0>.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
XXX.<AlphaWallet.OldestTransactionProvider: 0x60000044f6c0>.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
XXX.NewlyAddedTransactionSchedulerProvider.operation: receive error: (covalentError(AlphaWallet.Covalent.CovalentError.requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))))
XXX.OldestTransactionSchedulerProvider.operation: receive error: (covalentError(AlphaWallet.Covalent.CovalentError.requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))))
```

**Comment by hboon** [comment]
Also, would you modify the commit message to mention Klaytn too (along with Covalent)?

**Comment by oa-s** [comment]
> I get this `501`s:
> 
> ```
> XXX.reachablility: receive subscription: (SubscribeOn)
> XXX.reachablility: request unlimited
> XXX.<AlphaWallet.OldestTransactionProvider: 0x60000044f6c0>.start
> XXX.reachablility: receive subscription: (SubscribeOn)
> XXX.reachablility: request unlimited
> XXX.AlphaWallet.PendingTransactionProvider.start
> XXX.AlphaWallet.NewlyAddedTransactionSchedulerProvider.will fetch tsx for page: 0
> XXX.NewlyAddedTransactionSchedulerProvider.operation: receive subscription: (HandleEvents)
> XXX.OldestTransactionSchedulerProvider.operation: receive subscription: (HandleEvents)
> XXX.OldestTransactionSchedulerProvider.operation: request unlimited
> XXX.NewlyAddedTransactionSchedulerProvider.operation: request unlimited
> 
> XXX.AlphaWallet.NewlyAddedTransactionSchedulerProvider.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
> XXX.<AlphaWallet.NewlyAddedTransactionProvider: 0x6000dc0648a0>.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
> XXX.<AlphaWallet.OldestTransactionProvider: 0x60000044f6c0>.didFailure: requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))
> XXX.NewlyAddedTransactionSchedulerProvider.operation: receive error: (covalentError(AlphaWallet.Covalent.CovalentError.requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))))
> XXX.OldestTransactionSchedulerProvider.operation: receive error: (covalentError(AlphaWallet.Covalent.CovalentError.requestFailure(AlphaWallet.DataRequestError.general(error: AlphaWallet.DataRequestError.general(error: Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 501)))))))
> ```

checking

**Comment by hboon** [comment]
@oa-s would you help buzz me when it's ready? I'll try to merge it later today or tomorrow so we can cut a release.

**Comment by oa-s** [comment]
> @oa-s would you help buzz me when it's ready? I'll try to merge it later today or tomorrow so we can cut a release.

sure

**Comment by oa-s** [comment]
@hboon can u please share wallet address to watch, where you were able to reproduce this issue

**Comment by oa-s** [comment]
@hboon oh missed case is that covalent doesn't supported for `Klaytn` testnet.

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — APPROVED** [review]
At https://github.com/oa-s/alpha-wallet-ios/blob/abf62e9b2c93fc796edb001c9aab8735bb963b0c/AlphaWallet/Core/ReachabilityManager.swift#L38:

```
if isReachable != newReachable {
```

Because `isReachable` is initialized to `true` in `init` (for me at least, but could be false sometimes?), this if-condition never matches true, so subscribers to `ReachabilityManagerProtocol.reachabilityObservable` never triggers and Covalent doesn't start.

Maybe there needs to be a "isFirstTime" flag or `isReachable` has to be optional?

Would you help merge after this? Thanks.

**Comment by oa-s** [comment]
waiting for travis and merge if it not fails

**Pull request merged**
