### PR TITLE
Add 3 items to Browser's menu #2828

### LINKED ISSUE #2828: Add 3 items to Browser's menu
As discussed.
**Add three items to the menu:**
1. My Bookmarks
2. History
3. Set as Home Page

if you set a new Home Page, show a navigation bar with a Home icon. 
https://zpl.io/2ZwxJJ4
https://zpl.io/awvJ6lj

Screenshot 2021-06-01 at 09 39 50

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2828

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
This crashes:

1. Set a homepage
2. Tap more button
3. Tap My Bookmarks
4. Tap a bookmark

Similarly for accessing history

**Comment by hboon** [comment]
Can you make the commit message more descriptive?

"Add support for setting homepage to browser"

Short, but says what's done :)

**Review by hboon — CHANGES_REQUESTED** [review]
Works for bookmarks, still crashes with history

**Comment by vladyslav-iosdev** [comment]
> Works for bookmarks, still crashes with history

oh, checking

**Review by hboon — APPROVED** [review]

**Pull request merged**
