### PR TITLE
Add basic Klaytn support (no transactions, i.e. no Covalent integration) #4193

### LINKED ISSUE #4193: Add basic Klaytn support (no transactions, i.e. no Covalent integration)
Refer to #4191

Mainnet and testnet

### LINKED ISSUE #4203: Klaytn Network Differences
Two further refinements for supporting Klaytn network:

- Block gas limit is much higher than standard Ethereum node:
```
    public static final long GAS_LIMIT_MAX =          4712380L;  //Max block gas for most chains
    public static final long GAS_LIMIT_MAX_KLAYTN = 100000000L;  //Klaytn gas limit, see https://docs.klaytn.com/klaytn/design/computation/computation-cost
```
- Klaytn requires all transaction signatures to be EIP155 format (which you should be doing anyway).

### LINKED ISSUE #4222: Klaytn networks have Locked Gas
Klaytn network can only use the gas price reported from the node (currently should be 750), same as Optimism and Arbitrum.

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4193, Closes #4203, Closes #4222

### CODE REVIEW

**Comment by hboon** [comment]
Balance is showing up.

I know this is a WIP, but just in case:

- [ ] We should use the Crypress icon for mainnet https://github.com/AlphaWallet/alpha-wallet-ios/issues/4191#issuecomment-1082822525
- [ ] Remember to move the key out:

    ```
    private let key = "ckey_7ee61be7f8364ba784f697510bd"
    ```

- [ ] It doesn't seem to fetch the transaction history (I notice it's pulling from Covalent already)

**Comment by oa-s** [comment]
> * It doesn't seem to fetch the transaction history (I notice it's pulling from Covalent already)

Move transactions fetching to other PR

**Comment by oa-s** [comment]
@hboon  pr is ready for review

**Review by hboon — CHANGES_REQUESTED** [review]
I see 20 KLAY in the wallet tab, but when I tap the native token, it shows 0.

Screenshot 2022-04-22 at 12 35 32 PM
Screenshot 2022-04-22 at 12 35 34 PM

After I switch to mainnet and back, it seems to have been fixed.

Transfer works for me.

**Comment by hboon** [comment]
I noticed some problems with forming the blockchain explorer webpage URLs like https://baobab.scope.klaytn.com/address/0xbbce83173d5c1D122AE64856b4Af0D5AE07Fa362. But it seems to require other refactoring to support the changes. So I'll look into it after the PR is merged.

**Comment by oa-s** [comment]
Checking it

**Comment by oa-s** [comment]
> After I switch to mainnet and back, it seems to have been fixed.

Closes with #4393

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — APPROVED** [review]

**Pull request merged**
