### PR TITLE
Make the Network name headline according to the design #3169

### LINKED ISSUE #3169: Make the Network name headline according to the design
Screenshot 2021-09-08 at 07 55 19

https://zpl.io/bWEARp7

- It's 50 pt high (the background behind)
- The font is SourceSansPro-Semibold 15pt, Dove #727272

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3169

### CODE REVIEW

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
@vladyslav-iosdev would you help attach before and after images for such PRs unless it takes too much time (it's entirely possible if it's a hard to reproduce case, for example)? I usually don't check the code (much) for these PRs. But be good to know what actually changed, but when looking at the PR and for posterity.

**Comment by vladyslav-iosdev** [comment]
Before PR:
Screenshot 2021-09-10 at 08 49 35
After PR:
Screenshot 2021-09-10 at 08 51 13

**Comment by hboon** [comment]
@vladyslav-iosdev thanks. Edited it to use a table, easier to see :)

**Comment by vladyslav-iosdev** [comment]
Awesome! i wanted to do the same, but didn't know how to make it.

**Pull request merged**
