### PR TITLE
Remove promises from balance fetchers, don't wait for all tokens balances updates #4460

### LINKED ISSUE #4460: Remove promises from balance fetchers, don't wait for all tokens balances updates
When updating wallet balances with a lot of tokens it takes to long for waiting. Remove promises, and make code clearer

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4460

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s I'll get to this tomorrow. What's the functional change that this PR will create?

**Comment by hboon** [comment]
@oa-s What's the functional change that this PR will create?

**Comment by oa-s** [comment]
@hboon Functionaly it should speedup updating tokens balances, as we don't wait for fetching balances for all the tokens, to make realm object update.

**Review by hboon — APPROVED** [review]
Ok. Hard to review, so just have to trust you on this one. Merge when ready.

**Comment by oa-s** [comment]
@hboon  Instances of type `TokenBalance`, have `json` field, can't find any cases of their usage, do you know why do we need it?

**Comment by hboon** [comment]
Not sure. Might be some half-bake work done to support TokenScript. Leave it first. Add a TODO in the code to check maybe?

**Pull request merged**
