### PR TITLE
Fix crash when creating xmlHandler #5319

### LINKED ISSUE #5319: Fix crash when creating xmlHandler

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #5319

### CODE REVIEW

**Comment by oa-s** [comment]
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues/69686d40b51e807d89a8355193b81989?time=last-thirty-days&types=crash&versions=3.49%20(447);3.49%20(446)&sessionEventKey=ea95f51e30c94a83a97184fb98111609_1714845666857954812

**Review by hboon — COMMENTED** [review]
Is the link to Crashlytics correct?

**Comment by oa-s** [comment]
Yes.

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Similar to the earlier comments about queue/thread-safe access, I rather we figure out a better way. But let's go with it for now :)

**Pull request merged**
