### PR TITLE
Update Settings Tab Icons [Fiji] #1853

### LINKED ISSUE #1853: Update Settings Tab Icons [Fiji]
Supersedes #1659 

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5dfc1f63646faf970d746224

* There is a WIP feature branch: `update-settings-screen-design`. Only the very first screen is implemented (and not in a good way).
* Take care to address or remove all the `//hhh` comments
* Fix some of the bad practises/code in the branch. There might still be some. Some are probably marked with `//hhh` comments
* SettingsViewController is the original version
* Ignore SettingsViewController2 (and delete it at some point)
* Work on `SettingsViewController3` and finally rename it back to `SettingsViewController`. Feel free to do this right away if you prefer.
* There might be some mix match of rows in the design and in the current version (SettingsViewController), if they are not found in SettingsViewController, ignore it.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1853

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev can you help to rebase master?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev can you help to rebase master?

done

**Comment by vladyslav-iosdev** [comment]
> Doesn't seem to be build correctly
> 
> You can squash the "WIP" and the newer commit you have added. Don't need to keep it.

Done

**Comment by vladyslav-iosdev** [comment]
> Looks great!
> 
> The project couldn't build because the project file didn't include the new files properly. I have fixed it, rebased master and forced push.
> 
> Can you help to remove these:
> 
> * [x]  Notifications
> * [x]  Change Currency
> * [x]  Analytics
> * [x]  Also, can you make Support open this instead (ignore Blog for now)?:
> 
> https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5dfc1f52a3e2aa1c676e66d4
> 
> Sorry, missed this earlier.

Done

**Pull request merged**
