### PR TITLE
Prompt to sign messages #2497

### LINKED ISSUE #2497: Prompt to sign messages
Continuing from #2496:

There are a few versions for the prompt to sign messages https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/6012d1ea027bac2033d22ea7. You can try them at https://danfinlay.github.io/js-eth-personal-sign-examples/. Not all of them work. So try these:

* personal_sign
* Sign Typed Data
* Sign Typed Data V3
* Sign Typed Data V4 (it's the same as v3, the message in this example might be a bit longer)

It looks like this https://github.com/AlphaWallet/alpha-wallet-ios/pull/2461 currently for Sign Typed Data V3 and V4. For Sign Typed Data V3/V3, besides the message, it'll be good to include these 2 values:

* "domain name" ("Ether Mail" in the screenshot)
* "verifying contract" ("0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC")

The message for Sign Typed Data V3/V4 is a JSON string. For styling, we can change the font, color and add indentation (spaces), but can't otherwise have much control over the formatting. The length of some of the values might be too long to display (hence the intentional ellipsis for long values, otherwise it does a very ugly linewrap breaking the indentation). We ought to be able to do our normal 0xabcd...abcd formatting for addresses though, and keep the trailing truncation for non-address values.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2497

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Actionsheet looks ok for simple message signing.

I understand it's a WIP, so you probably planned to address these already. But any way:

- [x] When tapped on "Show", the message should be shown in a full screen view controller (https://user-images.githubusercontent.com/51817359/107025043-22729280-67a9-11eb-8b87-b29527aa120c.png)
- [ ] Tapping on "OK" in the confirm signing message doesn't do anything
- [ ] If the message is long, the "Show" button in the "Signature Request" actionsheet isn't shown (at least I think that's the reason)
- [ ] "persona_sign" in https://danfinlay.github.io/js-eth-personal-sign-examples/ doesn't displaying the "Show" button too
- [ ] For typed messages (EIP712, v3 and v4), all the rows in the actionsheet should have a "Show" button (https://user-images.githubusercontent.com/51817359/107025043-22729280-67a9-11eb-8b87-b29527aa120c.png). I suppose that means we just show the the keys at the "1st layer" of the JSON; the user has to tap the rows to look at nested dictionary/arrays as a formatted JSON string

**Review by hboon — CHANGES_REQUESTED** [review]
Looks good. One thing to fix:

Visiting https://example.walletconnect.org and tapping eth_signTypedData and the "Show" buttons in "encodedFun.." and "target..." is covered by the field value.

**Comment by vladyslav-iosdev** [comment]
> https://example.walletconnect.org

oh, i see. Missed that.

**Comment by hboon** [comment]
BTW, https://danfinlay.github.io/js-eth-personal-sign-examples/ seems a little broken recently. In case you were testing with it and thought it's our bug. The confirmation doesn't seem to pop up correctly, but the request to sign etc should still work.

**Comment by hboon** [comment]
Remember to buzz me again if it's ready

**Comment by vladyslav-iosdev** [comment]
@hboon for me it doesn't even appear, for this service, 
https://danfinlay.github.io/js-eth-personal-sign-examples/

**Comment by vladyslav-iosdev** [comment]
> seems a little broken recently. In case you were testing with it and thought it's our bug. The confirmation doesn't seem to pop up correctly, but the request to sign etc should still work.

Just tested it, it works fine, all popus appear as needed.

**Comment by hboon** [comment]
@vladyslav-iosdev does 81d9761 work for you? No popups appear for me, including https://xcontract.herokuapp.com/sign

**Comment by vladyslav-iosdev** [comment]
@hboon i am a little bit confused, first time i opened link in dapp browser, it worked ok.
https://danfinlay.github.io/js-eth-personal-sign-examples/
now it doens't work (pop up does't appear) even browser callback doesn't get called.

**Comment by hboon** [comment]
Force pushed after changing commit message from 

> Prompt to sign messages #2497 

to:

> Update prompt to sign messages to use actionsheet-style #2497

More intention revealing :)

**Review by hboon — APPROVED** [review]

**Pull request merged**
