### PR TITLE
Use single Realm instances for background, and main threads #4664

### LINKED ISSUE #4664: Use single runloop thread for realm updates

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4664

### CODE REVIEW

**Comment by oa-s** [comment]
PR improves realm object updates, allows to handle background updates for single object params changing. Allows <List> observation especially for nft balances.

**Comment by hboon** [comment]
Would you add to the PR title/commit message to mention why? This is useful:

> PR improves realm object updates, allows to handle background updates for single object params changing. Allows observation especially for nft balances.

Or if it improves performance or reduce crashes.

**Review by hboon — APPROVED** [review]
Didn't check. Let me know if there's something specific you want to look into :)

**Comment by oa-s** [comment]
PR improvance:
- use single Realm instances for background, and for main threads. (useful for nft tokens, previously it wasn't support)
- allows correct object observing, allows handling fields when they were updated in background.
- hope, it will reduce crashes ;)

**Comment by hboon** [comment]
> PR improvance:
> 
> * use single Realm instances for background, and for main threads. (useful for nft tokens, previously it wasn't support)
> * allows correct object observing, allows handling fields when they were updated in background.
> * hope, it will reduce crashes ;)

Add it to the commit message after the first setence and make the first sentence a summary :)

**Pull request merged**
