### PR TITLE
Crash when fetching events #3046

### LINKED ISSUE #3046: Crash when fetching events
Seems like #3043 introduces a crash. I tested with wallet: `0x007bEe82BDd9e866b2bd114780a47f2261C684E3` on Ropsten.

If we modify the loop at:

https://github.com/AlphaWallet/alpha-wallet-ios/blob/86555ad46d1cbf774ea9185daf7851a0082f59fa/AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift#L55

to become:

```
for each in activities {
    let date = each.date.timeIntervalSince1970
    let key: ActivityDateKey = .init(timeInterval: date)
    let currentItems = newItems[key] ?? .init()
    currentItems.add(each)
    NSLog("xxx keys before: \(newItems.keys) count: \(newItems.keys.count)")
    NSLog("xxx adding key: \(key) with hash: \(key.stringValue)")
    newItems[key] = currentItems
    NSLog("xxx adding after key count: \(newItems.keys.count)")
}

```

Running it, I get:

> 2021-08-10 11:58:56.293132+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1610440545.0, stringValue: "Jan 12, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603530944.0, stringValue: "Oct 24, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613564548.0, stringValue: "Feb 17, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603947660.0, stringValue: "Oct 29, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613451787.0, stringValue: "Feb 16, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603437376.0, stringValue: "Oct 23, 2020")] count: 6
> 2021-08-10 11:58:56.293289+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603438086.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> 2021-08-10 11:58:56.293435+0800 AlphaWallet[742:8953664] xxx adding after key count: 6
> 2021-08-10 11:58:56.293652+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1610440545.0, stringValue: "Jan 12, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603530944.0, stringValue: "Oct 24, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613564548.0, stringValue: "Feb 17, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603947660.0, stringValue: "Oct 29, 2020"), AlphaWallet.ActivityDateKey(timeInterval: 1613451787.0, stringValue: "Feb 16, 2021"), AlphaWallet.ActivityDateKey(timeInterval: 1603437376.0, stringValue: "Oct 23, 2020")] count: 6
> 2021-08-10 11:58:56.293825+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603438086.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> 2021-08-10 11:58:56.293962+0800 AlphaWallet[742:8953664] xxx adding after key count: 6
> 2021-08-10 11:58:56.387917+0800 AlphaWallet[742:8953691] Version 10.12.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v10.12.0/CHANGELOG.md
> 2021-08-10 11:58:56.398084+0800 AlphaWallet[742:8953664] xxx keys before: [] count: 0
> 2021-08-10 11:58:56.398283+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603782995.0, stringValue: "Oct 27, 2020") with hash: Oct 27, 2020
> 2021-08-10 11:58:56.398452+0800 AlphaWallet[742:8953664] xxx adding after key count: 1
> 2021-08-10 11:58:56.398670+0800 AlphaWallet[742:8953664] xxx keys before: [AlphaWallet.ActivityDateKey(timeInterval: 1603782995.0, stringValue: "Oct 27, 2020")] count: 1
> 2021-08-10 11:58:56.398966+0800 AlphaWallet[742:8953664] xxx adding key: ActivityDateKey(timeInterval: 1603437972.0, stringValue: "Oct 23, 2020") with hash: Oct 23, 2020
> Fatal error: Duplicate keys of type 'ActivityDateKey' were found in a Dictionary.
> This usually means either that the type violates Hashable's requirements, or
> that members of such a dictionary were mutated after insertion.
> 2021-08-10 11:58:56.399572+0800 AlphaWallet[742:8953664] Fatal error: Duplicate keys of type 'ActivityDateKey' were found in a Dictionary.
> This usually means either that the type violates Hashable's requirements, or
> that members of such a dictionary were mutated after insertion.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Fixes #3046

### CODE REVIEW

**Review by hboon — APPROVED** [review]
Not sure this is correct. Doesn't this mean that every `ActivityDateKey` instance would now have the same hash, so there is only 1 header appearing in Activity for the 1st date encountered in the relevant code?

**Review by hboon — CHANGES_REQUESTED** [review]
Not sure this is correct. Doesn't this mean that every ActivityDateKey instance would now have the same hash, so there is only 1 header appearing in Activity for the 1st date encountered in the relevant code?

**Comment by hboon** [comment]
Meant to reject. Don't merge :)

**Comment by vladyslav-iosdev** [comment]
> Not sure this is correct. Doesn't this mean that every ActivityDateKey instance would now have the same hash, so there is only 1 header appearing in Activity for the 1st date encountered in the relevant code?

oh, yep u right. checking

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Do you know why it caused a crash though? I don't understand.

**Comment by vladyslav-iosdev** [comment]
> Do you know why it caused a crash though? I don't understand.

if truthly i don't know too. but for some reasons it doesnt want to accept `custom hashable type` as key of dictionary, because it finds that it can be mutable for some reasons.  here what i found
https://github.com/apple/swift/blob/main/stdlib/public/core/NativeDictionary.swift

**Comment by hboon** [comment]
Ah, will try to figure it out. Thanks!

**Comment by hboon** [comment]
@vladyslav-iosdev Oh, the reason is at https://github.com/vladyslav-iosdev/alpha-wallet-ios/blob/044b86a4636d8def3182bfd19696adb77636e5ce/AlphaWallet/Activities/ViewModels/ActivitiesViewModel.swift#L31

This line:

```
return lhs.stringValue == lhs.stringValue
```

should be this instead:

```
return lhs.stringValue == rhs.stringValue
```

(There should be a SwiftLint check for this)

So if the implementation in #3043, you can restore it with this fix. Created #3052. You can close it if it's not necessary.

**Pull request merged**
