### PR TITLE
return ETH symbol rather than Goerli

### PR DESCRIPTION
**Pull request by James-Sangalli**

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon you mean with the special o char?

**Comment by hboon** [comment]
> @hboon you mean with the special o char?

No. From "0.15 Görli (GÖETH)" to "0.15 Görli (ETH)".

The hardcoded string which you updated is used in the app except when displaying the list of tokens in the wallet tab. The symbol is saved into the database, once, upon creation and read to display in the Wallets tab.

But then Görli support isn't available on the app store yet, only 2-3 of us will have this problem, so maybe it's not worth doing a migration for this..

**Comment by James-Sangalli** [comment]
@hboon yes, not yet released. Probably best we simply do it. Will it cause a crash or simply the wrong symbol to be displayed?

**Comment by hboon** [comment]
Simply wrong symbol for the 2-3 of us until reinstall. No crash or error otherwise.

Probably not worth the effort to do a migration. Up to you.

**Pull request merged**
