### PR TITLE
Build the Info tab for fungibles (native crypto + ERC20) and move the most recent 3 transactions into the Activity tab #2748

### LINKED ISSUE #2748: [Samoa] Build the Info tab for fungibles (native crypto + ERC20) and move the most recent 3 transactions into the Activity tab
No alert tab.

Original issue: #2629

Refer to umbrella issue: #2747

### LINKED ISSUE #2749: [Samoa] Modify the Activity sub-tab in token screen to show relevant Activities instead, with the correct UI and data
Refer to umbrella issue: #2747

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2748, closes #2749

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Looks great! A couple of questions:

* What if there is no price data for a particular token?
* What if price data failed to load?
* The labels like "ath" etc should need to be tweaked (I know it's a WIP)
* When the user touch down and drag their finger over the charts, is it possible to short the price and date/time at that point?

**Comment by hboon** [comment]
@vladyslav-iosdev BTW, before it's too late, do you want to keep the old `TokenViewController` around, if it doesn't complicate the code much? I'm thinking it might be easier for the other project when we sync again.

**Comment by vladyslav-iosdev** [comment]
> * What if there is no price data for a particular token?
> * What if price data failed to load?

for now it will display all fields with "-" values, the same for charts, 'no chart data' will be displayed.

**Comment by vladyslav-iosdev** [comment]
@hboon as for me, current implementation for tickers, isn't perfect, would be better to update it as subscribable values.

**Comment by vladyslav-iosdev** [comment]
> * When the user touch down and drag their finger over the charts, is it possible to short the price and date/time at that point?

sure, i will check it.

**Comment by hboon** [comment]
>@hboon as for me, current implementation for tickers, isn't perfect, would be better to update it as subscribable values. 

@vladyslav-iosdev yes. I didn’t change it because we could see how the UI works. Can do it later. It’s ok.

**Comment by vladyslav-iosdev** [comment]
@hboon can u provide more detailed information, what fields from ticker do we need to display, and what formatting specification for them?

**Comment by hboon** [comment]
@vladyslav-iosdev Looking at https://projects.invisionapp.com/share/7TZHRQ8W265#/screens/438941755, I think you can ignore:

* 24-H return
* Profit/Loss
* portfolio share
* average cost
* paid fees

They can't be computed unless we have the purchase data.

We should be able to get market cap and total supply if it isn't already available in the CoinGeck calls we made.

Let me know if you need more?

**Comment by vladyslav-iosdev** [comment]
@hboon can u describe how to resolve perfomance fields? what logic for their calculation should be

**Comment by hboon** [comment]
How about take the oldest price of each period - current?

**Comment by vladyslav-iosdev** [comment]
> How about take the oldest price of each period - current?

ok, i got it. also what about percentage value for it? how can i get it?
Screenshot 2021-05-17 at 09 33 58

**Comment by hboon** [comment]
Current / the_period_oldest_value * 100. Is that what are referring to?

**Comment by vladyslav-iosdev** [comment]
> Current / the_period_oldest_value * 100. Is that what are referring to?

thx, yes

**Comment by hboon** [comment]
Remember to buzz me if you want a review again.

**Comment by vladyslav-iosdev** [comment]
@hboon during developing i found that creating XMLHandler takes to many time, can we cache  XMLHandler instances ?  does it can brake any logic?

**Comment by hboon** [comment]
`XMLHandler` is just a wrapper around `PrivateXMLHandler`. The latter is already cached. Creating `XMLHandler` shouldn't take too much time.

**Comment by vladyslav-iosdev** [comment]
> `XMLHandler` is just a wrapper around `PrivateXMLHandler`. The latter is already cached. Creating `XMLHandler` shouldn't take too much time.

ok, i got it. Can u check this PR?

**Comment by hboon** [comment]
Ok!

**Comment by hboon** [comment]
Looks good except the numbers in the screenshot look strange. For example 1 day is "76.83 USD" maybe, then it can't be 97.01%, because ETH is around 2500-2600 USD these 2 days. Similarly, it was around 2300-2800 the past 7 days, and so on


Screenshot 2021-06-10 at 11 57 54 PM

**Comment by vladyslav-iosdev** [comment]
@hboon check this pr,  values should be ok now.

**Review by hboon — CHANGES_REQUESTED** [review]
- [ ] Can you describe how the Performance 1 Year is computed with numbers (you can make some up) as example? (I'm still wondering what it should actually show, not only what is being shown in the PR)
- [x] I think the fonts like "Stats" and "Market Cap" doesn't seem to match the design
- [x] Can you change format the Market Cap 248392873791 to become 248.39B? Maybe hardcode (or if there's a way to do it with formatters) so that B(illion), M(illion) are supported? And < 1M as it is, but all rounded to 2 decimal places since it's fiat
- [x] Let's use "USD" instead of "$" for Market Cap like we do for 1 Year Low/High (I know the design is a bit inconsistent there).
- [x] The token icon should be smaller

**Comment by hboon** [comment]
BTW, we should be using `1.10.1`. You'll have it if you run `bundle` to install gems in the project root.

**Comment by vladyslav-iosdev** [comment]
> * Can you describe how the Performance 1 Year is computed with numbers (you can make some up) as example? (I'm still wondering what it should actually show, not only what is being shown in the PR)

we computing value change according the values we got from the api.  here is description how it works

**Review by hboon — CHANGES_REQUESTED** [review]
Ok, I'm not too sure about the computations, but they don't look blantantly wrong. Could you help remove/hide the "Total Supply" and "Max Supply" rows? But we should figure out how to add them in a separate PR.

**Comment by vladyslav-iosdev** [comment]
> Total Supply 

as well as `Max Supply` we are getting from json, without any calculation on our side.

**Comment by vladyslav-iosdev** [comment]
@hboon Bump

**Review by hboon — APPROVED** [review]
Can you help rebase master and merge?

**Comment by vladyslav-iosdev** [comment]
@hboon i left pr unsquashed for reasons that this pr is too big, and it will be easier to find commits with problems

**Pull request merged**
