### PR TITLE
Improve fetching, and searching coin tickers #4580

### LINKED ISSUE #4580: The App Is Not Showing the Balance in USD of the Synthetic Tokens and the Boba Token
These synthetic tokens are the ones we use to implement cross chain swaps and AW is not registering them well. The balances in USD are not shown. Also the value on dollars of the native token of the Boba blockchain is not shown.

image

### LINKED ISSUE #4720: Not Shown $ Value of Tokens
The value in dollars of the tokens are not displayed, only the value of the native tokens of each network.

I'm pretty sure that when I opened the app after updated it with this last version 3.42 (430) the app showed the value in dollars but when I interacted with the app they disappeared immediately.

image

### LINKED ISSUE #4723: Not Shown Charts
The app only shows the chart of the native tokens. 

image

image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4580, Closes #4720, Closes #4723

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
@oa-s too big to check all. Can you describe how it fixes #4580?

**Comment by oa-s** [comment]
PR changes: 
- There was a problem with mapping address and rpc server to ticker id, we stored first matching ticker id without checking supported platforms values. in this pr we map tickers with `MappedCoinTickerId` that has primary token, for what ticker was find, and also supported platforms (that is dictionary of rpc server and address), so for now one ticker could be found for several tokens. 
- The pr also caches  ticker ids in local file so we don't need to load it every time app is launching. Reload interval is 1 week ( ad ticker ids dont  updates often). 
- The pr improves searching ticker id for when loading chanrt history, previously, we loaded history only if we have ticker, for now we trying to search ticker_id of return already cached and loading chart  history.

**Comment by oa-s** [comment]
There is still issue with searching for synthetic tokens ticker ids. as returned json of ticker ids don't contain these contracts. Need some flow of searching to such kind of ticker ids. @hboon any ideas?

**Comment by oa-s** [comment]
was trying to match tickers and tokens symbol: 

_if tokens symbol has syffix of tickers symbol  and tockens length is greater by 1 character then tickers symbol then it matches_

`token symbol: kusdt -> ticker_id: usdt, token symbol: susdt -> ticker_id: usdt`

**Comment by hboon** [comment]
Will check later, but no. Matching should be done via the tokens.json file. There should be an issue on this. It’s taken from this repo https://github.com/AlphaWallet/tokens

**Comment by hboon** [comment]
Then we can delegate building the mapping into that repo

**Comment by hboon** [comment]
> Will check later, but no. Matching should be done via the tokens.json file. There should be an issue on this. It’s taken from this repo https://github.com/AlphaWallet/tokens

This issue #3423

**Comment by hboon** [comment]
@oa-s I forgot what this is about :P It looks quite big. Do you need me to check anything?

**Comment by oa-s** [comment]
> @oa-s I forgot what this is about :P It looks quite big. Do you need me to check anything?

yes please

**Review by hboon — CHANGES_REQUESTED** [review]
The additional entries should be updated in the https://github.com/AlphaWallet/tokens repo's `tokens.json` file and then updated in our app's copy instead of adding a new file. (Sorry, I didn't noticed there's an additional tokens_2.json earlier)

Is `0xf04d3A8Eb17B832Fbebf43610e94BdC4fD5Cf2dd` + 137 a real token though? There are only 27 holders.

Similary for `0x2f28Add68e59733D23D5F57d94c31fb965f835D0` + 137, which has 11 holders.

https://github.com/AlphaWallet/tokens is in a bad state now. So let's get it fixed so that `tokens.json` can be updated properly. Could you help with these for this PR?

- [ ] Undo the change that introduce tokens_2.json (it's ok if we can't fix the price for those tokens, we'll do it when `tokens.json` can be updated)
- [ ] Clean up this PR so we can merge it (does it still do something?) and close it

**Comment by hboon** [comment]
```
[
    {
        "contracts": [
            {"address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", "chainId": 1},
            {"address": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174", "chainId": 137},
            {"address": "0x2f28Add68e59733D23D5F57d94c31fb965f835D0", "chainId": 137},
        ],
        "group": "usdc"
    },
    {
        "contracts": [
            {"address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", "chainId": 1},
            {"address": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619", "chainId": 137},
            {"address": "0xC11b1268C1A384e55C48c2391d8d480264A3A7F4", "chainId": 1},
        ],
        "group": "WETH"
    },
    {
        "contracts": [
            {"address": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56", "chainId": 56},
            {"address": "0xf04d3A8Eb17B832Fbebf43610e94BdC4fD5Cf2dd", "chainId": 137},
            {"address": "0xdab529f40e671a1d4bf91361c21bf9f0c9712ab7", "chainId": 137},

        ],
        "group": "BUSD"
    }
 ]
```

Pasting the contents of tokens_2.json so we can add it to https://github.com/AlphaWallet/tokens later

**Comment by oa-s** [comment]
> ```
> [
>     {
>         "contracts": [
>             {"address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", "chainId": 1},
>             {"address": "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174", "chainId": 137},
>             {"address": "0x2f28Add68e59733D23D5F57d94c31fb965f835D0", "chainId": 137},
>         ],
>         "group": "usdc"
>     },
>     {
>         "contracts": [
>             {"address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", "chainId": 1},
>             {"address": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619", "chainId": 137},
>             {"address": "0xC11b1268C1A384e55C48c2391d8d480264A3A7F4", "chainId": 1},
>         ],
>         "group": "WETH"
>     },
>     {
>         "contracts": [
>             {"address": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56", "chainId": 56},
>             {"address": "0xf04d3A8Eb17B832Fbebf43610e94BdC4fD5Cf2dd", "chainId": 137},
>             {"address": "0xdab529f40e671a1d4bf91361c21bf9f0c9712ab7", "chainId": 137},
> 
>         ],
>         "group": "BUSD"
>     }
>  ]
> ```
> 
> Pasting the contents of tokens_2.json so we can add it to https://github.com/AlphaWallet/tokens later

yes, right, that is just test example for some of tokens

**Comment by hboon** [comment]
@oa-s don't forget this one :)

**Pull request merged**
