### PR TITLE
Crash sometimes when searching in Activity tab #2281

### LINKED ISSUE #2281: Crash sometimes when searching in Activity tab
If you modify `ActivitiesViewController.processSearchWithKeywords` to log like this:

```
private func processSearchWithKeywords() {
    let keyword = searchController.searchBar.text

    DispatchQueue.global().async { [weak self] in
        guard let strongSelf = self else { return }

        NSLog("xxx update filter 1")
        strongSelf.viewModel.filter(.keyword(keyword))
        NSLog("xxx update filter 2")

        DispatchQueue.main.async {
            NSLog("xxx reloading 1")
            strongSelf.tableView.reloadData()
            NSLog("xxx reloading 2")
        }
    }
}
```

and:

```
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    NSLog("xxx cell: \(indexPath.section), \(indexPath.row)")
```

And repeatedly modify the search keywords to make section 0 have different number of items, eg. I can do this by just repeating switching between the keywords "a" and "" (a would match ERC20 approvals). (this might take 10s of times to trigger)

When it works, this would be logged:

> default	12:43:13.073585+0800	AlphaWallet	xxx update filter 1
> default	12:43:13.073663+0800	AlphaWallet	xxx update filter 2
> default	12:43:13.073916+0800	AlphaWallet	xxx reloading 1
> default	12:43:13.074646+0800	AlphaWallet	xxx reloading 2
> default	12:43:13.074848+0800	AlphaWallet	xxx cell: 0, 0
> default	12:43:13.076987+0800	AlphaWallet	xxx cell: 0, 1

When it crashes, this happens:

> default	12:43:56.576008+0800	AlphaWallet	xxx update filter 1
> default	12:43:56.576379+0800	AlphaWallet	xxx update filter 2
> default	12:43:56.577004+0800	AlphaWallet	xxx reloading 1
> default	12:43:56.577486+0800	AlphaWallet	xxx reloading 2
> default	12:43:56.579181+0800	AlphaWallet	xxx update filter 1
> default	12:43:56.579268+0800	AlphaWallet	xxx update filter 2
> default	12:43:56.591212+0800	AlphaWallet	xxx cell: 0, 0
> default	12:43:56.592997+0800	AlphaWallet	xxx cell: 1, 0
> default	12:43:56.595104+0800	AlphaWallet	xxx cell: 1, 1

Noticed that a second round of "update filter" starts before cells are asked for.

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2281

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Clashes here:

Screenshot 2020-11-16 at 10 11 10 PM

**Comment by vladyslav-iosdev** [comment]
hmmm, i will check.

**Comment by vladyslav-iosdev** [comment]
@hboon now it should be ok. it worked for me

**Review by hboon — CHANGES_REQUESTED** [review]
I get this when I switch quickly between "a" and "" and few times:

> Application Specific Information:
> Fatal error: Index out of range
>  
> CoreSimulator 732.18.0.2 - Device: iPhone X (12.4) (8514192F-9E0E-4713-B6F9-6B3F9BCF7A87) - Runtime: iOS 12.4 (16G73) - DeviceType: iPhone X
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libswiftCore.dylib            	0x0000000112dc3853 specialized _fatalErrorMessage(_:_:file:line:flags:) + 307
> 1   libswiftCore.dylib            	0x0000000112ba42c4 _ArrayBuffer._checkInoutAndNativeTypeCheckedBounds(_:wasNativeTypeChecked:) + 244
> 2   libswiftCore.dylib            	0x0000000112ba7541 Array.subscript.getter + 81
> 3   com.stormbird.alphawallet     	0x000000010913e243 ActivitiesViewModel.item(for:section:) + 195 (ActivitiesViewModel.swift:123)
> 4   com.stormbird.alphawallet     	0x000000010916eaff ActivitiesViewController.tableView(_:cellForRowAt:) + 879 (ActivitiesViewController.swift:247)

**Comment by vladyslav-iosdev** [comment]
> I get this when I switch quickly between "a" and "" and few times:

Yep, i also was able to reproduce this.
Removed backgroung perfomance as it cause a lot of issues.

**Comment by hboon** [comment]
Forced pushed after rebase and removing now unused "queue" var (from previous version of this PR)

**Review by hboon — APPROVED** [review]
Yeah, looks like performance is acceptable with throttling

**Pull request merged**
