### PR TITLE
Support of ERC 1155 Tokens #2750

### LINKED ISSUE #2750: Support of ERC 1155 Tokens
**Invision clickable prototype:**
https://invis.io/HD10WWZ5JXA5

Zeplin:
**Project**
All ERC1155 tokens are distributed to 'Projects'. They have tabs (Info, Activity, Assets). In the Assets tap, you will find more granular division.
- https://zpl.io/2v3EQXj
----

**Single Tokens and List**
Each token differs with Details. They are: 
Issuer, Circulating Supply, Total Supply, Reserve Value, Type, Transferability, Melt Fee, Transfer Fee, Token ID, Created, Rarity, Item Type, Holders, Melts, Transfers, Description
- https://zpl.io/2ZM6ddJ

----
**Send Multiple Tokens**
- https://zpl.io/a8n5d36

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes  #2750

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev too big to review :) is it done on your side? If it's not exposed and doesn't break anything, we can merge it into master and I can work on it together with the backend.

**Comment by hboon** [comment]
@vladyslav-iosdev how can I see it in action?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev how can I see it in action?

tapping on any erc1155 token opens a new flow.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev too big to review :) is it done on your side? If it's not exposed and doesn't break anything, we can merge it into master and I can work on it together with the backend.

it should't, but i will double check.

**Comment by hboon** [comment]
Ok, I ran it by making an ERC721 token open up the flow. Seems generally ok. Can you help take a quick look if it doesn't break anything if there are no ERC1155 tokens, then let's just merge it.

**Comment by vladyslav-iosdev** [comment]
> Ok, I ran it by making an ERC721 token open up the flow. Seems generally ok. Can you help take a quick look if it doesn't break anything if there are no ERC1155 tokens, then let's just merge it.

ok, np.

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Merge if you are ready, or let me know if you want me to merge

**Pull request merged**
