### PR TITLE
Actionsheet for transaction confirmations for all transactions (except claiming paid MagicLinks), so the user can adjust gas settings and nonce for all transactions

### LINKED ISSUE #1687: Actionsheet-style confirmation for TokenScript transactions

### LINKED ISSUE #1689: Actionsheet-style confirmation for "normal" transactions
i.e. not TokenScript and not MagicLink(s)

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #1687, Closes #1689

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Seems to be missing `UIStackView.removeAllArrangedSubviews`

**Comment by vladyslav-iosdev** [comment]
> Seems to be missing `UIStackView.removeAllArrangedSubviews`

u right, my fail, i fixed it.

**Comment by hboon** [comment]
Thanks, I'll look at it by tomorrow along with the other PRs :)

**Comment by vladyslav-iosdev** [comment]
> Thanks, I'll look at it by tomorrow along with the other PRs :)

ok.

**Review by hboon — CHANGES_REQUESTED** [review]
- [x] Tapping outside of the actionsheet should close it
- [x] The "header" with the title "Confirm Transfer" seems too short.
- [x] Order should be "Balance", "Gas", "Recipient", "Amount".
- [x] The Amount value should show the full amount — e.g if the user entered `0.123469`, it should not show `0.1234`
- [x] The Gas row should have the same height as the others
- [x] The Gas row should default to "Default", not "Slow", for native cryptos
- [x] The Gas row should default to "Default", not "Custom", for ERC20s too
- [x] Can we make the actions tied to each row be triggered when the user taps anywhere in that row, rather than tapping in the "Edit" button or the chevron? i.e. the "Edit" and chevron are just labels
- [x] Remember to show the estimated fiat ($) value in Amount row when the price is available. e.g. "1 ETH ≈ 380 USD"
- [x] In the "Set Speed" screen, tapping a row should go back immediately
- [x] In the "Set Speed" screen, the Transaction Data should be empty for sending ETH
- [ ] Are we already fetching and computing the gas estimates for Fast, Average, Slow?
- [ ] Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"

Chevron rotating is nice!

 - [ ] Maybe it helps to just support these for gas — "Default", "Custom" so we don't have to worry about fetching them and time estimates and you can follow up with a separate PR to add the functionality?

**Comment by vladyslav-iosdev** [comment]
> * [ ]  The "header" with the title "Confirm Transfer" seems too short.

i am not sure how to increase the height, because it displays on `UINavigationBar`

**Comment by hboon** [comment]
>> * [ ]  The "header" with the title "Confirm Transfer" seems too short. ...

@vladyslav-iosdev is it important for the UINavigationBar to be visible? Otherwise can we hide it and use a custom view to replace that header?

**Comment by vladyslav-iosdev** [comment]
> > > * [ ]   The "header" with the title "Confirm Transfer" seems too short. ...
> 
> @vladyslav-iosdev is it important for the UINavigationBar to be visible? Otherwise can we hide it and use a custom view to replace that header?

ok, np. i used UINavigationBar, because in prev design version, configure transaction controller should be pushed in the same navigation controller as confirmation view controller.

**Comment by vladyslav-iosdev** [comment]
> * Are we already fetching and computing the gas estimates for Fast, Average, Slow?

not now no, but can u help me to resolve how it should be calculated?

**Comment by vladyslav-iosdev** [comment]
> [ ] In the "Set Speed" screen, tapping a row should go back immediately

so we dont need fields validation on this screen?

**Comment by vladyslav-iosdev** [comment]
> * [ ]  Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"

also how can i calculate this "2 minutes" approximate time?

**Comment by hboon** [comment]
> > * Are we already fetching and computing the gas estimates for Fast, Average, Slow?
> 
> not now no, but can u help me to resolve how it should be calculated?

Leave it out of the PR first. Would you help create a separate issue to do this? So we can just do "Default" (which will probably be "Average" next time) and "Custom".

**Comment by hboon** [comment]
> > [ ] In the "Set Speed" screen, tapping a row should go back immediately
> 
> so we dont need fields validation on this screen?

Hmm.. How about only showing the "Save" button when the user taps on Custom? We don't need to show it when the user taps on "Default" (or "Average")

**Comment by hboon** [comment]
> > * [ ]   Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"
> 
> also how can i calculate this "2 minutes" approximate time?

Same issue like https://github.com/AlphaWallet/alpha-wallet-ios/pull/2105#issuecomment-683635476

**Comment by vladyslav-iosdev** [comment]
> * [ ]  Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"

@hboon am i understand right, i need to user some third party api to fetch `cost of gas and time`,  like this? 
https://api.etherscan.io/api?module=gastracker&action=gasestimate&gasprice=12323423423&apikey=

**Comment by vladyslav-iosdev** [comment]
> * [ ]  Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"

@hboon  for now no, i quite don't know how to do that, maybe it already implemented in code? maybe u can help me with it?

**Comment by hboon** [comment]
> > * [ ]   Can we show the approximate cost of gas and time? like "< 0.00362 ETH ($0.69 USD) ≈ 2 minutes"
> 
> @hboon for now no, i quite don't know how to do that, maybe it already implemented in code? maybe u can help me with it?
> there is already present method `eth_estimateGas` but i am not sure if its right method.

Don't worry about it for now, just do "Default" (which will probably be "Average" next time) and "Custom" and we can add it in later.

**Comment by vladyslav-iosdev** [comment]
@hboon can u review this please?

**Review by hboon — CHANGES_REQUESTED** [review]
- [x] When the actionsheet appears, the entire send screen slides up a bit, can that not happen? Notice in the "After" screenshot that the Cancel button and "Send ETH" title has moved up and is now hidden.

Before|After
-|-
|


- [x] During the animation when the actionsheet appears, the gray out area also appears to slide up, can it fade in instead?
- [x] The alignment for the labels Balance, Gas, Recipient and Amount, as well as the Edit button and the Recipient's chevron is a bit off, slightly higher than it should be.
- [x] Change "Blockie & ENS" to just "ENS"
- [x] The gas price and gas limit sliders isn't working correctly



The one in the PR has a hardcoded gas price, eg. 1-500. Similarly for gas limit.

But with the version in master, while it has a limit of 1-500 too, the user can key in a number, say 2000, and then the slider's range becomes 1-2000. Similarly for the gas limit.

- [ ] Can you implement this progress/activity view too? (either in this PR or in a followup)

Screenshot 2020-10-08 at 12 12 09 PM

- [ ] The fields don't display correctly in the actionsheet if it's an ERC20 token. eg. balance doesnt' show both current and new, and amount isn't displayed



- [x] Can you also help to rebase master? Seems like names of some of the classes have changed

**Comment by hboon** [comment]
Notes for the future (out of scope for this PR):

- [ ] Better/smarter gas settings like slow/normal/fast
- [ ] Display estimate time based on gas settings

**Comment by hboon** [comment]
I know this is a WIP, but anyway, I checked it out just in case:

- [ ] The animation when the actionsheet appears is good. Can we speed up the animation when the actionsheet slides out (when cancelled)
- [ ] Tapping Custom (speed/gas) no longer shows the custom gas settings (that's why I thought it's a WIP)
- [ ] Tapping the header of the actionsheet (the icon, "Confirm Transfer?") shouldn't close it. Should do nothing instead

**Comment by vladyslav-iosdev** [comment]
> The fields don't display correctly in the actionsheet if it's an ERC20 token. eg. balance doesnt' show both current and new, and amount isn't displayed

@hboon  can u send me some ERC20 tokens to check how it get displayed (because i tested only with native crypto)?

**Comment by vladyslav-iosdev** [comment]
> https://ropsten.etherscan.io/tx/0x7a1971667e2686b8697fc85cd080e89d37bfba37ef8e05f59fb4a92171ef185e

seems like yes, but it displays incorrectly, isn't it?
Screenshot 2020-10-13 at 16 37 10

**Comment by vladyslav-iosdev** [comment]
maybe i sent u wrond address 
can u try this 0x68f5974Ba0F810A3d45acC6fFAee610Abde05f22 ?

**Comment by hboon** [comment]
As in the balance is still 0? It seems to be very slow to update or stuck. I created an issue earlier today. Kill the app and it should refresh quite fast

**Comment by vladyslav-iosdev** [comment]
@hboon maybe u can help me, i was trying to animate Barbuttons `backgroundColor` (to show loading animation) but it seems like we are not able to apply CABasicAnimation for `backgroundColor`. maybe u know. how to do it?

**Comment by hboon** [comment]
@vladyslav-iosdev I thought `CABasicAnimation(keyPath: "backgroundColor")` should work. Maybe something else is messing it up? Why do you need to animate the background color?

**Comment by vladyslav-iosdev** [comment]
> CABasicAnimation(keyPath: "backgroundColor")

I tried this way to perform animation but it did work for me. I want to use it perform beautiful transition from confirmation button to loading indicator. Check lates commited changes to see how it works.

**Comment by hboon** [comment]
Looks good!

I took a look. No idea why it doesn't work. If you want, you can try animating `alpha` instead?

Can you make the tick animation speed up as it goes? Something like `.curveEaseIn`?

**Comment by vladyslav-iosdev** [comment]
> * Are we already fetching and computing the gas estimates for Fast, Average, Slow?

@hboon this not implemented yet, do u have any ideas how to do that, or maybe documentation ref for it.?

**Comment by vladyslav-iosdev** [comment]
i found this https://doc.upvest.co/reference#ethereum-fees
but not sure if its what we need.

**Comment by hboon** [comment]
We aren’t fetching it yet. Let’s that out of this PR and get this merged first.

**Comment by vladyslav-iosdev** [comment]
> We aren’t fetching it yet. Let’s that out of this PR and get this merged first.

ok, seems like all is done, if i not missed something.

**Comment by hboon** [comment]
Ok, I think we might be able to tweak the animation or screen's hiding when a transaction is sent. But can you squash into a single commit and rebase master and let's see?

**Comment by hboon** [comment]
Actionsheet for transaction confirmations for all transactions, so the user can adjust gas settings and nonce for all transactions:

* fungible transfers (native crypto and ERC20)
* non-fungible transfers
* dapp-initiated transactions
* TokenScript transactions

Also: 

* Make UnconfirmedTransaction clearer, whether `to` refers to recipient or contract
* The error message that used to be shown when the max gas (ETH) is exceeded was in `wei`. This is fixed too
* Fix: crash if transaction formed by dapp is malformed — no `to` address

@James-Sangalli would you help to test? This is a big PR, but the changes are isolated, so: a few places which are affected:

* Fungible (native crypto and ERC20) transfers
* NFT transfers
* Transactions initiated from dapps
* TokenScript transactions
* Gas price and limit estimates
* Max gas limit enforced
* Max gas (ETH) enforced

There is still follow up work after this PR:

- [ ] Fast/average/slow gas options. Maybe #2242
- [ ] Display estimate time based on gas settings
- [ ] After NFT transfer is done, we should close the UI and show activity tab like we do for fungible transfers
- [ ] Don't show the ENS label when recipient is expanded if there's no ENS name resolved
- [ ] Display the ETH value in actionsheet for dapp-initiated transactions
- [ ] Decode ERC20/ERC721/875 transfers for dapp-initiated transactions and display in actionsheet
- [ ] Show function name and args for TokenScript transactions
- [ ] Show name of token for ERC721 transfers (at least those from OpenSea)
- [ ] Rename TransferType? Not always transfers, but transactions
- [ ] Log events #2199

**Comment by hboon** [comment]
Forced pushed after rebase master

**Comment by hboon** [comment]
@vladyslav-iosdev FYI: I have removed `BiometricAuthentication` because when the app tries to access the user's seed/key for signing, iOS will automatically prompt the user for biometric.

**Pull request merged**
