### PR TITLE
Add thin gray lines behind the chart with edge values #3418

### LINKED ISSUE #3418: Add thin gray lines behind the chart with edge values
Screenshot 2021-11-09 at 15 51 51

https://zpl.io/bo7Pj8m

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3418

### CODE REVIEW

**Comment by hboon** [comment]
Force pushed after rebase master

**Review by hboon — CHANGES_REQUESTED** [review]
I added a commit to lighten the horizontal grid lines. Can you help to squash if that looks closer to the design?

Also see if you can add the labels on the right? Highlighted in https://github.com/AlphaWallet/alpha-wallet-ios/issues/3418#issue-1048700147

**Comment by vladyslav-iosdev** [comment]
> Also see if you can add the labels on the right?

but this PR, is already displaying them, on right side of the chart

**Comment by hboon** [comment]
Oh, what was I thinking. Hah!. Thanks

**Review by hboon — APPROVED** [review]

**Pull request merged**
