### PR TITLE
Improve the transition to Search Box at the top #3529

### LINKED ISSUE #3529: Improve the transition to Search Box at the top
Notice how the navigation bar animates. It slides up and it's not visually pleasant. Maybe we can speed up this animation.
https://user-images.githubusercontent.com/51817359/145568622-8a2073b1-813d-4abc-ac84-3d2b9e0f4705.mp4

This is the frame I am talking about.
Screenshot 2021-12-10 at 12 39 57

Check out how smooth this is in other apps.

Uploading 2021-12-10 09.02.16.mp4…

https://user-images.githubusercontent.com/51817359/145568860-8f4971e8-f859-4bb3-9962-492bdff685b9.mp4

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3529

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon seems like this one is better

**Comment by hboon** [comment]
@vladyslav-iosdev it works like this in the simulator when I build it. Is it the same for you? Is it better on the simulator?

https://user-images.githubusercontent.com/56189/145927473-65347b46-5bbf-48f9-b8ba-c1ff9b9000f5.mp4

**Comment by vladyslav-iosdev** [comment]
@hboon i was trying it on a real device, there it looks more smoothly.

**Comment by hboon** [comment]
I’ll take your word for it! (My device is displaying a bug and I want to keep it to debug so can’t test it there)

**Comment by hboon** [comment]
> WIP.

Oh, was just going to merge :)

**Comment by eviltofu** [comment]
I think I have a solution using `UIPresentationController`.

**Comment by hboon** [comment]
@oa-s need me or Jerome to do anything?

**Comment by oa-s** [comment]
@hboon do you have any examples of usage `UIPresentationController` those fit to our requirements (i mean animation)?

**Comment by hboon** [comment]
@oa-s not off the top of our head. @eviltofu ? Since you suggested it.

**Comment by hboon** [comment]
@eviltofu bump

**Comment by oa-s** [comment]
that isn't simple issue, as default implementation of UISearchBarController presented in navigationBar doesn't fit to our requirements. I was trying to implement something custom using `UIViewControllerAnimatedTransitioning`, `UIViewControllerTransitioningDelegate`

https://user-images.githubusercontent.com/96283950/149152575-439d764f-7a48-4eda-a7f6-f99b403ffa8e.mov

**Comment by hboon** [comment]
What if we don't animate at all? Is it easier?

**Comment by oa-s** [comment]
> What if we don't animate at all? Is it easier?

let me check it

**Comment by oa-s** [comment]
Here is updating without animation
https://user-images.githubusercontent.com/96283950/149206669-314dd505-ae48-4a22-856e-67fd1502b51e.mov

**Comment by eviltofu** [comment]
Do you still want me to try and do the animation code for this?

**Comment by hboon** [comment]
> Here is updating without animation
> https://user-images.githubusercontent.com/96283950/149206669-314dd505-ae48-4a22-856e-67fd1502b51e.mov

Looks ok. Thanks.

> Do you still want me to try and do the animation code for this?

Merged #3700. Closing this PR. But if you'd like, go for it.

**Comment by hboon** [comment]
Closing because #3700 supersedes this

**Pull request closed without merging**
