### PR TITLE
Add a logging library #3204

### LINKED ISSUE #3204: Add a logging library
Something that allows:

* different levels of logging (warning, trace, debug, etc).
* configurable to log to stdout or file
* be great if it's available on SwiftPM, but not too important

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3204

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
i was trying to use SPM but it seems like the proj doesn't want to compile.

**Comment by hboon** [comment]
Strange, this PR didn't seem to have triggered Travis.

**Review by hboon — CHANGES_REQUESTED** [review]
I'm getting build errors.

Maybe it is related to the `PaperTrailLumberjack` having a dependency on `CocoaLumberjack`? You can find it used in `RemoteLogger.swift`:

> Compile Swift source files (x86_64)
> Compile WKWebViewConfiguration.swift (x86_64)
> (5, 8) No such module 'CocoaLumberjackSwiftLogBackend'
> Compile LockViewModel.swift (x86_64)
> (5, 8) No such module 'CocoaLumberjackSwiftLogBackend'
> Compile Constants.swift (x86_64)
> (5, 8) No such module 'CocoaLumberjackSwiftLogBackend'
> Compile UIButton.swift (x86_64)
> (5, 8) No such module 'CocoaLumberjackSwiftLogBackend'

**Comment by vladyslav-iosdev** [comment]
@hboon seems like i imported incorrect module, now it should be ok

**Review by hboon — APPROVED** [review]
Great. I can build it too now. Can you help with these then you can merge when you ready?

* Make it log to the console too? (DDTTYLogger.sharedInstance?)
* Log everything to console, but only info, warning, error to file?
* Create a shared instance of Log and make debug() etc to instance side (so calls become `Log.instance.debug("foo")`)? This makes it a bit easier later if we want to selectively replace the logging calls in selected parts of the app?

**Comment by vladyslav-iosdev** [comment]
> Great. I can build it too now. Can you help with these then you can merge when you ready?
> 
> * Make it log to the console too? (DDTTYLogger.sharedInstance?)
> * Log everything to console, but only info, warning, error to file?
> * Create a shared instance of Log and make debug() etc to instance side (so calls become `Log.instance.debug("foo")`)? This makes it a bit easier later if we want to selectively replace the logging calls in selected parts of the app?

@hboon btw what if we create a common functions for each call debug, error, and son on 
```
func debug(_ loggger: Log = .instance, _ message: String) {
    loggger.debug(message)
} 
```
it could help us to easily switch between loggers further if needed

**Comment by hboon** [comment]
Sure, up to you.

**Review by hboon — CHANGES_REQUESTED** [review]
I noticed the messages aren't appearing when I look at them with `Console.log`. They do appear in AppCode/Xcode's console. There's this message:

> CocoaLumberjack: Warning: Usage of DDTTYLogger detected when DDOSLogger is available and can be used! Please consider migrating to DDOSLogger.

So I replaced `DDTTYLogger` with:

```
DDLog.add(DDOSLogger.sharedInstance)
```

The logs now appear in `Console.log`, but only `error`, not `verbose`, `info`, `debug` and `warn`. Can we make all 5 appear in `Console.log` like it does in Xcode/Appcode?

On the other hand, all 5 of them appear in the log files, can we make it so only `error`, `warn` and `info` appear, but `verbose` and `debug` don't?

**Comment by vladyslav-iosdev** [comment]
> The logs now appear in Console.log, but only error, not verbose, info, debug and warn. Can we make all 5 appear in Console.log like it does in Xcode/Appcode?

it also appears in `console.app` just need to select these checkboxes
Screenshot 2021-09-29 at 14 12 43

**Comment by hboon** [comment]
I must be doing something really silly here, I'm only getting info, warn, error, but not verbose and debug despite checking Info and Debug. Do you know why?

I see all 5 logged in Xcode (but strangely not in AppCode, but never mind that):

Screenshot 2021-09-29 at 10 20 58 PM

**Comment by hboon** [comment]
All 5 log levels show up in Console.app when I replace `DDOSLogger` with `DDASLLogger`:

```
DDLog.add(DDASLLogger.sharedInstance)
```

If that works for you too and you don't see anything wrong with it, shall we go with that?

**Comment by vladyslav-iosdev** [comment]
it seems like it's ok, except it rises warning `'DDASLLogger' was deprecated in iOS 10.0: Use DDOSLogger instead`

**Review by hboon — APPROVED** [review]
Thanks!

**Pull request merged**
