### PR TITLE
Fixed LiveLocaleSwitcherBundle Localization Bug

### LINKED ISSUE #3651: Localized strings not appearing when set to Simplified Chinese
Verify if simulator only.

1. Change language in Settings.app to Simplified Chinese
2. Launch AlphaWallet app
3. Activity tab

Dates are in Chinese but "Wallet" tab title is still in English. Our localization effort is somewhat patchy and incomplete so not all English strings are localized, but it seems like none of the localized ones are used.

Let's figure out why this is broken before fixing it. It might well be good to stay this way until we patch up the missing localization strings.

Screenshot 2022-01-07 at 10 32 28 AM

### PR DESCRIPTION
**Pull request by eviltofu**
Closes: #3651 and closes: #3680

### CODE REVIEW

**Comment by hboon** [comment]
Keep it for now if we proceed with this PR.

But I don't understand the reason for this PR. We don't want the in-app language switcher to be enabled.

**Comment by eviltofu** [comment]
@hboon I’ve changed the code to remove the reason why we only see English. Do you want me to go further into Config.setLocale to see if there is anything wrong with that code?

**Comment by hboon** [comment]
Oh yes. Would be good.

Can you also help to modify the PR title and commit message to reflect that this is fixing the bug and not changing the flag?

**Comment by hboon** [comment]
Thanks. I’ll look at it tomorrow. But if you are still around, can you check if we can bypass LiveLocalSwitcherBundle completely if in-app switching is disabled? It shouldn’t be necessary anymore when it is disabled.

**Comment by eviltofu** [comment]
> Thanks. I’ll look at it tomorrow. But if you are still around, can you check if we can bypass LiveLocalSwitcherBundle completely if in-app switching is disabled? It shouldn’t be necessary anymore when it is disabled.

I think we just don't set the Config locale at startup to skip it.

**Review by hboon — APPROVED** [review]
Looks good and thanks for hunting this down!

> I think we just don't set the Config locale at startup to skip it.

Can you help remove this and merge?:

```
if Features.isLanguageSwitcherDisabled {
    Config.setLocale(.system)
}
```

It should be safe. Users who have had the language override a long time ago should have already encountered this code already

**Pull request merged**
