### PR TITLE
Fix number overflow crash while when fetching erc1155 tokens #5550

### LINKED ISSUE #5550: Crash with ERC1155 token IDs fetching
https://console.firebase.google.com/u/0/project/alphawallet-ios-prod/crashlytics/app/ios:com.stormbird.alphawallet/issues?time=last-seven-days&state=open&tag=all

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #5550

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s thanks! Checking. I think we can tweak the test and fix a bit. Hold on.

**Comment by hboon** [comment]
@oa-s so still fixing the overflow problem, I've simplified the fix a bit and added a few test cases and comments. See if it makes sense? If it does, can you help update your branch and merge?

This: https://github.com/AlphaWallet/alpha-wallet-ios/tree/5550-alt

**Comment by oa-s** [comment]
from crash report in xcode
Screenshot 2022-10-13 at 07 59 22

**Comment by hboon** [comment]
Huh! The one time Xcode's crash logger was better than Crashlytics.

**Comment by oa-s** [comment]
@hboon  https://github.com/AlphaWallet/alpha-wallet-ios/tree/5550-alt it still crashes when we pass `maximumWindow: UInt64.max`

XCTAssert(Erc1155TokenIdsFetcher.functional.makeBlockRangeForEvents(toBlockNumber: 0, maximumWindow: UInt64.max, excludingRanges: [0..<5]) == nil)

**Comment by hboon** [comment]
@oas Checking…

**Comment by hboon** [comment]
@oa-s passes for me. Any idea where it crashes?

**Comment by oa-s** [comment]
sorry my fail, wrong branch :) work ok

**Pull request merged**
