### PR TITLE
Crash when tap to show a Hidden Token in Add / Hide Tokens screen #2933

### LINKED ISSUE #2933: Crash when tap to show a Hidden Token in Add / Hide Tokens screen
1. Tap Add / Hide Tokens
2. Scroll to Hidden Tokens
3. Hide a token first if there aren't any hidden tokens
4. Tap + on a Hidden Token
5. Crashes

```
2021-07-01 13:53:52.634623+0800 AlphaWallet[53050:926547] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], UITableView.m:2131
2021-07-01 13:53:52.637113+0800 AlphaWallet[53050:926547] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 0 from section 1 which only contains 0 rows before the update'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20422de3 +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207748e7 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff248bddc3 -[UITableView _endCellAnimationsWithContext:] + 6485
	5   UIKitCore                           0x00007fff248d9ff7 -[UITableView endUpdatesWithContext:] + 116
	6   UIKitCore                           0x00007fff248da1c9 -[UITableView _performBatchUpdates:withContext:completion:] + 253
	7   UIKitCore                           0x00007fff248da2af -[UITableView performBatchUpdates:completion:] + 97
	8   AlphaWallet                         0x00000001047db446 $s11AlphaWallet27AddHideTokensViewControllerC05tableF0_6commit8forRowAtySo07UITableF0C_So0mF16CellEditingStyleV10Foundation9IndexPathVtFyAA11TokenObjectC5token_AM05indexS8ToInsertSb04withT8CreationtSgcfU_ + 2278
	9   PromiseKit                          0x000000010784c4c6 $s10PromiseKit8ThenablePAAE4done2on5flags_AA0A0CyytGSo17OS_dispatch_queueCSg_8Dispatch0J13WorkItemFlagsVSgy1TQzKctFyAA6ResultOyARGcfU_yycfU_ + 214
	10  PromiseKit                          0x000000010781a300 $sIeg_IeyB_TR + 48
	11  libdispatch.dylib                   0x00007fff2010670d _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x00007fff201078df _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00007fff20114a27 _dispatch_main_queue_callback_4CF + 1045
	14  CoreFoundation                      0x00007fff203908f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00007fff2038b169 __CFRunLoopRun + 2781
	16  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	17  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	18  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	19  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	20  AlphaWallet                         0x00000001040bfcdb main + 75
	21  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException

Process finished with exit code 0
```

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Fixes #2933

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Still crashes for me when I un-hide.

**Comment by vladyslav-iosdev** [comment]
@hboon not it should be ok

**Comment by vladyslav-iosdev** [comment]
@hboon Bump

**Review by hboon — APPROVED** [review]
Looks good. Can you help rebase master before merging?

**Pull request merged**
