### PR TITLE
Show transaction confirmation information after each action complete in TS #2030

### LINKED ISSUE #2030: Show transaction confirmation information (marriage proposal) after each action complete in TS
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5f0d9787fbff438dfee0f65d

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2030

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli Maybe we should merge it into train-leaves branch first? We tap the Edit button at the top of this PR to change the target branch.

**Comment by vladyslav-iosdev** [comment]
@hboon one question, is there any general callback/closure, that called when each action is completed?

**Comment by hboon** [comment]
@vladyslav-iosdev No, but search for this:

```
notify(message: "Posted Transaction Successfully")
```

(TODO to make it localizable after the train leaves)

**Comment by hboon** [comment]
@vladyslav-iosdev btw, careful that you work out of the `train-leaves` branch and not `master`. Otherwise, we might be introducing PRs that have been merged into master but not into `train-leaves` which is based on an older master.

**Comment by vladyslav-iosdev** [comment]
> btw, careful that you work out of the `train-leaves` branch and not `master`. Otherwise, we might be introducing PRs that have been merged into master but not into `train-leaves` which is based on an older master.

ok, just to summarize, this one i should post to 'train-leaves' but before that i dont need to rebase 'master', right?

**Comment by vladyslav-iosdev** [comment]
> "Posted Transaction Successfully"

seems like i will not need this text because we raplace it with confirmation screen, right?

**Comment by hboon** [comment]
> ok, just to summarize, this one i should post to 'train-leaves' but before that i dont need to rebase 'master', right?

Right. If you want to git rebase "master" for these PRs, you want to do this instead: `git rebase train-leaves`

**Comment by vladyslav-iosdev** [comment]
@hboon can you send me eth to 0xf3e310f7EC8301bb188DF75A451c9d7B1548AfB3 for testing transaction?

**Comment by James-Sangalli** [comment]
> 0xf3e310f7EC8301bb188DF75A451c9d7B1548AfB3

sent you some

**Comment by vladyslav-iosdev** [comment]
> > 0xf3e310f7EC8301bb188DF75A451c9d7B1548AfB3
> 
> sent you some

thx!

**Comment by James-Sangalli** [comment]
@hboon please take a quick look over. it's rebased with master and can go in.

**Comment by hboon** [comment]
@James-Sangalli The commit a95c563ad9eb0a9d500797535d27a8c721bbffd2 ("Finances tab in iOS to show all defi related tokens #2029") shouldn't be included.

This PR seems to be combining two things:

* Showing the actionsheet style confirmation before a transaction (i.e. a "pop up")
* Showing the confirmation screen after posting a transaction (i.e. informational-only)

Is it intentional?

**Pull request merged**
