### PR TITLE
Repurpose fiat total value header in Wallet tab when in testnet mode #3569

### LINKED ISSUE #3569: Repurpose fiat total value header in Wallet tab when in testnet mode
Maybe hide or use that space to make it clear it's testnet?

Screenshot 2021-12-16 at 5 31 51 PM

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3569

### CODE REVIEW

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Need to fix conflicts before merging

**Comment by oa-s** [comment]
> Need to fix conflicts before merging

@hboon Done

**Comment by hboon** [comment]
@oa-s go ahead and merge it :)

**Comment by oa-s** [comment]
@hboon  i am not authorized to marge prs

**Comment by hboon** [comment]
Strange. Will fix it soon

**Pull request merged**
