### PR TITLE
Show full Ethereum address in transaction confirmation actionsheet not "0xabcd…cdef" #5576

### LINKED ISSUE #5529: Actionsheet confirmation should display ENS name if user entered one
Regression
 
Screenshot 2022-10-11 at 12 03 05 PM
Screenshot 2022-10-11 at 12 03 07 PM

### LINKED ISSUE #5576: Show full Ethereum address in transaction confirmation actionsheet not "0xabcd…cdef"
Careful to do it for when there's an ENS too. Both contracts and recipients. Too easy to fake them. Improve UX + safety for users

After #5529 since that would affect ENS display

from|to
-|-
Screenshot 2022-10-14 at 10 50 22 AM| Screenshot 2022-10-14 at 10 47 18 AM

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5576, Closes #5529

### CODE REVIEW

**Review by hboon — APPROVED** [review]
Looks like it fixes #5529 too.

Can you help make it show the full address here (and let it wrap), when there's an ENS too?

Screenshot 2022-10-17 at 11 30 32 AM

**Comment by oa-s** [comment]
@hboon do you mean to display full address always, even `ens` has resolved?

**Comment by hboon** [comment]
@oa-s yes.

**Comment by oa-s** [comment]
displaying ens + full  address brakes layout, line is too long for header, updating it with displaying only address, when header collapsed

**Comment by hboon** [comment]
@oa-s ok

**Pull request merged**
