### PR TITLE
Hide token label when display placeholder image, or load image via url #4463

### LINKED ISSUE #4463: Hide token label when display placeholder image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4463

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Can you help with (before/)after screenshots?

**Comment by oa-s** [comment]
| Before PR | After PR |
| -------- | --------- |
| IMG_5843 | IMG_5844 |

**Comment by hboon** [comment]
@oa-s I can't tell the difference. In before, it shows "Enjin" and "0", in after, it shows "Lost Relic" and "10". What's the thing that is hidden in after?

**Comment by hboon** [comment]
Hmm. Ok. I'll take your word for it :)

**Review by hboon — APPROVED** [review]

**Pull request merged**
