### PR TITLE
Adding custom RPC does not work #2911

### LINKED ISSUE #2911: Adding custom RPC does not work
I tried with this details below, which works on Metamask:

Fuse Network Details
    "name": "Fuse Mainnet",
    "chainId": 122,
    "shortName": "fuse",
    "chain": "FUSE",
    "network": "mainnet",
    "networkId": 122,
    "nativeCurrency": {"name":"Fuse","symbol":"FUSE","decimals":18},
    "rpc": ["https://rpc.fuse.io"],
    "faucets": [],
    "explorers": [https://explorer.fuse.io/],
    "infoURL": "https://fuse.io/"
 
I got the following error screen.
image

### PR DESCRIPTION
**Pull request by oa-s**
Closes #2911

### CODE REVIEW

**Comment by eviltofu** [comment]
What if the url has more then one `/` at the end?

**Comment by eviltofu** [comment]
@hboon @oa-s It appears that we might be trying to solve the wrong problem? The reason why the code originally fails is because of issues when trying to construct the url. Maybe we can use URL and URLComponents to safely construct it?

```swift
import Foundation

func constructUrlFrom(urlString: String) -> URL? {
    guard var url = URL(string: urlString) else { return nil }
    url.appendPathComponent("api")
    guard var urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: true) else { return nil }
    urlComponents.queryItems = [
        URLQueryItem(name: "module", value: "account"),
        URLQueryItem(name: "action", value: "tokennfttx"),
        URLQueryItem(name: "address", value: "0x007bEe82BDd9e866b2bd114780a47f2261C684E3"),
    ]
    return urlComponents.url
}

print(constructUrlFrom(urlString: "https://www.apple.com")!)
print(constructUrlFrom(urlString: "https://www.apple.com/")!)

https://www.apple.com/api?module=account&action=tokennfttx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3
https://www.apple.com/api?module=account&action=tokennfttx&address=0x007bEe82BDd9e866b2bd114780a47f2261C684E3
```

**Review by eviltofu — CHANGES_REQUESTED** [review]
See https://github.com/AlphaWallet/alpha-wallet-ios/pull/3639#issuecomment-1006362129

**Comment by oa-s** [comment]
@eviltofu i will create a new issue with `improve building Blockchain Explorer URL`

**Review by eviltofu — APPROVED** [review]

**Comment by hboon** [comment]
One of you merge it :) Either the reviewer does it or the reviewer makes sure the author knows he/she should merge it.

**Comment by hboon** [comment]
@oa-s can you help rebase and merge?

**Comment by oa-s** [comment]
@hboon this PR can be closed as `improve building Blockchain Explorer URL` #3677 has already merged

**Comment by hboon** [comment]
I see. Go ahead :)

**Pull request closed without merging**
