### PR TITLE
rename provider to AlphaWallet

### PR DESCRIPTION
**Pull request by James-Sangalli**
Old naming is now no longer valid

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli test broken

**Comment by James-Sangalli** [comment]
@hboon my tests are passing on my machine?

**Comment by hboon** [comment]
Hmm.. ServerTrustPolicyManager and ServerTrustPolicy are part of Alamofire, don't rename references to those :)

**Comment by hboon** [comment]
@James-Sangalli ServerTrustPolicyManager and ServerTrustPolicy are part of Alamofire

**Comment by hboon** [comment]
@James-Sangalli seems to have missed TrustProviderFactory in TrustProvider.swift

**Pull request merged**
