### PR TITLE
Text Fields redesign

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev is this considered more or less complete so I can review it or should I look at it as a WIP and post comments?

**Comment by vladyslav-iosdev** [comment]
lets for now look at it as a WIP

**Comment by hboon** [comment]
@vladyslav-iosdev I understand this is WIP, so you might already plan to do these, but anyway:

In the Send screen:

- [ ] the Paste button for address doesn't work until the address has been modified (or maybe unless the textfield is the first responder
- [ ] Can you swap the positions for the address textbox and amount textboxes?
- [ ] The amount textbox should show the US flag when it's in USD

In the Import Wallet (Watch) screen:

- [ ] the Clear button doesn't seem to work

Others:

- [ ] Include in the first comment of a PR "Closes #123" or "Fixes #123" depending on whether the PR is fixing a bug. The special keywords "closes" and "fixes" will let GitHub automatically close the issue when the PR is merged

- [ ] Can you make the 2 computed properies in SelectCurrencyButton private (maybe there's more?), since they are not used outside the class

- [ ] Generally order the variables this way:

private let/var

private let/var {computed}

let/var

let/var {computed}

- [ ] For colors, in general, can you use the colors from the asset catalog? They are named matching their names in Zeplin (e.g Danger), or use an existing constant (which ultimately points to the asset catalog color using R) so `static let textFieldStatus = UIColor.red` should not use `UIColor.red`. Feel free to define constants too (that map to the asset catalog using R, like you did with `DataEntry.Color.textFieldError`). There might be a few rare exceptions.

- [ ] Careful to text if fonts are usable in small screen like 5s. e.g `static let amountTextField = Fonts.regular(size: 36)`. Use `ScreenChecker().isNarrowScreen` as a test. Don't need to do this for most cases. Hard to maintain any way.

- [ ] Is AddressTextField.addressBookButton used?

- [ ] There are 2 textfields in SliderTextFieldCell too

Seems to look great generally and I appreciate that you adopt the conventions in the repo. Thanks!


Notes for Boon for later:

- [ ] Update look of Send screen

**Comment by vladyslav-iosdev** [comment]
> * [ ]  Is AddressTextField.addressBookButton used?
no, it now used, i saw in design there was address button, so i added it. i will remove it in next PR.

**Comment by vladyslav-iosdev** [comment]
> * the Paste button for address doesn't work until the address has been modified (or maybe unless the textfield is the first responder

I will check and fix it.

**Comment by vladyslav-iosdev** [comment]
> * [ ]  Can you swap the positions for the address textbox and amount textboxes?

ok

**Comment by vladyslav-iosdev** [comment]
> * [ ]  There are 2 textfields in SliderTextFieldCell too
 
@hboon can you tell me how can i get to screen where SliderTextFieldCell is using?

**Comment by hboon** [comment]
>> * [ ]  There are 2 textfields in SliderTextFieldCell too ...

@vladyslav-iosdev go to the send screen, enter an address and an amount and tap the green (send?) button. Then tap the gear button at the top right

**Comment by hboon** [comment]
>> * [ ]  Can you swap the positions for the address textbox and amount textboxes? ...

@vladyslav-iosdev don’t have to reply me for those :) I added those with checkbox so it’s easier for you to track them.

**Comment by vladyslav-iosdev** [comment]
> * The amount textbox should show the US flag when it's in USD

@hboon  can you provide this icon, i did not find it on design screens?

**Comment by vladyslav-iosdev** [comment]
@hboon how can i refill balance? i can't send tokens.

**Comment by hboon** [comment]
> @hboon how can i refill balance? i can't send tokens.

Send me a wallet address. I'll send you some testnet ETH, or you can switch to Ropsten (in the Browser tab, tap the top right button and choose "Connected to:") and visit https://faucet.ropsten.be.

**Comment by hboon** [comment]
> > * The amount textbox should show the US flag when it's in USD
> 
> @hboon can you provide this icon, i did not find it on design screens?

You can find it here: https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5e7879d750753b6d5a0e404a

**Comment by vladyslav-iosdev** [comment]
> > @hboon how can i refill balance? i can't send tokens.
> 
> Send me a wallet address. I'll send you some testnet ETH, or you can switch to Ropsten (in the Browser tab, tap the top right button and choose "Connected to:") and visit https://faucet.ropsten.be.

dont need for now, i find way to do that. thx!

**Comment by vladyslav-iosdev** [comment]
> > > * The amount textbox should show the US flag when it's in USD
> > 
> > 
> > @hboon can you provide this icon, i did not find it on design screens?
> 
> You can find it here: https://app.zeplin.io/project/5d088205bff2d15de6a4397b/styleguide/components?coid=5e7879d750753b6d5a0e404a

it says that "You’re not invited to this project". for now  i'm using ans@unicsoft.com account

**Comment by hboon** [comment]
@vladyslav-iosdev oh. We'll sort out the permissions. See if this works for you:

[us-flag.zip](https://github.com/AlphaWallet/alpha-wallet-ios/files/4651370/us-flag.zip)

**Comment by vladyslav-iosdev** [comment]
@hboon 
what about height for text field, do i need to inctease it, or left as it is?
do i need to update "Transaction data" tf?
Screenshot 2020-05-19 at 18 31 15
Screenshot 2020-05-19 at 18 31 21

**Comment by hboon** [comment]
@vladyslav-iosdev just what you have done looks fine fine. Keep the heights. Ignore transaction data. The entire screen will be replaced so don't waste too much time on it.

**Comment by hboon** [comment]
@vladyslav-iosdev I suppose this is superseded by #1816?

**Pull request closed without merging**
