### PR TITLE
Modifed code so that an error message is displayed if MFMailComposeViewController.canSendMail() returns false

### LINKED ISSUE #3807: When tapping Support > SendMail there is sometimes no response
```swift
        if MFMailComposeViewController.canSendMail() {
            let mc = getMFMailComposeViewController()
            mc.mailComposeDelegate = self

            for attachment in attachments {
                mc.addAttachmentData(attachment.data, mimeType: attachment.mimeType, fileName: attachment.fileName)
            }

            viewController.present(mc, animated: true)
        }
```
If `MFMailComposeViewController.canSendMail()` returns false, there is no feedback to the user.

Proposed show a message "Your device isn't configured to send email".

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #3807 

@oa-s @hboon 

Does anyone know how to trigger `HelpContentsViewController` and `HelpViewController` are in the app? I can't find them to test. The one spot I know where to test is below:

Settings > Support > Email

Screen Shot 2022-01-28 at 3 54 13 PM

### CODE REVIEW

**Comment by hboon** [comment]
> Does anyone know how to trigger HelpContentsViewController and HelpViewController are in the app? I can't find them to test. > The one spot I know where to test is below:

@eviltofu seems like it's no longer used with #2588. Can you help verify and remove the code if it isn't used anymore?

**Comment by oa-s** [comment]
yeah, that part was replaced with web view representation

**Comment by eviltofu** [comment]
```swift
class WhatIsEthereumInfoViewController: HelpContentsViewController {
    override var url: URL? {
        return R.file.whatIsEthereumInfoHtml()
    }
}
```
is still used by `TokensCardCoordinator.swift:407`
```swift
   private func showViewEthereumInfo(in viewController: UIViewController) {
        let controller = WhatIsEthereumInfoViewController(delegate: self)
        controller.navigationItem.largeTitleDisplayMode = .never

        viewController.navigationController?.pushViewController(controller, animated: true)
    }
```
@oa-s @hboon 

I've eliminated the following:

 `HowDoIGetMyMoneyInfoViewController`, `HowDoITransferETHIntoMyWalletInfoViewController`, `PrivacyPolicyViewController`, and `TermsOfServiceViewController`.

**Comment by hboon** [comment]
@eviltofu will check. But if you removed it as part of this PR, can you move it out? Sorry, I wasn’t clear.

**Comment by eviltofu** [comment]
> @eviltofu will check. But if you removed it as part of this PR, can you move it out? Sorry, I wasn’t clear.

Move what out? @hboon

**Comment by hboon** [comment]
> > @eviltofu will check. But if you removed it as part of this PR, can you move it out? Sorry, I wasn’t clear.
> 
> Move what out? @hboon

I was referring to this:

> seems like it's no longer used with #2588. Can you help verify and remove the code if it isn't used anymore?

Can you do it in a separate PR and not here.

**Review by hboon — APPROVED** [review]

**Pull request merged**
