### PR TITLE
ADD PHI NETWORK RPC

### PR DESCRIPTION
**Pull request by Phinetwork**
ADDED PHI NETWORK TO RPC ALREADY ADDED TO ANDROID VERISION

If bug:
Fixes #

If not a bug:
Closes #

1-liner summary:

Details if any (this should probably be in the commit message too):

Screenshots of Before PR and After PR if it's applicable (sometimes this make it much faster/easier to review):

Anything particular to test:

### CODE REVIEW

**Comment by hboon** [comment]
@Phinetwork there are a few more changes needed:

* Would you help to fix the indentations and the errors (some missing strings and images)?
* There are other files that need to be modified (you can find them by building and looking at the compilation errors)

Alternatively, if you like, grant me write access to your repo https://github.com/Phinetwork/alpha-wallet-ios and I can chip in directly.

**Comment by Phinetwork** [comment]
ok great thank you for the information and your help we have added you to the repo appreciate your assistance.

**Comment by hboon** [comment]
> ok great thank you for the information and your help we have added you to the repo appreciate your assistance. can help how ever you would like just let me know what lines to fix but gave access to make easy so you can go ahead and fix thank you.

Thanks. Got the invite. I'll look into it and reply here if there's anything else we'll need.

**Comment by Phinetwork** [comment]
Great thank you.

**Comment by hboon** [comment]
Have updated the PR. @oa-s would you help do a check and merge? 

@Phinetwork would you help give us a mention in https://docs.phi.network/phi-wiki/use-phi-smart-chain/compatible-wallets/create-smart-chain-wallet/additional-wallets-setup?

**Comment by Phinetwork** [comment]
For Sure We Will Be Highlighting Alpha Wallet To Users As The Go To Wallet For PHI Network. Is it possible you Can Also Add Pricing Api For Prices Show UP That pull from https://info.phiswap.com ? can send you API for price to add

**Comment by hboon** [comment]
> For Sure You can check it has been updated. Highlighted Alpha Wallet To Users As The Best Alternative Go To Wallet For PHI Network on the page requested. Is it possible you Can Also Add Pricing Api For Prices Show UP That pull from https://info.phiswap.com ? can send you API for price to add.
> 
> Also was the logo added or do you need a logo url?

I have added the logo into the PR.

For pricing API, would you help to create a new issue (or PR if you like) and we can look at it separately? This PR as it is can be merged by itself.

**Comment by Phinetwork** [comment]
> 

Ok Great Yes will create a new pull request for api thank you

**Review by hboon — APPROVED** [review]

**Comment by Phinetwork** [comment]
Thanks for the merge Two questions

what file is the price api for change?

 and when can we expect the update to reflect on the app?

**Comment by hboon** [comment]
> Thanks for the merge Two questions
> 
> what file is the price api for change?

It depends on how the API is like. Can you help create an issue with how the API works?

> and when can we expect the update to reflect on the app? @hboon

We just did a release yesterday, next one might be 2-3 weeks time.

**Comment by Phinetwork** [comment]
> > Thanks for the merge Two questions
> > what file is the price api for change?
> 
> It depends on how the API is like. Can you help create an issue with how the API works?
> 
> > and when can we expect the update to reflect on the app? @hboon
> 
> We just did a release yesterday, next one might be 2-3 weeks time.

Ok Great Thanks For The Information & Updated Have Created A New Issue. Thanks Again.

**Pull request merged**
