### PR TITLE
Added dark mode to FungibleTokenViewController under Test mode

### PR DESCRIPTION
**Pull request by eviltofu**
Switch to Testnet mode. In main wallet tab, tap ETH.

Before PR | Light mode | Dark mode
-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-10-12 at 19 46 56 copy | Simulator Screen Shot - iPhone 14 Pro - 2022-10-12 at 19 45 34 copy | Simulator Screen Shot - iPhone 14 Pro - 2022-10-12 at 19 45 36 copy

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
There is already #5518 which adds dark mode to FungibleTokenViewController. Maybe update the title/commit message to reflect that it's for test mode, if that's what this PR does?

Then update the screenshots for before and after the PR in Dark mode. The light mode version seems unnecessary (but you are free to include it for comparison)

**Comment by eviltofu** [comment]
> Then update the screenshots for before and after the PR in Dark mode. The light mode version seems unnecessary (but you are free to include it for comparison)

The before dark mode shot just looks broken with some text fields not showing the correct dark background. Do you still want that? @hboon

**Comment by hboon** [comment]
@eviltofu commit message too?

**Comment by eviltofu** [comment]
@hboon commit message updated.

**Review by hboon — APPROVED** [review]

**Pull request merged**
