### PR TITLE
Set token icons loading priority order: `.alphaWallet`, `OpenSea`, `.thirdParty` #3828

### LINKED ISSUE #3827: Hardcode a new Collection picture for the Enjin ERC1155 token
https://zpl.io/VqrDmol

### LINKED ISSUE #3828: Hardcode a new Collection picture for ENS token
https://zpl.io/VqrDmG5

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3828,  Closes #3827

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s we don't have to bundle the images :) Just upload the big version of the token icon to the `iconassets` repo and update the code to check against the repo (but not the other repo) first before checking against OpenSea. Refer to https://github.com/AlphaWallet/alpha-wallet-ios/issues/3827#issuecomment-1023279563 and the comments after it.

**Comment by hboon** [comment]
@oa-s I think this line: https://github.com/AlphaWallet/alpha-wallet-ios/blob/014654118f6538089ca3b05445b84e8dcac3d476/AlphaWallet/UI/TokenObject+UI.swift#L201

**Comment by hboon** [comment]
I pushed the WIP/test code to https://github.com/AlphaWallet/alpha-wallet-ios/tree/load-token-image-from-github-first-then-opensea. In case it helps (and careful with the `//hhh`s. Not that this version still loads from both GitHub before OpenSea. But we actually want to only read from `iconassets` first, then OpenSea, then finally the other GitHub repo.

**Comment by eviltofu** [comment]
@oa-s How do I test this?

**Review by hboon — CHANGES_REQUESTED** [review]
Changes required. In case @oa-s missed it

**Comment by oa-s** [comment]
Checking for GitHub before OpenSea could cause a lot of  `SPAM`  icons appearing , is that is ok?

**Comment by oa-s** [comment]
Continue after https://github.com/AlphaWallet/iconassets/pull/11 https://github.com/AlphaWallet/iconassets/pull/10 will be merged

**Comment by hboon** [comment]
> Checking for GitHub before OpenSea could cause a lot of `SPAM` icons appearing , is that is ok?

SPAM because our GitHub repo includes a token icon like https://github.com/AlphaWallet/iconassets/commit/dd66c1ad06379b5e350874a03e60db687a361539 ? Then it's fine; ideally when it does that, we ought to consider it as spam and not override it with OpenSea's.

**Comment by hboon** [comment]
Actually we should probably make https://github.com/AlphaWallet/tokens/blob/main/tokens.json include an `isSpam` flag.

**Review by hboon — COMMENTED** [review]
Does this PR fetch the icons in this order (it should)?

* GithubAssetsURLResolver.Source.alphaWallet 
* OpenSea
* GithubAssetsURLResolver.Source.thirdParty 

It used to be:

* OpenSea
* GithubAssetsURLResolver.Source.alphaWallet
* GithubAssetsURLResolver.Source.thirdParty

**Comment by oa-s** [comment]
> It used to be:

yes, we do it in the next order:
* OpenSea
* GithubAssetsURLResolver.Source.alphaWallet
* GithubAssetsURLResolver.Source.thirdParty

**Comment by hboon** [comment]
Yeah. But we want it to be this instead:

* GithubAssetsURLResolver.Source.alphaWallet
* OpenSea
* GithubAssetsURLResolver.Source.thirdParty

**Comment by hboon** [comment]
> Continue after [AlphaWallet/iconassets#11](https://github.com/AlphaWallet/iconassets/pull/11) [AlphaWallet/iconassets#10](https://github.com/AlphaWallet/iconassets/pull/10) will be merged

Done.

**Comment by hboon** [comment]
BTW, can you help to update the commit message and PR title?

**Comment by oa-s** [comment]
| Before PR | After PR |
| -------- | -------- |
||
|||

**Review by hboon — APPROVED** [review]

**Pull request merged**
