### PR TITLE
Restrict token symbol to half screen width to avoid broken amount text field view #6185

### LINKED ISSUE #6185: Make sure amount textfield and All Funds button always show up and works even if the token symbol is too long
Symbol is probably too long? https://blockscout.com/xdai/mainnet/address/0xA68b7779504b0AE372ddCC109f8786DB9B91e93e

&nbsp;| &nbsp;| &nbsp;
-|-|-
|vs|Screenshot 2023-01-19 at 9 53 08 AM

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6185

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Seeing this on iPhone 14 Pro iOS 16.2:

Screenshot 2023-01-25 at 8 25 42 AM

**Review by hboon — APPROVED** [review]
The little down arrow button to switch between crypto and fiat doesn't appear, but I guess it's ok since all (or at least most) crypto-fiat pairs should not have such a long symbol.

Can you help verify on a narrow device to see it works properly? I see it shows "1.23456" without truncating (it would truncate "silently" if there's 1 more digit, so would not be good if it's too narrow) on iPhone 14 Pro.

**Comment by hboon** [comment]
> maybe its not available, i mean switching beetwen fiat, then its hidden, or you able to toogle beetwen currencies?

Oh, I forgot it's hidden if fiat rates aren't available. I hardcoded it to have a rate and it appears. All good.

Does the All Funds button display correctly with narrower devices?

**Comment by oa-s** [comment]
> Does the All Funds button display correctly with narrower devices?

yes, still good

**Review by hboon — APPROVED** [review]
Haven't retested. But look good earlier.

**Pull request merged**
