### PR TITLE
Improve the total amount change color in the Wallet tab #3165

### LINKED ISSUE #3165: Improve the total amount change color in the Wallet tab
In the #2273, I explained what this should be. Maybe not clear enough.

I conducted 3 tests using usabilityhub:
1) https://app.usabilityhub.com/tests/86ec06814d57/results/1f78709fe6f1

Screenshot 2021-07-08 at 11 23 29

2) https://app.usabilityhub.com/tests/6076f465a67c/results/590f397ceee6

Screenshot 2021-07-08 at 11 23 39

3) https://app.usabilityhub.com/tests/bcdef3f68e73/results/420f2f243df1

Screenshot 2021-07-08 at 11 23 49

and the result is that they understand if the number you marked is the ‘24H Price change’ of the ‘how much your 
tokens are worth in USD’ (5% x 1500 USD). This is also the same as Delta app, Zerion App, Blockfolio. So the winner was 2)

@zhangzhongnan928 @hboon 
The trigger to open AlphaWallet and check wallet tab should be: **tell me how much money I gained/lost in last 24h**. There are other tools to check the market prices. And if you are looking for that data, open a token and you will find numbers like ETH price. 

So if **1 ETH = 1000 USD** and the ** ETH price raised by 5%** in last 24H then it should like this:

Screenshot 2021-07-08 at 11 16 29

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3165

### CODE REVIEW

**Review by hboon — APPROVED** [review]
Didn't check :)

**Comment by vladyslav-iosdev** [comment]
a few things has left to done

**Comment by vladyslav-iosdev** [comment]
btw i a little bit confised with what should be here?
Screenshot 2021-09-09 at 09 29 56
currently there is `value change` but out of here 
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2894#issue-919990829 there should be market price,

**Comment by hboon** [comment]
Assume

1 ETH = $1000 (from CoinGecko) API
5% 24h change (from CoinGecko) API
Assume 1.5 ETH in wallet

So we display "1.500 ETH"
and "5%"
and hence total fiat value = 1.5 * 1000 =  1500 -> display "$1500.00"
and hence the fiat gain = 1500 * 5% -> display "$75.00"

Does that answer your question?

**Comment by vladyslav-iosdev** [comment]
> Does that answer your question?

thanks for explanation ;)

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
@vladyslav-iosdev would you help fix the tests (if it's relevant to this PR) and then merge?

**Pull request merged**
