### PR TITLE
Resolve realm memory leaks #4621

### LINKED ISSUE #4621: Resolve realm memory leaks
For some reasons creating a copy of realm objects causes memory leaks. Especially with `Balance` instances.

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4621

### CODE REVIEW

**Review by hboon — APPROVED** [review]
I see some refactoring/renaming. But what was the problem?

**Comment by oa-s** [comment]
We got here a memory leak issue, when we make a new copy of realm object (like we did with detached() ) the instances don't get deleted. Even if we don't have manual strong ref to them. Is especially related to token, and tokenBalance. After passing some time, after apps launch, there is more than 10k Token balances, and from 1-2k token objects.

**Comment by oa-s** [comment]
Renaming it's mostly related of what we passing, token as(activity.token) or tolenObject

**Comment by oa-s** [comment]
Guess that passing structs peer the app should be better

**Review by hboon — APPROVED** [review]
OK. Trust you tested :)

**Pull request merged**
