### PR TITLE
Make ERC721/ERC1155 token image with rounded corners #4585

### LINKED ISSUE #4585: Make ERC721/ERC1155 token image with rounded corners
Is it possible to make the image with rounded corners as it is on Opensea?
Screenshot 2022-05-12 at 10 22 30

**Opensea**

### PR DESCRIPTION
**Pull request by oa-s**
Closes #4585

### CODE REVIEW

**Comment by oa-s** [comment]
Doesn't work for image: **https://tdbc.mypinata.cloud/ipfs/QmXFNzB7vyvKcdgUTZXbEwSRMkkvGEBcgbuprhHXcXCHwg**

**Comment by hboon** [comment]
Does it work reliably for SVGs too? i.e does it end up rounding the corners of whitespace around the content and the content not rounded? (We don't want that)

Would be good to keep them square or fix it for the placeholder image. It's also used while loading the actual image:

Screenshot 2022-05-20 at 1 34 51 PM

Need margins for this, but maybe it's meant for #4584 :

Screenshot 2022-05-20 at 1 36 56 PM

**Comment by oa-s** [comment]
rounding for svg handling via css style, so it should be rounded.

**Comment by oa-s** [comment]
rounding for placeholder was added manually, removing it

**Comment by oa-s** [comment]
> Need margins for this, but maybe it's meant for https://github.com/AlphaWallet/alpha-wallet-ios/issues/4584 : 

checking it

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Review by hboon — APPROVED** [review]
Thanks!

**Pull request merged**
