### PR TITLE
[Samoa] Modify Wallet tab cells look and feel (no group/section) #2754

### LINKED ISSUE #2754: [Samoa] Modify Wallet tab cells look and feel (no group/section)
Just the cells, no grouping/sections

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/6045ee59577f8ba371b3deac

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2754

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
NFT token cell not changed yet

**Comment by hboon** [comment]
@vladyslav-iosdev yeah, change NFTs too. It looks like this (CBF and CK) at the moment:

Screenshot 2021-05-21 at 10 35 50 PM

**Comment by vladyslav-iosdev** [comment]
@hboon this one is ready for review.

**Review by hboon — APPROVED** [review]
Looks good. Didn't merge since marked as WIP.

**Comment by colourfreak** [comment]
Quick feedback.

a) We did a user test in the past where we a/b test the right part. What I marked here:

Screenshot 2021-06-04 at 12 42 50

should not display the current market price, but the price change in USD in the last 24h. 

b) https://zpl.io/aRnNBnz the bottom part, where we have "1.503 ETH" should be 15pt. The same to the part on the right with the price change. Make it larger - 15 pt. 

c) the place where we have "2.53%" is currently in the brackets. Shouldn't be. And make it larger - 15pt.

**Comment by hboon** [comment]
@colourfreak could you help to create a new issue with this comment and mention this issue number? Clearer

**Comment by colourfreak** [comment]
> @colourfreak could you help to create a new issue with this comment and mention this issue number? Clearer

https://github.com/AlphaWallet/alpha-wallet-ios/issues/2273

**Pull request merged**
