### PR TITLE
Added dark mode to AddHideTokenViewController

### PR DESCRIPTION
**Pull request by eviltofu**
On the main wallet screen, tap the ellipses (…). Tap Add/Hide Tokens.

Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 18 copy 2 Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 26 copy 2

Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 46 copy 2 Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 40 copy 2

Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 54 copy 2  Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 09 58 copy 2

Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 10 11 copy 2 Simulator Screen Shot - iPhone 12 - 2022-09-19 at 17 10 06 copy 2

### CODE REVIEW

**Comment by hboon** [comment]
@eviltofu will check, but can you help reword the commit and PR to refer to the screens rather than the classes, since it’s applicable?

**Review by hboon — COMMENTED** [review]
> can you help reword the commit and PR to refer to the screens rather than the classes, since it’s applicable?

@eviltofu remember to reword the commit message too

Not sure if it's specific to this screen (if not, merge this and fix in a separate PR), but these 2 lines should gone in Dark mode too:

Screenshot 2022-09-20 at 1 30 34 PM

**Comment by eviltofu** [comment]
Simulator Screen Shot - iPhone 12 - 2022-09-24 at 00 01 50 copy 2 Simulator Screen Shot - iPhone 12 - 2022-09-24 at 00 01 44 copy 2

**Comment by hboon** [comment]
@eviltofu need to buzz me if it's good to review + merge

**Comment by hboon** [comment]
I did a quick check. Wallet tab seems broken:

Screenshot 2022-09-24 at 2 35 33 PM

and if you scroll down in Add/Hide Tokens:

Screenshot 2022-09-24 at 2 36 01 PM

tap on the "Auto" (top right button of Add / Hide Tokens):

Screenshot 2022-09-24 at 2 36 52 PM

**Comment by eviltofu** [comment]
I think I've fixed these.

image
image
image

**Comment by hboon** [comment]
Force-pushed after rebase master

**Review by hboon — APPROVED** [review]

**Pull request merged**
