### PR TITLE
Fix app crashing when trying to generate a link when private key unavailable #6114

### LINKED ISSUE #6114: Fix app crashing when trying to generate a link when private key unavailable

### PR DESCRIPTION
**Pull request by oa-s**
Fixes #6114

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
@oa-s Can you describe how you reproduce the crash and which wallet and NFT contract + tokenId?

Note to self from Boon: I get a crash with an ExpansionPunks both before and after the PR. Want to know if it's a different problem

**Comment by oa-s** [comment]
steps: 
- set flag `shouldPretendIsRealWallet = true`
- watch tomek.eth wallet
- enabled xDai chain, and look for `Tickers` collection
- open any item `Tickers` 
- tap sell
- go forvard for generation url link
- tap `generate` 

**expectation**:
- app displays an error

**actual**
- app crashes with error `accountMayNeedImportingAgainOrEnablePasscode`

**Comment by oa-s** [comment]
@oa-s can u show error you got?

**Comment by hboon** [comment]
@oa-s it doesn't crash anymore with 39b117bdc2249645498b7aa747a5f39136f7b515, but I get this:

Screenshot 2023-01-11 at 10 42 06 PM

**Comment by oa-s** [comment]
@hboon can u try it one more time?

**Comment by hboon** [comment]
Not crashing anymore. Thanks.

But maybe an unrelated problem: If we hardcode `generateSellLink(tokenHolder:,linkExpiryDate:,ethCost:,server:)` to return a URL string and then proceed to share, tapping on `Messages` does nothing. Console says:

> [MFMessageComposeViewController] Unable to initialize due to + [MFMessageComposeViewController canSendText] returns NO.

So maybe it's not a problem. But I thought it worked previously, the Messages sharing sheet at least popped up.

**Comment by oa-s** [comment]
> > [MFMessageComposeViewController] Unable to initialize due to + [MFMessageComposeViewController canSendText] returns NO.
> 
> So maybe it's not a problem. But I thought it worked previously, the Messages sharing sheet at least popped up.

but we displaying `UIActivityViewController` and not `MFMessageComposeViewController`

**Comment by hboon** [comment]
Yes, it should show it after we tap to share via Messages in the sharing sheet. But maybe it’s only a problem on simulator?

**Comment by oa-s** [comment]
yes, that is only on simulator, works on real device

**Comment by hboon** [comment]
Good enough :) thanks.

**Pull request merged**
