### PR TITLE
Added dark mode to FungibleTokenViewController

### PR DESCRIPTION
**Pull request by eviltofu**
Main wallet tab > Ethereum 

From created Wallet
Before PR | Light mode | Dark mode
-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 12 24 50 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 10 39 56 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 10 42 50 copy 2

From watched Wallet
Before PR | Light mode | Dark mode
-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 12 20 58 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 10 41 03 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 10 41 09 copy 2

From created Wallet
Before PR | Light mode | Dark mode
-|-|-
Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 12 28 54 copy 2 |  Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 12 33 33 copy 2 | Simulator Screen Shot - iPhone 14 Pro - 2022-10-07 at 12 34 54 copy 2

Push button animation below:

Simulator Screen Recording - iPhone 14 Pro - 2022-10-07 at 10 39 40

### CODE REVIEW

**Comment by hboon** [comment]
@eviltofu please read https://github.com/AlphaWallet/alpha-wallet-ios/pull/5510#pullrequestreview-1132240894 and ping again when it's done. Thanks

**Comment by eviltofu** [comment]
@hboon updated

**Review by hboon — APPROVED** [review]
Seems OK, but can you make it pass the test (it builds with Xcode 14 but not Xcode 13) before merging?

**Comment by eviltofu** [comment]
> Seems OK, but can you make it pass the test (it builds with Xcode 14 but not Xcode 13) before merging?

Which tests? Right now there appears to be some tests that always seem to fail in the `make test`.

**Comment by hboon** [comment]
Build vs pass.

Refer to this: https://app.travis-ci.com/github/AlphaWallet/alpha-wallet-ios/jobs/584978516

Make it build (not pass the test, though that would be good) on Xcode 13.

About passing the tests, they (before the PR) always passes for me on Xcode 14 locally. It's just more problematic on Travis.

**Comment by hboon** [comment]
@eviltofu I presume this is done? In the future please ping here if it's good to merge/check again? Less ambiguous.

**Pull request merged**
