### PR TITLE
Add handling gesture cancelation when popping view controller #5145

### LINKED ISSUE #5145: Add handling gesture cancelation when popping view controller

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5145

### CODE REVIEW

**Comment by hboon** [comment]
@oa-s can you describe what this does? Is it testable in the simulator and which screen?

**Comment by hboon** [comment]
Boon remind self:

- [ ] #5148
- [ ] #5150

**Comment by oa-s** [comment]
@hboon  this pr resolves next issue: when tap on back button or make swipe action we immediatelly receive callback
    `override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        if isMovingFromParent || isBeingDismissed {
            delegate?.didClose(in: self)
        }
    }`

and remove coordinator or do some actions.

this behaviour is ok for tapping back button, but when we do swipe, we might don't close view controller, and just cancel swipe event, and as result we will get removed coordinator, but view controller still will be in vcs hierarchy.

**Comment by oa-s** [comment]
> Is it testable in the simulator and which screen?

yes, just make sure you have checked `Window -> Show Device Bezels` on simulator, to being able to make swipe

**Comment by hboon** [comment]
> > Is it testable in the simulator and which screen?
> 
> yes, just make sure you have checked `Window -> Show Device Bezels` on simulator, to being able to make swipe

Wow. I had no idea! Thanks :)

**Review by hboon — APPROVED** [review]

**Pull request merged**
