### PR TITLE
If the message to sign is very long for personal_sign, it isn't displayed correctly #2455

### LINKED ISSUE #2455: If the message to sign is very long for personal_sign, it isn't displayed correctly
Test: https://danfinlay.github.io/js-eth-personal-sign-examples/

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2455

### CODE REVIEW

**Comment by hboon** [comment]
Oh. My bad. It's broken on the simulator only. Pre-PR, it shows up on the device, although after a long time. Does this PR make it appear faster?

**Comment by hboon** [comment]
Even after applying the PR, it shows up as blank on the simulator for iOS 12.4

**Comment by hboon** [comment]
Related: #2497. So you can see if you still want to go ahead with this PR or switch to that.

**Comment by vladyslav-iosdev** [comment]
> Related: #2497. So you can see if you still want to go ahead with this PR and handle it later or switch to it right away

@hboon That is really strange but when i am trying to check this issue, nothing happens. When I open URL in dapp browser, tap `sign`  nothing happens, `didCall(action:` doesn't get called.

**Comment by vladyslav-iosdev** [comment]
@hboon  Also what i found that when i run app on iPhone X 12.4, and tapped create a new wallet, application stuck on seed phrase check

**Comment by vladyslav-iosdev** [comment]
@hboon i found that for iOS version 12.4 large text couldn't be displayed,  but it could be fixed with replacing it with `UITextView` instead.

**Comment by hboon** [comment]
@vladyslav-iosdev good for review?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev good for review?

yep, please check it.

**Review by hboon — APPROVED** [review]

**Pull request merged**
