### PR TITLE
Add option to switch network in active WalletConnect session #3383

### LINKED ISSUE #3383: Add option to switch network in active WalletConnect session
QR_WalletConnect_Zerion_Switch
QR_WalletConnect_Zerion

https://zpl.io/bJ6EPM3
https://zpl.io/2935mjY

### LINKED ISSUE #3395: Check if possible to switch network for active WalletConnect session
Refer to #3384

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3383, Closes #3395

### CODE REVIEW

**Review by hboon — CHANGES_REQUESTED** [review]
Ah great! It really is possible :)

- [x] But we need to update the network value displayed after switching. It only updates if we pop and push it again (the "Network" value in the screenshot)

Screenshot 2021-11-01 at 11 23 25 AM

**Comment by vladyslav-iosdev** [comment]
> * [ ]  But we need to update the network value displayed after switching. It only updates if we pop and push it again (the "Network" value in the screenshot)
> 

hmm, suppose it works not perfectly, it was working for me.

**Comment by hboon** [comment]
@vladyslav-iosdev does it wait for a response before updating? Maybe I didn't wait long enough?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev does it wait for a response before updating? Maybe I didn't wait long enough?

yes it does. just a sec, will push changes

**Pull request merged**
