### PR TITLE
[Refactoring] rename cancelable with cancellable

### PR DESCRIPTION
**Pull request by oa-s**

### CODE REVIEW

**Comment by oa-s** [comment]
too many files, but not critical changes, just var renaming

**Review by hboon — COMMENTED** [review]
@oa-s "cancellable" is British spelling so it's fine if you prefer to keep it.

**Comment by hboon** [comment]
Oh, you renamed it. Then: "cancelable" is fine too, since it's American :)

**Comment by oa-s** [comment]
oh, that we can close it

**Pull request closed without merging**
