### PR TITLE
add `eth_signTypedData_v4` as key variation for eth_signTypedData

### LINKED ISSUE #6341: iOS - Error showed on Alpha Wallet after connecting to Bogota Passive using WC v2
name: Bug Report
about: Occurs only on iOS Alphawallet

---

**Describe the bug**
Error showed on Alpha Wallet after connecting to Bogota Passive using WC v2, Eth/Polygon main net.

**Steps to reproduce (REQUIRED)**
1. Go to ticket issuer to create a ticket https://tokenscript.github.io/token-negotiator-examples/ticket-issuer-url-website/
2. Open https://tokenscript.github.io/token-negotiator-examples/hotel-bogota-passive-negotiation-website/
3. Click Book
4. Select Ticket and complete Attestation
5. Click WalletConnect v2
6. Scan QR code and confirm in Alpha wallet

**Expect**
Alpha Wallet connected via WC v2

**Observed**
Error showed on Alpha Wallet after connecting

**Screenshots**
image

**Version or build number number**
3.61 (iOS)

**Additional context (Error Messages, etc.)**

### PR DESCRIPTION
**Pull request by oa-s**
Closes #6341

### CODE REVIEW

**Comment by oa-s** [comment]
attestation sends `eth_signTypedData_v4` method instead of `eth_signTypedData`

**Comment by hboon** [comment]
You mean fixing the other ticket too?

**Comment by oa-s** [comment]
or you know maybe i did something wrong, any way this one shoule fix issue with wallet connect

**Review by hboon — APPROVED** [review]
OK, looks good.

**Pull request merged**
