### PR TITLE
Added iOS 16 target to Makefile, corrected iOS versions for iOS 15 test. Updated phone models in tests.

### PR DESCRIPTION
**Pull request by eviltofu**
Added `make test16` target to run tests under iOS 16 and iPhone 14. Corrected some iOS version errors under Xcode 14.

Supersedes #5509.

### CODE REVIEW

**Comment by hboon** [comment]
@eviltofu is this ready?

**Comment by eviltofu** [comment]
No, let me think a bit on this. This needs to work under Xcode 13 as well as Xcode 14.

**Comment by hboon** [comment]
Low priority

**Comment by eviltofu** [comment]
Superseded by #5735. Should I close this?

**Pull request closed without merging**
