### PR TITLE
Tweak and standardize text inputs. Update text fields and views to have same method of creating, add support of inputAccessoryButtonType for each text inputs, handle when next and done buttons selected. #5800

### LINKED ISSUE #5785: Most of the accessory button with the "Done" title should be "Next" and they should scroll to review the first responder
- [ ] The accessory button should all be "Next" instead of "Done" except when the Nonce textbox is focused
- [ ] Tapping "Next" should scroll to reveal the textbox that will be become the first responder

### LINKED ISSUE #5800: Tweak and standardize text inputs. Update text fields and views to have same method of creating, add support of `inputAccessoryButtonType` for each text inputs, handle when next and done buttons selected.

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5800, Closes #5785

### CODE REVIEW

**Comment by oa-s** [comment]
PR is quite big

**Review by hboon — COMMENTED** [review]
Maybe start with "[Refactoring]" ?

**Review by hboon — APPROVED** [review]
Didn't check extensively, but idea is good :)

I forgot if it was fixed before this PR (or will be separate), but the button in "Set Speed" screen for gas for the Nonce textbox should be "Done", not "Next"

Screenshot 2022-11-12 at 11 28 35 AM

**Comment by oa-s** [comment]
@hboon pr is ready for review

**Comment by hboon** [comment]
@oa-s I might be crazy, but was the "Transaction Data (Optional)" field hidden prior to this PR (see the previous screenshot)?

Screenshot 2022-11-16 at 11 42 30 AM

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
Haha

**Pull request merged**
