### PR TITLE
Updated illustrations with light and dark mode pdfs

### LINKED ISSUE #5041: Update Illustrations in Dark Mode
Zeplin:
https://zpl.io/g8XXlED

I made two groups:
- Dark
- Light

**Screen Shot 2022-07-25 at 09 20 32**

Screen Shot 2022-07-25 at 09 20 26

### PR DESCRIPTION
**Pull request by eviltofu**
Closes #5041

There are 9 images from illustrations used in the app but one of them (activities_empty_list) has no dark mode counterpart. The images were replaced by manually scanning the `Assets.xcassets` file.

There are however some more images in Zeplin which are **NOT** in the app.
 
## List of light illustrations
https://zpl.io/DlrEg4O

## List of dark illustrations
https://zpl.io/404mNvz

## Replaced images
There are two images which do not have screen shots here. The first is `activities_empty_list` and the second is `biometric-lock`. There is no dark mode counterpart for `activities_empty_list `. I could not find where in the app the view controller displaying `biometric-lock` is activated in the simulator. 

### activities_empty_list
There is no dark mode counterpart so this image was not replaced or updated.
https://zpl.io/kDNyZXG

### alerts_empty_list
Light | Dark
-|-
alerts_empty-light|alerts_empty-dark

### biometric-lock
I can't find this.

### conversionDaiSai
Light | Dark
-|-
conversionDaiSai-light|conversionDaiSai-dark

### empty_list
Light | Dark
-|-
empty_list-light|empty_list-dark

### hd-introduction
Light | Dark
-|-
hd-introduction-light|hd-introduction-dark

### iconsIllustrationsAnalytics, iconsIllustrationsCrashReporting
Light | Dark
-|-
iconsIllustrationsAnalytics-light|iconsIllustrationsAnalytics-dark

### iconsIllustrationsEmptyWalletConnect
Light | Dark
-|-
iconsIllustrationsEmptyWalletConnect-light|iconsIllustrationsEmptyWalletConnect-dark

### showSeedPhraseIntroduction
Light | Dark
-|-
showSeedPhraseIntroduction-light|showSeedPhraseIntroduction-dark

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
You had to generate the illustrations yourself?

**Comment by eviltofu** [comment]
> You had to generate the illustrations yourself?

No, they are all in Zeplin. The screen shots I had to generate.

**Review by hboon — COMMENTED** [review]
Ok. Looks OK from screenshots.

**Comment by eviltofu** [comment]
So approved for merge?

**Review by hboon — APPROVED** [review]
> So approved for merge despite the missing screen shot for biometric-lock?

Yes. (but I didn't notice it. Just looked at the screenshots).

**Pull request merged**
