### PR TITLE
Support for update WalletConnect v2 SDK #3989

### LINKED ISSUE #3989: Support for update WalletConnect v2 SDK
- [ ] List changes, what we can readily do (eg. push would need some planning and to decide if we can support it)
- [ ] Implement what we can quickly
- [ ] Decide for the rest

### PR DESCRIPTION
**Pull request by oa-s**
Closes #3989

### CODE REVIEW

**Comment by oa-s** [comment]
The WalletConnect v2 has updated up to 0.5.0 version
Replacements: 
- refactored accounts `Set<String>` with updated model `Account`, now its `Set<Account>` ref: https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md
- push notifucations not implemented!

**Comment by hboon** [comment]
Ok. Buzz me if there's anything you want me to review. About push notifications, could you describe (maybe another issue?) what we need to do to support it and what it's for? And we can see how/when we can do it.

**Comment by oa-s** [comment]
sure, let me explore a bit more about push notifications implementation.

**Comment by hboon** [comment]
With this build, after I followed these steps https://github.com/AlphaWallet/alpha-wallet-ios/issues/3871#issue-1125459344 to connect to a new session, and confirm to connect in the AlphaWallet actionsheet, the dapp still shows this screen:

Screenshot 2022-03-04 at 11 14 53 AM

It worked as expected with master (4af030b2bb8c50d11874b81ec25fd698b5f529bb).

**Comment by oa-s** [comment]
> Ok. Buzz me if there's anything you want me to review. About push notifications, could you describe (maybe another issue?) what we need to do to support it and what it's for? And we can see how/when we can do it.

the lib was updated up to 0.5.0 version, updated code (types mismatching) and so on. According to the Push notification can't answer, as i can't find any details fori its implementations. more explorations is needed

**Review by hboon — APPROVED** [review]
Ok. Thanks. We can write the issue for push (or a list of functionality later). Better get this merge first.

**Pull request merged**
