### PR TITLE
with new api route for infura

### PR DESCRIPTION
**Pull request by James-Sangalli**
WIP until error fixed or we move node provider 

For #731

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli good job!

**Comment by James-Sangalli** [comment]
@hboon that should happen since the id is there and actually the ether balances won't show in the wallet key view with that link. It boggles my mind since everything is correct.

**Comment by hboon** [comment]
@James-Sangalli Oh. try changing `EtherServiceRequest.path` from:

```
    var path: String {
        return "/"
    }
```

to:

```
    var path: String {
        return ""
    }
```

There are a few places which accesses `EtherServiceRequest`. Not sure if this is compatible with all of them


This came from the docs (which works):

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []}' "https://mainnet.infura.io/v3/da3717f25f824cc1baa32d812386d93f"
```

Our equivalent has a trailing slash:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []}' "https://mainnet.infura.io/v3/da3717f25f824cc1baa32d812386d93f/"
```

**Comment by James-Sangalli** [comment]
@hboon excellent spotting

**Pull request merged**
