### PR TITLE
Make pending ERC20/721 sends in Activity tab be displayed using the new Activity cells rather than old-style transactions

### PR DESCRIPTION
**Pull request by hboon**
Before PR|After PR
-|-
|

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@hboon what happens if the tx fails?

**Comment by James-Sangalli** [comment]
Also, how will the user know it is still pending?

**Comment by hboon** [comment]
> Also, how will the user know it is still pending?

Little grey icon shows it's pending. It's a little green tick if it's completed.

**Comment by hboon** [comment]
> @hboon what happens if the tx fails?

No idea. Don't think it's handled correctly. Was it ever supported for iOS when we had the transactions tab? Any way, it's good to have. Created #2238 as/so we can handle it separately.

**Review by James-Sangalli — APPROVED** [review]

**Pull request merged**
