### PR TITLE
Add in a check if keys for all wallets are not accessible on startup #2048

### LINKED ISSUE #2048: Add in a check if keys for all wallets are not accessible on startup
Probably have to iterate this a few times. Ideally something like:

1. Launch (not resume) app
2. Check keys are accessible
3. Inform user and "probably" go to the create new wallet screen

This is a bit tricky because we want to make sure the keys are really not accessible anymore (due to migration to a new device).

Related to: #1849

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #2048, #1849

### CODE REVIEW

**Comment by vladyslav-iosdev** [comment]
@hboon for me its not clear why do we need to paste it in MigrationInitializator.perform()
        i guess we need to perform it before we call
        if let wallet = keystore.recentlyUsedWallet ?? keystore.wallets.first, keystore.hasWallets {
            showTransactions(for: wallet)
        } else {
            resetToWelcomeScreen()
        }
        because wee need to remove unvailable wallets, and only then make decision what to do next. Or i mistake?

**Comment by hboon** [comment]
> @hboon for me its not clear why do we need to paste it in MigrationInitializator.perform(). I guess we need to > perform it before we call.
> if let wallet = keystore.recentlyUsedWallet ?? keystore.wallets.first, keystore.hasWallets { showTransactions(for: > wallet) } else { resetToWelcomeScreen() }

The reason I suggested we put it in MigrationInitializer.perform() is so it it's easier to locate it. i.e. it is a kind of migration.

You are right, we should do it before this check ^. How about a static func in `MigrationInitializer`? It'll still be located there but called at the right place?

Also what about this? Simpler? :

> I just realised there's another way to fix the problem: since the Realm database files are not backed up too, when the app launch, run through the 3 lists of wallets and check if the Realm database file exist, if not, remove that wallet from the list).

**Comment by vladyslav-iosdev** [comment]
Also i got a question, why do we call this function async? func `delete(wallet: Wallet, completion: @escaping (Result<Void, KeystoreError>) -> Void)` it called piece of code, `!UIApplication.shared.isProtectedDataAvailable` in background thread, but this one should be called only in main thread.

**Comment by vladyslav-iosdev** [comment]
> @hboon for me its not clear why do we need to paste it in MigrationInitializator.perform(). I guess we need to > perform it before we call.
> if let wallet = keystore.recentlyUsedWallet ?? keystore.wallets.first, keystore.hasWallets { showTransactions(for: > wallet) } else { resetToWelcomeScreen() }
> 
> The reason I suggested we put it in MigrationInitializer.perform() is so it it's easier to locate it. i.e. it is a kind of migration.
> 
> You are right, we should do it before this check ^. How about a static func in MigrationInitializer? It'll still be located there but called at the right place?
> 
> Also what about this? Simpler? :
> 
> I just realised there's another way to fix the problem: since the Realm database files are not backed up too, when the app launch, run through the 3 lists of wallets and check if the Realm database file exist, if not, remove that wallet from the list).

yep, i realized that it's easier to implement.

**Comment by hboon** [comment]
> Also i got a question, why do we call this function async? func `delete(wallet: Wallet, completion: @escaping (Result<Void, KeystoreError>) -> Void)` it called piece of code, `!UIApplication.shared.isProtectedDataAvailable` in background thread, but this one should be called only in main thread.

Do you mean why there is an async here in `EtherKeystore`?

```
    func delete(wallet: Wallet, completion: @escaping (Result<Void, KeystoreError>) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let strongSelf = self else {
```

I don't know. We inherited that code :) My guess is the developer felt/thought that the deleting work takes a bit of time and didn't want to block the UI.

Where does it call `UIApplication.shared.isProtectedDataAvailable` though?

**Comment by hboon** [comment]
> yep, i realized that it's easier to implement.

Ok, would you think about it a bit and implement it if it's good? But can you also verify that the Realm database is created immediately when the user create/import/watch a database? This is to guard against this flow:

1. Create wallet (are the Realm database files created immediately?)
2. Immediately kills app (or low battery and iOS kills it)
3. Launch app
4. New code checks that Realm database is not there, delete the wallet address from the list (and thus losing access to the key)

**Comment by vladyslav-iosdev** [comment]
> Where does it call `UIApplication.shared.isProtectedDataAvailable` though?

it get called in `init` method
`(try? LegacyFileBasedKeystore(analyticsCoordinator: analyticsCoordinator))?.delete(wallet: wallet) `

**Comment by hboon** [comment]
> > Where does it call `UIApplication.shared.isProtectedDataAvailable` though?
> 
> it get called in `init` method
> `(try? LegacyFileBasedKeystore(analyticsCoordinator: analyticsCoordinator))?.delete(wallet: wallet)`

Oh. That's no good. Calling `UIApplication.shared.isProtectedDataAvailable` on a background thread seems to be harmless for now although the main thread checker complains about it.. Maybe wrap this line with a  dispatch to main in a separate PR?

> `(try? LegacyFileBasedKeystore(analyticsCoordinator: analyticsCoordinator))?.delete(wallet: wallet)`

Not the best approach, but `LegacyFileBasedKeystore` shouldn't matter much anymore since we have moved away from storing them that way for more than a year:

```
$ gl -S 'LegacyFileBasedKeystore'
commit 1e6a51b7feba2a401cf0cf56a0192d1a97a469ca
Author: Hwee-Boon Yar <hboon@motionobj.com>
Date:   2019-07-04 16:29:35 +0800

    Support HD wallets, only using account 0, as well as raw private keys 
```

**Comment by vladyslav-iosdev** [comment]
> Oh. That's no good. Calling `UIApplication.shared.isProtectedDataAvailable` on a background thread seems to be harmless for now although the main thread checker complains about it.. Maybe wrap this line with a dispatch to main in a separate PR?
> 
> > `(try? LegacyFileBasedKeystore(analyticsCoordinator: analyticsCoordinator))?.delete(wallet: wallet)`
> 
> Not the best approach, but `LegacyFileBasedKeystore` shouldn't matter much anymore since we have moved away from storing them that way for more than a year:

i guess it will not be a problem if we will create wallet/delete wallet in main instead of background thread. (backround thread improve nothing here, as i understand)

**Comment by hboon** [comment]
> i guess it will not be a problem if we will create wallet/delete wallet in main instead of background thread. (backround thread improve nothing here, as i understand)

Hmm.. makes sense. Try? Remember not to change anything else. This is delicate.

**Comment by vladyslav-iosdev** [comment]
> > i guess it will not be a problem if we will create wallet/delete wallet in main instead of background thread. (backround thread improve nothing here, as i understand)
> 
> Hmm.. makes sense. Try? Remember not to change anything else. This is delicate.

yep, ok! u know i just checked it, and found that creating wallet sync cause not a big issue, (but anyway, its issue), that wallet creates too fast now, and we don't see creating wallet indicator. adding here some delay make no sence because. Does it make sence create wallet sync instead of async?

**Comment by hboon** [comment]
> Does it make sence create wallet sync instead of async?

No. Since we show that green success overlay upon creation, we don't need the creating wallet indicator if it's fast and synchronous (or if it's async and still fast).

**Comment by vladyslav-iosdev** [comment]
> No. Since we show that green success overlay upon creation, we don't need the creating wallet indicator if it's fast and synchronous (or if it's async and still fast).

ok, i didn't touch it, and left as it is.

**Comment by hboon** [comment]
Pushed after rebase master.

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
@James-Sangalli this looks good to me, Would you help to take a look at this too? This describes the problem: https://github.com/AlphaWallet/alpha-wallet-ios/issues/2048#issuecomment-671774855

**Comment by hboon** [comment]
@James-Sangalli bump

**Comment by hboon** [comment]
Rebased master before doing a check again, to be sure.

**Pull request merged**
