### PR TITLE
Fix Swift Package Manager error when building

### LINKED ISSUE #4310: SPM error when building
Screenshot 2022-04-13 at 12 22 16 PM

### PR DESCRIPTION
**Pull request by hboon**
Fixes #4310

@oa-s do you know why? Does both before and after PR work for you?

### CODE REVIEW

**Review by oa-s — APPROVED** [review]

**Comment by oa-s** [comment]
I will check

**Comment by hboon** [comment]
Ok, buzz here once you have confirmed post-PR works for you then I'll merge.

**Comment by eviltofu** [comment]
Can we use one of these flags to prevent the Packages.resolved file to be updated every build?
```
    -resolvePackageDependencies                              resolves any Swift package dependencies referenced by the project or workspace
    -disableAutomaticPackageResolution                       prevents packages from automatically being resolved to versions other than those recorded in the `Package.resolved` file
    -onlyUsePackageVersionsFromResolvedFile                  prevents packages from automatically being resolved to versions other than those recorded in the `Package.resolved` file
    -disablePackageRepositoryCache                           disable use of a local cache of remote package repositories
    -packageCachePath                                        path of caches used for package support
```

**Comment by hboon** [comment]
Force pushed after rebase master with no other modifications to make it clearer there is just 1 commit.

**Comment by hboon** [comment]
> Can we use one of these flags to prevent the Packages.resolved file to be updated every build to solve this issue?

Xcode isn't doing that. And it shouldn't. I *think* the issue was that it read `Packages.resolved`, think it's updated (so didn't resolve, rightfully), but somehow fail to fetch the specified dependencies; and my fix by upgrading it (it worked though) was the wrong way to go. Anyway, this seems to have fixed it self and the pre-PR `Package.resolved` builds now. So closing it.

**Pull request closed without merging**
