### PR TITLE
Move the search bar down, move Add/Hide Tokens #3444

### LINKED ISSUE #3444: Move the search bar down, move Add/Hide Tokens
**Changes:**
* Replace "My Wallet Address" with the additional menu icon
* When revealed additional menu, show two options "My Wallet Address" and "Add/Hide Tokens"
* Move search bar where "Add/Hide Tokens" was before

**Positives**
* More clear interface
* Less real estate occupied by "Add/Hide Tokens"
* We allow Android to be identical to iOS, and it was difficult to include a search bar anywhere on Android
* I found people are confused what's behind these two icons in the top right (when people are looking for QR Code scanner, do I have to tap on "QR Code" icon or "Camera"?

Screenshot 2021-11-17 at 10 05 16

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes #3444

### CODE REVIEW

**Comment by hboon** [comment]
Looks ok. In case you missed it, don't forget "Copy Address" https://github.com/AlphaWallet/alpha-wallet-ios/issues/3444#issuecomment-972764762

**Comment by hboon** [comment]
Seems the PR is restricted to changing the Wallet tab's navigation button for now and not the search bar yet. Do you mean if I take over this PR and merge in the navigation button changes, and you can start a different one for the search bar change?

**Comment by hboon** [comment]
i.e. I'll scope down this PR to:

Add copy address functionality to Wallet tab navigation button (so there's an actionsheet)

**Comment by vladyslav-iosdev** [comment]
@hboon its ready to review

**Review by hboon — APPROVED** [review]
Great! Can you fix the test suite?

**Comment by hboon** [comment]
Force pushed after rebase master

**Pull request merged**
