### PR TITLE
AW_Kaleido integration - added sign/ send transactions using web3Swif…

### PR DESCRIPTION
**Pull request by LikaIOS**
AW_Kaleido first step integration - added sign/ send transactions using web3Swift, Kaleido platform APIs, creds; Manually added ERC20 token and try out transferring using Kaleido APIs. Reused existing app UI for integration tests.

Link to quick Kaleido start tutorial - https://drive.google.com/file/d/1mMcoA6kbAW4Li3QNHMSfxYztJIdNU2ah/view

Test account creds to Kaleido platform  - https://next.kaleido.io/login
Login - faraga7494@shzsedu.com
Pass - Test1234$$

### CODE REVIEW

**Comment by hboon** [comment]
@LikaIOS thanks for the PR. I'm looking at it. I've tried to import the key "0xca33xxx" but there isn't a balance (native crypto or the KETH token) for it. Is there a wallet, with transactions we can test the PR against?

**Comment by AW-STJ** [comment]
@LikaIOS - can you fork the current AlphaWallet-ios repo and then submit a PR there? This code is intended to create a version of AlphaWallet that talks to Kaleido natively.

**Comment by LikaIOS** [comment]
> @LikaIOS thanks for the PR. I'm looking at it. I've tried to import the key "0xca33xxx" but there isn't a balance (native crypto or the KETH token) for it. Is there a wallet, with transactions we can test the PR against?

@hboon Please check - here is the wallet in Kaleido console:
https://classic.kaleido.io/nodes/e0hr1zgg19/e0iipo4q1k/e0wrfvrsl9/wallet
Login - faraga7494@shzsedu.com
Pass - Test1234$$
tried to fund "0x3b1b62e0080cd706c46f66eb092f6b21965dcd98"  account.
Please let me know if any info needed.

**Comment by hboon** [comment]
@LikaIOS Sorry, was away for a while. I can't access the Kaleido console https://classic.kaleido.io/nodes/e0hr1zgg19/e0iipo4q1k/e0wrfvrsl9/wallet. It just display "Unauthorized" in the browser. The wallet 0x3b1b62e0080cd706c46f66eb092f6b21965dcd98 shows up as having a zero balance for me.

I can't verify if it works, but I took a look at the code. We have some existing code that works with Kaleido, maybe you can see if it works for your environment and to tweak it so it works. The idea is to:

* Introduce a new chain by adding to `RPCServer`. In your version, you can just make sure that only this chain is active eg. `.kaleido`
* Add a class implementing `SingleChainTransactionDataCoordinator` which supports fetching transaction history from Kaleido: `SingleChainTransactionKaleidoDataCoordinator` https://gist.github.com/hboon/7e0f6004b6eb5877d1cae9d48e68f50a
* Add a class `RawKaleidoTransaction` supporting Kaleido transactions: https://gist.github.com/hboon/c5979b17650629d4803b485cf7e9b0d5
* Modify `AlphaWalletService.swift` to added the cases and make sure they use the correct endpoints/query parameters
* Similar modifications across the app based on the compiler complaining that `RPCServer.kaleido` is not handled in switch statements

This fits better into our code base architecture so it'll be easier to maintain and pull in future changes from our repo into yours. You'll have to massage this a bit to get it to build.

**Comment by LikaIOS** [comment]
@hboon to access the Kaleido console you need to first login:
https://next.kaleido.io/login
Login - faraga7494@shzsedu.com
Pass - Test1234$$
And then you will have access to wallet - https://classic.kaleido.io/nodes/e0hr1zgg19/e0iipo4q1k/e0wrfvrsl9/wallet

thanks for the feedback, I will check the idea and write you back if any questions

**Comment by hboon** [comment]
Thanks!

**Comment by hboon** [comment]
Closing due to inactivity

**Pull request closed without merging**
