### PR TITLE
Make entire address and ENS name labels tappable to trigger the copy action

### LINKED ISSUE #1806: Make entire address and ENS name labels tappable to trigger the copy action
Currently only the blue icon is tappable. Note that the screenshot doesn't show the ens name label. Look around `RequestViewController.copyEnsButton`. The screen is accessible from Settings > My Wallet Address.

Simulator Screen Shot - iPhone X - 2020-05-19 at 23 20 14

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Make entire address and ENS name labels tappable to trigger the copy action #1806

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev assign as reviewer :)

**Comment by hboon** [comment]
@vladyslav-iosdev Can you help with these:

- [ ] Make the PR only contain the commit relevant for the issue, in this case, looks like only the commit: f306154 
- [ ] Change the commit message to reflect why something is done. If it's just a change because of requirements, then just a 1-liner describing it (which is often the issue title or a variation of it). End it with the issue number
- [ ] Make the title of the PR reflect the issue (somtimes just copying over the issue title works. It'll likely match the commit message)

So in this case, title can be:

"Make entire address and ENS name labels tappable to trigger the copy action"

and the commit message:

"Make entire address and ENS name labels tappable to trigger the copy action #1806"

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev Can you help with these:
> 
> * [ ]  Make the PR only contain the commit relevant for the issue, in this case, looks like only the commit: [f306154](https://github.com/AlphaWallet/alpha-wallet-ios/commit/f306154bce7d16373fdb1f8edd9f0e6117dd3454)
> * [ ]  Change the commit message to reflect why something is done. If it's just a change because of requirements, then just a 1-liner describing it (which is often the issue title or a variation of it). End it with the issue number
> * [ ]  Make the title of the PR reflect the issue (somtimes just copying over the issue title works. It'll likely match the commit message)
> 
> So in this case, title can be:
> 
> "Make entire address and ENS name labels tappable to trigger the copy action"
> 
> and the commit message:
> 
> "Make entire address and ENS name labels tappable to trigger the copy action #1806"

Let me know if i did every thing correctly, because i am not sure.

**Comment by hboon** [comment]
@vladyslav-iosdev Would you be able to add it as a collaborator in the GitHub settings for your repo?

**Comment by hboon** [comment]
@vladyslav-iosdev try this:

(The master branch has changed quite significantly since you fork because we did a big merge to master today)

Ok, assuming that you only need this commit: f306154bce7d16373fdb1f8edd9f0e6117dd3454. One way to do it is, we create a new branch "branch1" and fix it branch1, then update this branch to be the same as branch1:

git checkout master
git pull upstream master #fetch the updated master. Replace "upstream" with what is pointing to the original alphawallet repo
git checkout -b branch1 #new throwaway branch
git cherry-pick f306154bce7d16373fdb1f8edd9f0e6117dd3454 #the 1 commit you want to copy
#branch1 is how your feature branch will look like. Verify it builds, etc
git checkout 1806
git reset --hard branch1 #Force your feature branch 1806 to be like branch1
git push origin 1806 --force #Replace "origin" with what is pointing to the repo in your account

**Pull request closed without merging**
