### PR TITLE
Add switching between fiat currencies feature #5758

### LINKED ISSUE #5758: Add switching between fiat currencies feature

### PR DESCRIPTION
**Pull request by oa-s**
Closes #5758

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
The charts don't appear but not sure if it's just this PR.

I didn't check, but is the currency default to USD for users who have not enabled the feature flag? Especially new installs

**Review by hboon — APPROVED** [review]
The charts don't appear but not sure if it's just this PR.

I didn't check, but is the currency default to USD for users who have not enabled the feature flag? Especially new installs

The send screen should probably be updated too? But we can leave it for a separate PR:

Screenshot 2022-11-30 at 11 01 52 AM

**Comment by oa-s** [comment]
> I didn't check, but is the currency default to USD for users who have not enabled the feature flag? Especially new installs

i will double check but yes, default currency is USD

**Comment by oa-s** [comment]
> The charts don't appear but not sure if it's just this PR.
> 
> I didn't check, but is the currency default to USD for users who have not enabled the feature flag? Especially new installs
> 
> The send screen should probably be updated too? But we can leave it for a separate PR:
> 
> Screenshot 2022-11-30 at 11 01 52 AM

oh yes, it didn't applied for amount text field

**Comment by hboon** [comment]
Just in case it's ready, buzz me :)

**Comment by oa-s** [comment]
> Just in case it's ready, buzz me :)

@hboon looks ok now

**Comment by hboon** [comment]
Got a very strange crash at https://github.com/oa-s/alpha-wallet-ios/blob/52081f6e986dbd33c5c76d66cc42907585d95ffb/modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptFileIndices.swift#L68

```
if contractsToFileNames[contract].isEmpty {
```

It crashed complaining that it's nil. It looks like the follow extension (which is in the same module) isn't loaded?

```
extension Optional where Wrapped: Collection {
    public var isEmpty: Bool {
        switch self {
        case .none:
            return true
        case .some(let value):
            return value.isEmpty
        }
    }
}
```

After I added some debug statements, I can't reproduce it anymore, even after removing the debug statements. I don't think it's related to this PR.

**Review by hboon — COMMENTED** [review]
Remember to reset this:

```
public let shouldPretendIsRealWallet = true
```

Maybe not related to this PR? But "All Funds" show 3.0958, but the actionsheet total is 3.0956 ETH.

Screenshot 2022-12-02 at 3 20 57 PM

**Comment by oa-s** [comment]
> Maybe not related to this PR? But "All Funds" show 3.0958, but the actionsheet total is 3.0956 ETH.

yes, its value - gas

**Comment by oa-s** [comment]
> Got a very strange crash at https://github.com/oa-s/alpha-wallet-ios/blob/52081f6e986dbd33c5c76d66cc42907585d95ffb/modules/AlphaWalletFoundation/AlphaWalletFoundation/TokenScriptClient/Models/TokenScriptFileIndices.swift#L68
> 
> ```
> if contractsToFileNames[contract].isEmpty {
> ```
> 
> It crashed complaining that it's nil. It looks like the follow extension (which is in the same module) isn't loaded?
> 
> ```
> extension Optional where Wrapped: Collection {
>     public var isEmpty: Bool {
>         switch self {
>         case .none:
>             return true
>         case .some(let value):
>             return value.isEmpty
>         }
>     }
> }
> ```
> 
> After I added some debug statements, I can't reproduce it anymore, even after removing the debug statements. I don't think it's related to this PR.

hmm, haven't seen that

**Comment by oa-s** [comment]
maybe need to create a new issue for that, definatelly not related to currencies changing

**Comment by hboon** [comment]
> > Maybe not related to this PR? But "All Funds" show 3.0958, but the actionsheet total is 3.0956 ETH.
> 
> yes, its value - gas

But shouldn't it show `3.0956` above "All Funds" then? Maybe `3.0958` is always how it worked? Never mind that.

**Comment by hboon** [comment]
> maybe need to create a new issue for that, definatelly not related to currencies changing

Created #5899.

**Comment by hboon** [comment]
@oa-s this one's not ready yet?

**Comment by oa-s** [comment]
looks like its ready

**Comment by oa-s** [comment]
only thing i can facing its when we got a lot of tokens it takes to long time to resolve tickers, especially for ticker ids resolving. Might need to check resolvation logic, in another pr.

**Comment by hboon** [comment]
Maybe related to:

> the last isssue to fix is left (sometimes tokens don't get updated when a new tickers resolved)

After I switch currency and the UI reloads, showing the Wallet tab, I wait for ~1 minute and the fiat data isn't showing up (it was shown before I switched currency):

Screenshot 2022-12-15 at 9 49 01 AM

Pulling down to refresh shows this after ~2 secs:

Screenshot 2022-12-15 at 9 49 28 AM

**Comment by hboon** [comment]
If you prefer to merge first, go ahead since there's a feature flag.

**Pull request merged**
