### PR TITLE
Fix unexpected bottom inset which appears while resuming from background #2466

### LINKED ISSUE #2466: Fix unexpected bottom inset which appears while resuming from background

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Fixes #2466

before PR
IMG_0531

after PR
IMG_0532

### CODE REVIEW

**Review by hboon — COMMENTED** [review]
Can you help make before and after screenshots to illustrate the problem?

**Comment by vladyslav-iosdev** [comment]
> Can you help make before and after screenshots to illustrate the problem?

it seems like i can't reproduce it, but yesterday i was able to reproduce it several times.

**Comment by vladyslav-iosdev** [comment]
@hboon  Just reprodused this issue

**Comment by hboon** [comment]
How do you reproduce it?

**Comment by vladyslav-iosdev** [comment]
Steps to reproduce:
- enable Passcode/FaceID on settings scree
- move app to background
- move app to foreground
- repeat last two steps several times.

**Comment by hboon** [comment]
I still can't reproduce it. Can you do it reliably?

**Review by hboon — APPROVED** [review]
I can't reproduce it. But I'll take your word for it :)

**Pull request merged**
