### PR TITLE
Turn on Preserve Vector Data in the pdf. #3762

### LINKED ISSUE #3762: Set Preserve Vector Data for PDFs in XCAssets file
I noticed some PDFs in the XCAssets file don't have the Preserve Vector Data checkbox clicked. Someone should go through all the PDF images in the XCAssests file and turn Preserve Vector Data on.

### PR DESCRIPTION
**Pull request by ramen2020**
[issues3762](https://github.com/AlphaWallet/alpha-wallet-ios/issues/3762)

closes #3762

## problem
In the pdf, PreserveVectorData was turned on in 7 cases, while it was turned off in 176 cases.

## try
In order to eliminate human error, I created a program to correct the preserve_vector_data of the pdf to be on.
In order to turn preserve_vector_data on, it was necessary to add the following property values to Contents.json, which is associated with the corresponding image, so the program was created to add them.

```
"properties" : {
    "preserves-vector-representation" : true
 }
```

I place it in alpha-wallet-ios/AlphaWallet/Assets.xcassets/search_pdf.py and ran that program and turned on PreserveVectorData for all the pdfs, there are 183 of them.

## Test Results
Of course, I checked everything visually and made sure PreserveVectorData was turned on in the pdf image.

※ search_pdf.py is not included in the commit.

Here is the program
```python
import os
from pathlib import Path

def updatePreserveVectorDataExistProperties(filePath):
    read_path = Path(filePath)
    content = read_path.read_text()

    # replace
    content = content.replace(
'''
  },
  "properties" : {
''',
'''
  },
  "properties" : {
      "preserves-vector-representation" : true
'''
)
    # write
    read_path.write_text(content)

def updatePreserveVectorData(filePath):
    read_path = Path(filePath)
    content = read_path.read_text()

    # replace
    content = content.replace(
'''
  },
  "properties" : {
''',
'''
  },
  "properties" : {
      "preserves-vector-representation" : true,
'''
)


    # replace
    content = content.replace(
'''
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
''',
'''
  "info" : {
    "author" : "xcode",
    "version" : 1
  },
  "properties" : {
      "preserves-vector-representation" : true
  }
'''
)

    content = content.replace(
'''
  "info" : {
    "version" : 1,
    "author" : "xcode"
  }
''',
'''
  "info" : {
    "version" : 1,
    "author" : "xcode"
  },
  "properties" : {
      "preserves-vector-representation" : true
  }
'''
)
  
    # write
    read_path.write_text(content)

preserve_vector_data_on_pdf_count = 0
preserve_vector_data_off_pdf_count = 0
for files in os.listdir("./"):
    if os.path.isdir(files):
        for file in os.listdir("./" + files):
            base, ext = os.path.splitext(file)
            if ext == '.pdf':
                with open("./" + files + "/Contents.json") as f:
                    if '"preserves-vector-representation" : true' in f.read():
                        preserve_vector_data_on_pdf_count += 1
                    elif '"properties" : {' in f.read():
                        preserve_vector_data_off_pdf_count += 1
                        updatePreserveVectorDataExistProperties("./" + files + "/Contents.json")
                        print("./" + files + "/Contents.json") # preserves-vector-representation" : false ファイル
                    else:
                        preserve_vector_data_off_pdf_count += 1
                        updatePreserveVectorData("./" + files + "/Contents.json")
                        print("./" + files + "/Contents.json") # preserves-vector-representation" : false ファイル

print("::: preserve_vector_data_off_pdf_count : ", preserve_vector_data_off_pdf_count)
print(":::::: preserve_vector_data_on_pdf_count", preserve_vector_data_on_pdf_count)


```

### CODE REVIEW

**Comment by eviltofu** [comment]
In the header could you add in a closes: 3762 so that when this PR is merged, the other issues are closed automatically as well? @ramen2020

**Comment by ramen2020** [comment]
@eviltofu
3762 added to the header.

**Comment by eviltofu** [comment]
> @eviltofu
> 3762 added to the header.

@ramen2020 I'm sorry I wasn't clear I meant in the first comment but adding that in the title is good too.

Screenshot 2022-01-25 at 9 46 41 AM

**Comment by eviltofu** [comment]
@ramen2020 Sorry I wasn't clear. Adding that in the title is good too. 

Screenshot 2022-01-25 at 9 46 41 AM

**Comment by ramen2020** [comment]
@eviltofu 
I'm sorry. I've added it and would like you to check it again.

**Review by hboon — APPROVED** [review]
Looks great. Thank you @ramen2020 !

How did you come to know about our project and what made you decide to contribute?

**Comment by ramen2020** [comment]
@hboon 
Thanks Marge.
I found this when I was searching for issues on Github. The project looked interesting, so I wanted to participate and contribute myself!
I want to participate again.

**Comment by hboon** [comment]
@ramen2020 We'll certainly prepare more as they come up. Thanks again!

**Pull request merged**
