### PR TITLE
Empty new features view #3684

### LINKED ISSUE #3684: Empty new features view
name: Bug Report
about: Using AlphaWallet, but it's not working as you expect?

---

**Describe the bug**
Empty features view

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior

1. uninstall the AlphaWallet app
2. install the AlphaWallet app on iPhone 8 Plus simulator with iOS 15

**Expect**
6a. List of features is displaying

**Observed**
6b. List of features is empty

**Screenshots**
Screenshot 2022-01-11 at 09 38 07

**Version or build number number**
Version number: 3.34 (417)

### PR DESCRIPTION
**Pull request by oa-s**
Closes  #3684

### CODE REVIEW

**Review by hboon — APPROVED** [review]
@oa-s would you help split out a commit for removing the `JavaScriptKit` pod?

**Comment by hboon** [comment]
So the problem here is that the height constraint isn't set?

**Comment by hboon** [comment]
Merge when you are ready.

**Comment by oa-s** [comment]
> So the problem here is that the height constraint isn't set?

seems like yes, for some reasons it doesn't get updated with its contents height

**Pull request merged**
